cozy/cozy-banks

src/ducks/account/AccountSwitch.jsx
src/ducks/balance/Balance.jsx
src/ducks/filters/index.js
src/locales/en.json
src/locales/fr.json
src/selectors/index.js

This adds a virtual groups that group the user's accounts by their types.

feat: add virtual groups for each accounts types

---

package.json
src/components/PopupSelect/index.jsx
src/documents/transaction.js
src/ducks/commons/Nav.jsx
src/ducks/filters/SelectDates.styl
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.styl
src/ducks/transactions/TransactionsPage.jsx
src/reducers/index.js
yarn.lock

Show the account associated to each transaction on the movements list : 
If the user is filtering transactions on a particular account, we don't show this information anymore : 
Also, on desktop, the date column is now after the label column.

feat: show transaction account on movements list

---

src/selectors/index.js

Only show a virtual group if an account type has more than one account. And don't create a group for accounts that don't have a type.

feat: add more conditions for showing virtual groups

---

src/ducks/transactions/TransactionActions.jsx
src/ducks/transactions/Transactions.jsx

When component is updated a old action is display with the new transaction because `action` was already informed.

Fix wrong transaction

---

src/ducks/account/helpers.js
src/ducks/transactions/Transactions.jsx

When the user edited the label of an account, this change was not reflected on the transaction page.

fix: reflect changes on transactions page when the user edit an account label

---

config/webpack.config.base.js

Services build is broken because cozy-konnector-libs is using a spread operator that needs to be transpiled. See https://travis-ci.org/cozy/cozy-banks/builds/368619692#L766

chore: fix services build

---

src/ducks/mobile/push.js

We had an issue with the push notifications : 
* On login, push object was initialized and push notifications were shown
* On logout, push notifications were stopped, but the push object was not resetted
* On new login, we already had a push object so we didn't reinitialized it => no push notification could be received

fix: reset push object on logout

---

src/ducks/settings/services.js

We had a settings like that : 
```
{
notifications: {
toto: true,
/* no last seq*/
},
categorization: {
}
}
```
If this setting was merged with the default, the existing notifications attribute would override the default notification settings and there would be no lastSeq.
`merge` is now used to deeply merge the default and the existing settings.

🐝 fix: merge deeply instead of shallowy to completely merge default settings

---

src/ducks/transactions/TransactionsPage.jsx

We already have a system that skip months without any transactions when we click on previous/next arrows in the date filters. But there was the following problem : 
Say we have these months that have some transactions : 
```
[
"2018-04",
"2018-01",
"2017-08",
"2017-07"
]
```
If we are currently on `2017-08` and click on the next arrow, then we should show `2018-01`. But we were showing `2018-04`. This is because we are looking for the first month greater than the current month in the previous array. But if it's sorted from the most recent to the oldest, then the first month greater than the current month is always the most recent month. Here `2018-04`.
To fix this, we should do the following : 
* If we want the previous month with transactions : sort the array of months from the most …

fix(date filter): going to next month with transactions was going to last month with transactions

---

src/styles/main.styl

We had the following problem since I increased the footer z-index to make it visible even when we have a transaction modal opened :

fix: increase cozy-bar drawer z-index on mobile so it is above the footer

---

src/components/Select/index.jsx
src/ducks/filters/SelectDates.jsx
src/ducks/filters/SelectDates.styl

Some adaptations on the mobile date filter : 
* Use the good colors for the text and the icons
* Make it always use the full width : both selects adapts their width, and the buttons have fixed width

Adaptive date filter mobile

---

src/ducks/filters/SelectDates.jsx
src/ducks/filters/SelectDates.styl

Year select takes 1/3 of the space, and month select 2/3.

feat(dates filter): apply a flex-grow ratio on month and year selects

---

src/ducks/apps/index.js
src/ducks/settings/AccountSettings.jsx
src/ducks/settings/AccountsSettings.jsx
src/ducks/settings/CollectLink.jsx
src/ducks/transactions/TransactionsPage.jsx

Collect was identified by its source in order to provide a direct deep link (the "Add an account" link in account settings). Since collect is now in the registry, we have to identify it via its _id.

fix add account link

---

src/ducks/categories/CategoriesChart.jsx

The colors were not sorted in the right order in the categories chart. It's now the case.
https://testbanksfixcategorieschart-banks.cozy.works/#/categories

feat(CategoriesChart): always sort parts in reverse order

---

src/ducks/mobile/userAgent.js
src/main.jsx
src/targets/mobile/config.xml

Set the user agent to a string `{DEVICE NAME} {APP IDENTIFIER}-{APP VERSION} {ORIGINAL USER AGENT}` when the app is started.

feat(mobile app): set custom user agent on app start

---

src/ducks/onboarding/Onboarding.jsx

In aeb0a471ffbceca245ba8f1be40750519b382b0c, we replaced the internal Hero component
by the one from cozy-ui, but there was custom code in the Hero styl to remove the last
two sections on mobile.

🐝 fix: only show 1 onboarding section on mobile

---

src/components/Figure/Figure.jsx
src/ducks/categories/Categories.jsx
src/ducks/categories/CategoriesHeader.jsx
src/ducks/categories/CategoriesHeader.styl
src/ducks/categories/CategoriesPage.jsx

* Remove padding on income toggle on mobile
* Fix "transaction(s)" plural
* If a category has no data, then show "－ €" as its total
* When the selected period has no data, don't show the income toggle and the graph

Some fixes on categories page

---

src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/Transactions.jsx

Fab has a hard to reproduce bug : while recategorizing transaction, at some
point the app breaks (exception in console). The app has to be restarted
to work again. This bug is not 100% reproducible which
leads me to believe it is a race condition bug.
I suspect that it is to me caused by the fact
that we were finding the transaction, in the transaction list received
in props, by its transaction id. This means that if this list at some
point, loses this transaction, for one reason or another, the Transaction
modal is getting an undefined transaction.
To mitigate this, I propose that we rely on the document store to get
the transaction. This way we are more sure not to rely on a state/incomplete
source of data.

🐝 fix: use only one source of truth

---

src/ducks/categories/CategoriesPage.jsx
src/ducks/settings/constants.js

When the user changes the state of the "show incomes" toggle, we persist it in the settings. So the next time the user goes on the categorization page, his/her preference is still here.

feat(Categories): persist the show incomes toggle state in the settings

---

src/ducks/categories/Categories.jsx
src/ducks/categories/CategoriesHeader.jsx

Always show the categories chart, even if there is no data for the period.
On mobile, don't show the text indicating that there's no data

fix(Categories): always show the chart even if there is no data

---

src/ducks/transactions/TransactionModal.jsx

In https://github.com/cozy/cozy-banks/pull/151, @ptbrowne fixed something that looks like a race condition bug. But after, the account and bank name were not shown in the transaction modal anymore, because we don't link the transaction to the banking account anymore. This PR intends to fix this.

fix(TransactionModal): show account and bank again

---

package.json
src/components/App.jsx
src/components/App.styl
src/ducks/transactions/Page.jsx
src/ducks/transactions/Page.styl
src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionModal.styl
yarn.lock

This introduce a `Page` component that is 99% like a `Modal`, but shows the footer. It could be extracted in Cozy UI if it's needed. But maybe it needs a cleaning step before.
With that, we don't have problems with the footer being above modals anymore.

feat(TransactionModal): use Page component on mobile

---

src/components/BackButton/index.jsx
src/components/SelectDates/SelectDates.jsx
src/components/SelectDates/SelectDates.styl

This increases some clickable area on mobile. Mostly on the mobile date select. It also adds a margin to the back button (the same as the cozy bar menu button), so the page title don't jump anymore.

Increase clickable areas on mobile

---

src/ducks/filters/index.spec.js

* transactions are returned already sorted by the reducer
* with the introduction of virtual groups, a method had to be mocked

🐝 fix: tests

---

src/components/SelectDates/SelectDates.jsx
src/ducks/transactions/Transactions.jsx

🔧 chore: must apply ellipsis to children for it to be effective
🔧 chore: select date is no longer truncated

Two small graphic fixes

---

src/components/SelectDates/SelectDates.jsx
src/components/SelectDates/utils.js
src/components/SelectDates/utils.spec.js

The next button is disabled if all options after it are disabled.

🐝 fix: disable next button when months after have no transactions

---

src/ducks/transactions/TransactionModal.jsx

> quand j'ouvre le détail d'une opération je vois le détail de l'opérations avec le champ banque notamment : dans ce champ est présent la notion "sans secure key"

🐝 fix: need to use helper to print institution label to remove secure key part

---

src/ducks/balance/Balance.jsx

Groups were not fetched on the balances page, so they were not shown when first arriving on the app.
I also added a little bit of immutability, because we were mutating props, which is bad.

fix(Balance): fetch groups from stack

---

src/ducks/transactions/TransactionActions.spec.jsx
src/ducks/transactions/actions/KonnectorAction.jsx
src/locales/en.json
src/locales/fr.json

This add a variation of the informative modal for health connectors : 
A different label for the CTA : 
A different content : 
For that, I made `InformativeModal` more generic by passing its content to its props.

Informative modal health

---

src/ducks/transactions/TransactionSelectDates.jsx
src/ducks/transactions/__snapshots__/TransactionSelectDates.spec.jsx.snap
src/ducks/transactions/actions/KonnectorAction.jsx

<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …

Release 0.7.8

---

.travis.yml

In PR from forks, we cannot decrypt encrypted env var, so we cannot add our ssh agent.
This step is only necessary when deploying. Deploying is not done in pull request builds.
https://docs.travis-ci.com/user/deployment#Pull-Requests

🐝 fix: use before_deploy to decrypt ssh key, deploy phase is bypassed in pr

---

src/ducks/transactions/TransactionsPage.jsx
src/utils/triggers.js
src/utils/triggers.spec.js

Claire has a legacy trigger whose content is encoded in base64. Banks did not recognize it as a konnector trigger and would display the "Install the connector" CTA, even if the konnector is already installed (and has a working trigger).

🐝 fix: supports legacy triggers

---

manifest.webapp

Safari does not send cookies with the request for the icon so
the icon must be available publicly.

🐝 fix: make the icon available when non authentificated

---

src/ducks/settings/CollectLink.jsx

This button was the last place where we used a hard coded redirection to collect. Now we use the same mechanism as in the `KonnectorAction` on mobile.

feat(CollectLink): use intents redirects

---

src/ducks/onboarding/ensureIsFirstSynced.js

On mobile app resume, fetch initial data, so when we accept TOS, when we come back on the app, we don't have the onboarding screen.

feat: Fetch initial data on resume

---

package.json
src/components/Select/index.jsx
src/components/Select/styles.styl
src/components/SelectDates/SelectDates.jsx
src/components/SelectDates/SelectDates.styl
src/targets/mobile/config.xml

The cozy-ui select has a problem on Android: when we click on the (transparent) overlay to close the select without interacting with elements on the page, the first time acts like if there was no overlay, then everything is normal on next tries.
Since we have been searching why we have this behaviour for a long time, without any success, and since we have another problem with the cozy-ui select, on iOS this time (the click handler is not triggered everywhere), I think it's better for us to just use native selects on mobile.
The advantages are:
* Better UX : options are large enough to click on it easily, whereas cozy-ui select's options are very small
* No more bugs : Android and iOS bugs are past
The disadvantage is: the design of the options is platform-dependent. But to me it's …

Use native selects on mobile

---

.babelrc
package.json
src/ducks/balance/Balance.jsx
src/ducks/balance/helpers.js
src/ducks/balance/helpers.spec.js
yarn.lock

Compute the balance history for each account when the user hits the Balances page.
The result is an object indexed by the account ID. And for each account, an array of objects with the shape:
```
{
"date": Date,
"balance": Number
}
```

feat: Compute balance history

---

src/ducks/transactions/actions/KonnectorAction.jsx

We were using `slug` for one intent and `konnector` for the other. The platformers told us that `slug` is the good one.

fix(KonnectorAction): Replace konnector option by slug in intent

---

package.json
src/components/Chart/LineChart.jsx
src/components/Chart/LineChart.md
src/components/Figure/Figure.jsx
src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.styl
src/ducks/balance/History.jsx
src/ducks/balance/History.md
src/ducks/balance/History.styl
src/ducks/balance/helpers.js
src/ducks/balance/helpers.spec.js
src/ducks/balance/history_data.json
src/locales/en.json
src/locales/fr.json
styleguide.config.js
yarn.lock

It uses static data for now. The balance history is passed in a rolling window algorithm with a size of 15. The result can be seen on the Balance page or in the styleguide

Balance history chart

---

src/components/Chart/LineChart.jsx
src/components/Chart/LineChart.md
src/ducks/balance/History.jsx

This adds a gradient under the balance history line chart :

Chart gradient

---

src/ducks/categorization/services.js

There were still lines that didn't have an identifier to find them easily in logs.

fix(categorization service): Add missing log identifiers

---

src/components/Chart/LineChart.jsx
src/components/Chart/LineChart.md
src/ducks/balance/Balance.jsx
src/ducks/balance/History.jsx
src/ducks/balance/History.styl
src/ducks/transactions/TransactionsPage.jsx
src/locales/en.json
src/locales/fr.json
src/main.jsx

There are two distincts UIs : 
One for the balances page, that shows the X axis and the current balance:
And one for the transactions page, that only shows the line: 
Some UI things that are related to interactions are not present in this PR, but will be in a next one.

Balance history UI

---

package.json
yarn.lock

This update gives us the opening of installed apps natively
instead of in the browser.

chore: update cozy-bar

---

config/webpack.config.dev.js

I propose to use cheap-module-eval-source-map when building for dev to get lines in source files in error stacktrace while developing.

chore: Use cheap-module-eval-source-map

---

package.json
src/components/FileIntentDisplay.jsx
src/ducks/authentication/MobileRouter.jsx
src/ducks/client/web.js
src/ducks/settings/AddAccountLink.jsx
src/ducks/transactions/TransactionSelectDates.spec.jsx
src/ducks/transactions/actions/KonnectorAction.jsx
src/utils/client.js
test/AppLike.jsx
test/client.js
yarn.lock

To remove cozy-client-js we should extract intent in a new lib.
This lib is cozy-interapp, we change instantiation to pass cozy-client

feat: Use cozy-interapp lib 🚜

---

src/ducks/transactions/TransactionModal.jsx

Since cozy-client returns the object instead of an array when there is only one result, we needed a small update.

fix(TransactionModal): Get a single result

---

src/ducks/client/links.js

For now we activate it only on mobile. Maybe later we will use it on web too.

feat: Activate PouchDB only on mobile

---

package.json
src/main.jsx
yarn.lock

On browsers without `fetch`, it is necessary to add a polyfill.

fix: Add fetch polyfill

---

package.json
yarn.lock

This fixes the weird behavior where the balance history chart was shown then removed.

chore(deps): Update cozy-flags to v1.2.5

---

src/ducks/balance/History.jsx
src/ducks/transactions/TransactionsPage.jsx

History calculation are done at each render of the transactions leading, to bad performance.
I will bring screeshots ;)

perf: Mv balance history computations to HistoryChart

---

package.json
yarn.lock

We come from v5.1.0. So we must be careful if something breaks. According to the [changelog](https://github.com/cozy/cozy-bar/releases/tag/v6.0.0), we only need to use `name_prefix` in our manifest, which we alreaydy do (see https://github.com/cozy/cozy-banks/blob/master/manifest.webapp#L41).
Ping @CPatchane and @gregorylegarec can you have a look and tell us if we miss something ?

chore(deps): Update cozy-bar to v6.1.3

---

src/ducks/balance/Balance.jsx
src/ducks/balance/History.jsx
src/ducks/balance/HistoryChart.jsx
src/ducks/balance/helpers.js
src/ducks/transactions/TransactionsPage.jsx

- extraction de la fonction `sortBalanceHistoryByDate` dans les helpers
- extraction du composant HistoryChart dans son fichier pour exporter correctement avec ses breakpoints

fix: Historychart error after refactor

---

src/ducks/transactions/__snapshots__/TransactionSelectDates.spec.jsx.snap

We don't have enough time right now to see what we can do to avoid updating snapshot every months, but we should consider an action.

test: Update TransactionSelectDates snapshot

---

src/ducks/transactions/actions/AppLinkAction.jsx

We have some cases in production where we show a "open in Collect" CTA on a transaction because the label contains "collect" (for example "Collectif [...]"), which is not intended

feat(AppLinkAction): Don't show collect

---

package.json
yarn.lock

This fixes the crash when we search a document that is not in the store

chore(deps): Update cozy-client to v3.4.0

---

package.json
yarn.lock

This fixes `cannot index document as it has no id` errors

chore(deps): Update cozy-client to v3.6.4

---

src/ducks/client/links.js

This behavior is already managed by cozy-pouch-link: https://github.com/cozy/cozy-client/blob/master/packages/cozy-pouch-link/src/PouchManager.js#L60-L79
It also manages the listeners removal, which we didn't do here.

refactor: Remove pause/resume replication

---

src/ducks/settings/GroupSettings.jsx
src/ducks/settings/GroupSettings.spec.js
test/fixtures/operations-merged.json

We were not passing an id to `existsById`, thus the account was never found in the collection and the toggle never checked.

fix(GroupSettings): Wrong toggle state

---

src/ducks/client/utils.js

The virtual groups didn't have a `raw` property, so we were returning all accounts instead of accounts associated to the selected virtual group.

fix: Bad balance for virtual groups on transactions page

---

manifest.webapp

We had this property twice in our manifest.

chore: Remove duplicated name_prefix in manifest

---

src/ducks/categories/CategoriesPage.jsx

This PR fix 2 bugs:
- save correctly settings
- when Cozy don't have `io.cozy.bank.settings` it create it with default value

fix: Save settings when Incomes toggle change

---

src/ducks/categories/helpers.js
src/ducks/categories/helpers.spec.js

The local categorization model is doing its work in the service for a while in production now. This PR intends to use the result of this model and show its result to the user. For the user, it means that his transactions are now categorized automatically based on his manual categorization habits.
The rules are the following:
* If there's a manual category, use it
* If there's no manual category, but there's a local category and the probability of this category is higher than a threshold (defined at `0.8`), then use it
* If there's no manual category, but there's a local category but its probability is lower than the threshold, use the automatic category
* If there's neither manual category not local category, use the automatic category

feat: Use local categorization model result

---

config/webpack.target.browser.js
config/webpack.target.mobile.js
docs/dev.md
package.json
src/ducks/client/links.js

If you want activate Pouch on web app, you need:
- a token
- launch your build with `FORCE_POUCH`
```
cozy-stack instances token-cli cozy.tools:8080 $(cat manifest.webapp | jq -r '[.permissions[] | .type] | join(" ")')
env FORCE_POUCH=true yarn watch
```
Launch your web application and in console javascript fill in the token and refresh the page:
```
flag('cozyToken', <your token>)
```
Now you can play with replication:
```
cozyClient.links[0].startReplication()
cozyClient.links[0].stopReplication()
```

feat: Add pouch on web to develop easily

---

src/ducks/billsMatching/Linker/Linker.js
src/ducks/billsMatching/Linker/Linker.spec.js
src/ducks/categories/helpers.js
src/ducks/categorization/services.js
src/ducks/tracking/__mocks__/index.js
src/ducks/tracking/index.js

We want to know the number of transactions that uses the local categorization model (eg how many have a `localCategoryProba` higher than the usage threshold (0.8 for now)). So everytime we apply the local model to some operations, we send an event to Matomo with the number of transaction that satisfy this condition.
To achieve this goal, I refactored the current tracking code. The idea is to have a `getTracker` function that returns the right tracker according to the target it gets passed. For services (NodeJS) we want to use a specific tracker. For others targets (web), we don't to anything for now but we will certainly want to use the tracker from cozy-ui. So for now I only added a `NodeTracker` that uses `matomo-tracker` under the hood.

Track local categorization model usage

---

src/ducks/categorization/services.js

We found a bug in the model this morning. Since we want to release as soon as possible, our best solution is to disable the model until François find how to fix the issue.
For information, the issue occurs when there are very few manually categorized transactions on the instance. In that case, the model applies wrong categories with a high probability to a lot of unrelated transactions.
We also have another bug: not only new transactions get the model applied to them.

feat: Disable local categorization model

---

src/ducks/mobile/utils.js

Currently we redirect the user to the login page as soon as he clicks on the "logout" button. But the process of destroying PouchDB databases can take several seconds. So it's safer to wait for the dbs to be destroyed before redirecting the user.

feat(mobile): Wait for client to be resetted before redirect on logout

---

src/ducks/onboarding/EnsureHasAccounts.jsx
src/ducks/onboarding/EnsureHasAccounts.spec.jsx

The auto-refresh of the onboarding when there is no data but some triggers may be running was broken.

fix: Autoreload data on onboarding

---

src/components/LogoutModal/LogoutModal.jsx
src/components/LogoutModal/LogoutModal.styl
src/components/LogoutModal/index.js
src/ducks/mobile/MobileRouter.jsx
src/index.ejs
src/locales/en.json
src/locales/fr.json

We now wait for cleanup to be done before redirecting to user to the login screen when he logs out. This can take several seconds, so we need to show him that something is happening. We choosed to show a modal with a spinner and a message indicating that the logout process is doing its job.

Show a modal during logout

---

config/webpack.config.dev.js

Watch mode was very slow because we didn't set webpack `mode` to `development`. Since the default is `production`, it was applying unnecessary optimizations.

chore: Use developement mode in dev

---

src/ducks/balance/Balance.styl

Some cleaning in preparation for a future [release of Cozy-UI](https://github.com/cozy/cozy-ui/pull/641) with color variables as CSS custom properties.
We can't have custom properties in Stylus functions, it just breaks.
Most of `alpha()` color actually need ligter colors, not transparency. I think that was the case and that should do it.
Correct me if I'm wrong.
| Before | After |
|--------|-------|
|![image](https://user-images.githubusercontent.com/1606068/48472089-bc7b4880-e7f5-11e8-96eb-84c5de6364bc.png)|![image](https://user-images.githubusercontent.com/1606068/48472111-ca30ce00-e7f5-11e8-8128-735c24b7cb60.png)|

fix: Don't use color var in stylus func

---

src/components/UserActionRequired/index.jsx
src/ducks/mobile/MobileRouter.jsx
src/ducks/transactions/actions/KonnectorAction.jsx

We forgot to add the `contextTypes` property on components using the context. React requires it.

fix: Add contextTypes on component using context

---

src/styles/main.styl

The original bug is because we use a custom value for the
overflow-y for the html tag. If scroll is used, the scrollbar
does push content, if auto is used, the scrollbar does not push
the content, and the content can be truncated by the scrollbar.

fix: Scrollbar not pushing content

---

src/ducks/categorization/services.js
src/ducks/categorization/services.spec.js
src/targets/services/onOperationOrBillCreate.js

The alpha model was previously fixed at `0.1`, but we saw that it doesn't handle all cases well. So François reworked it and came with some new expectations for this parameter:
* Never lesser than a minimum value (`0.1`)
* Never higher than a maximum value (`10`)
* Equals to `max smoothing parameter / number of unique categories` (where `max smoothing = 20`)
The initialization of the local model also needed a little rework:
* If the number of recategorized transactions is lower than a limit (`2`), give a higher weight to the recategorized transactions
* If the number of unique `manualCategoryId`s equals to `1`, add a fake transaction to the learn sample
Finally, we had a bug in which not only new transactions were passed in the categorization models.

Update local categorization model

---

config/webpack.config.dev.js
src/components/AugmentedModal.jsx
src/ducks/transactions/actions/BillAction.jsx

The augmented modal had some problems due to recent changes:
* We no longer expose cozy-client-js globally, so we had to pass the intent creation function to the `IntentIframe`
* Preact didn't propagate events through portals, but React does. It caused a bug in which we could not close the augmented modal

Fix augmented modal

---

src/ducks/transactions/Transactions.styl

Headers were not properly aligned on medium screen:
| Before | After |
|--------|-------|
|![image](https://user-images.githubusercontent.com/1606068/48846268-f96bb000-ed9e-11e8-85ad-5a1bc983b003.png)|![image](https://user-images.githubusercontent.com/1606068/48846228-dfca6880-ed9e-11e8-981e-879858878bea.png)|

fix(transactions): Align headers on medium screen

---

src/ducks/balance/HistoryChart.jsx

I'm pretty sure it worked before, but now the ref is undefined and I don't know why. Since we are working on this feature again, I think we can comment it for the moment so we are not blocked and see what's wrong later.

feat(HistoryChart): Disable automatic scroll

---

src/ducks/transactions/TransactionHeader.jsx
src/ducks/transactions/Transactions.styl

We just want to be consistent with the mobile style, which don't show this.

feat(TransactionHeader): Don't show columns headings on tablet

---

src/targets/services/onOperationOrBillCreate.js

The service was crashing if the `io.cozy.bills` database didn't exist. So I wrapped the data fetching of each part in the according `try..catch` block. This way, if a part of the service is failing due to a fetch error, it doesn't crash the whole service.

Enhance error management in service

---

package.json
yarn.lock

Following the [event-streamgate](https://github.com/dominictarr/event-stream/issues/116). It targeted crypto-currency stuff, so we're not "in danger", but still.

chore(deps): Update npm-run-all to v4.1.5

---

src/components/List/index.jsx
src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.spec.jsx
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/helpers.js
src/ducks/transactions/scroll/TopMost.js
src/ducks/transactions/scroll/TopMost.spec.js

The date selector was not updating because transactions rows refs were not passed to the TopMost instance : while scrolling, we could not figure out the highest visible row.

Fix date selector update when scrolling

---

src/ducks/notifications/html/templates/balance-lower.hbs
src/ducks/notifications/html/templates/health-bill-linked.hbs
src/ducks/notifications/html/templates/transaction-greater.hbs
src/locales/fr.json

- Transaction amounts are shown in the health bill linked email
- Separators between accounts is lighter and separators between banks have been added

Html notifs

---

src/ducks/categorization/services.js

We logged the number of all fetched transactions instead of only manually categorized ones.

fix(service): Log manually categorized transactions number

---

src/ducks/transactions/TransactionHeader.jsx
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/TransactionsPage.styl

We broke it when introducing the `Padded` component. We needed to wrap only a part of the header in `Padded` instead of the whole page, and to remove some custom negative margins, which is great.

fix(transactions): Infinite scroll

---

src/ducks/transactions/TransactionActions.jsx
src/ducks/transactions/TransactionActions.spec.jsx
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/actions/HealthExpenseStatusAction.jsx
src/ducks/transactions/actions/KonnectorAction.jsx

There was two flaws with this action:
* The `brands` property used in the `match` function was too ambiguous (which brands ? All brands ?). In this action we need to know brands without trigger. In other actions we need to know brands with trigger. So I refactored this to add a `hasTrigger` property to brands and pass all brands instead of only the ones without trigger. This way, the prop name is no ambiguous anymore
* The `userCanInstallHealthKonnector` function did what it was intended to do, but we actually didn't want that condition in this action. What we want to do is to always show the status if there are reimbursements, or if there is at least one health konnector with a trigger

Fix health expense status action

---

src/components/Header/Header.jsx
src/components/Header/Header.styl
src/components/SelectDates/SelectDates.styl
src/ducks/transactions/TransactionHeader.jsx
src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.styl
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/TransactionsPage.styl
src/ducks/transactions/header/TableHead.jsx
src/ducks/transactions/header/TableHead.styl
src/styles/main.styl

Changes :
- Add a flag (transaction-history) to display separately the graph current balance and transaction
- Add blue frame on transaction
- Add new design on table head
You can see design with and without `transaction-history` flag:
without | with
--------|-----

Transaction: Update design on table head

---

src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js

It led to an error when saving settings in the service. There was no error in the app because it uses the new cozy-client that handles it automatically.

fix(settings): Remove _type from default settings

---

package.json
yarn.lock

This release fixes a bug in browser/node detection that broke the flag system in browser. See https://github.com/cozy/cozy-libs/pull/181 for more details.

fix(deps): Update cozy-flags to v1.3.2

---

src/components/Chart/LineChart.jsx
src/ducks/balance/History.jsx

We showed only the last day's balance when there is no transaction:
This was because we didn't provide the whole `from` => `to` interval. So I just added the `to` date.
But it showed another problem: when there is only one value `n` in the dataset, the domain of the `y` axis is `[n, n]`, and d3 will draw the line like all values are the minimum:
So I handled it by setting the minimum value of the domain to `0` in that case:

Show the full graph when there is no transaction

---

src/ducks/brandDictionary/brands.json

@kossi, as resquested, would be great to put it quickly in prod
(we hope that will be a soft advertise to have our first accounts slowly)
But more than 0.

chore: Add eoviMCD in brand dictionnary

---

src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js
src/ducks/settings/services.js
src/targets/services/onOperationOrBillCreate.js

This PR addresses two things:
* Revert a commit that removed the `_type` property in default settings. We actually needed it in the app and the new cozy-client removes it automatically. Since the service uses the old cozy-client-js, we need to remove it by hand in the service
* There was a typo in the retrieval of the last seq in the `fetchChangesOrAll` function. We ended with undefined last seq persisted in DB

Service fixes

---

src/doctypes.js
src/doctypes.spec.js

We splitted the bill id in `HasManyReimbursements::get data` but not in `HasManyReimbursements::query`.

fix(HasManyReimbursements): Split bill id

---

test/fixtures/latestfixture_2018-12-11.json

Having a health transaction linked to a Free bill was a nonsense for demo.

chore(fixtures): Remove free bill on Docteur Martin transaction

---

src/targets/mobile/config.xml

<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …

Release 0.11.0

---

package.json
src/ducks/categories/CategoriesHeader.styl
src/targets/mobile/config.xml

<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …

Release 0.11.1

---

src/ducks/balance/Balance.jsx
src/ducks/settings/Configuration.jsx
src/ducks/settings/TogglePane.jsx
src/ducks/settings/TogglePane.styl
src/ducks/settings/ToggleRow.jsx
src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js
src/locales/en.json
src/locales/fr.json

The balance history on balance page is not behind a flag anymore. Instead, the user can enable it via a setting.
I refactored the components used in this page so we have more flexibility and can achieve what we wanted easily.

feat: Add a setting to show the balance history

---

src/ducks/balance/Balance.jsx

This spinner was too small, misaligned and visible a fraction of second causing a disturbing blink.

feat(Balance): Remove spinner while loading settings

---

src/ducks/categories/CategoriesChart.styl

The chart is hidden by the figure block

fix: Display tooltip on mobile

---

src/ducks/notifications/BalanceLower.js
src/ducks/notifications/HealthBillLinked.js
src/ducks/notifications/TransactionGreater.js
src/ducks/notifications/services.js
src/ducks/notifications/services.spec.js

We had a problem due to code minification on production mode. The classes names were mangled by the minification process, but since we relied on it to do the link between settings and classes, it was broken. The result was that even if the user had notifications enabled, we treated it as disabled.
After some research, I found that it broke between webpack 3 (no problem) and webpack 4. I looked at Terser options, but I felt it was better to just not rely on classes `name` property, so we don't rely on a tool configuration to make our code work. I mean if in the future we change the minifier, but forget to set the right configuration, this code will again. I think it's not safe at all.

fix: Notifications

---

src/ducks/notifications/BalanceLower.js
src/ducks/notifications/TransactionGreater.js

<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …

Release 0.11.4

---

package.json
yarn.lock

The `fixtures` scripts doesn't work if we don't have ACH installed on our system. I think it should always work, so I propose to add `cozy-ach` as a dev dependency.
If we don't want to add such a dependency, we can also update the script to use npx: `npx cozy-ach import ...`

chore(deps): Add ACH as a dev dependency

---

package.json
yarn.lock

v3.1.13 and 3.1.4 have a bug with host checking (see https://github.com/webpack/webpack-dev-server/issues/851#issuecomment-449518624). Potential solutions are:
* adding `disableHostCheck: true` in the config
* downgrade to v3.1.10
I went for downgrading since I think it's better than fixing a bug by changing the config.

Downgrade webpack-dev-server to v3.1.10

---

manifest.webapp
src/components/App.jsx
src/components/Info/__snapshots__/index.spec.js.snap
src/components/Info/index.js
src/components/Info/index.spec.js
src/components/Info/styles.styl
src/components/KonnectorUpdateInfo/index.js
src/components/KonnectorUpdateInfo/styles.styl
src/doctypes.js
src/locales/en.json
src/locales/fr.json

When a change in a connector requires the user to accept new TOS, we want to show an alert with a button that redirects the user to the list of connectors waiting for a manual update.
The `Info` component used is a copy/pasted and improved version of the cozy-ui one. I'm going to have a look with designers to see if we merge the update in cozy-ui or not.
Instance for validation : https://testbanksbiinfo-banks.cozy.works/#/balances
You should activate the flag: `flag('konnector-update-info', true)`. I installed a "Axa Banque" connector and updated it so the alert will be shown. But the whole feature may not whole correctly since the connector is not really waiting for a manual update.

Alert for konnectors waiting for manual update

---

config/webpack.config.base.js
config/webpack.vars.js
src/main.jsx

This adds the possibility to enable some flags at build time.
For example: `COZY_FLAGS=balance-history,transaction-history yarn build` will make a build with `balance-history` and `transaction-history` flags enabled by default.
This can be useful to generate mobile builds with enabled flags, so testing the feature is easier. Or to generate web builds with enabled flags and deploy them with `deploy2cozy`. Maybe this kind of feature can be integrated to CCA in the future (for example when we switch to cozy-scripts :p).
The only downside I don't know how to bypass is that since we use `localStorage` for web flags, when we enable the flag `f` for a build, then we do another build without enabling it, it will remain enabled on the instance.

chore: Flags at build time

---

src/ducks/balance/BalancePanels.jsx
src/ducks/groups/helpers.js
src/ducks/groups/helpers.spec.js
src/locales/en.json
src/locales/fr.json

There are new rules for virtual groups:
* We create a virtual group for every type of account that exist on the instance (previously it required at least two accounts with the same type)
* We handle accounts without any type and group them in an "undefined" group
WARNING: the base branch is `expansion-panel` since #713 is not merged for now. This is because this PR is based on the work in #713. I think we must merge #713 before this one.

feat(groups): Create virtual group for accounts alone and without type

---

src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.styl

Use a pseudo element with the same background color as the chart container so we think the group panel overflows on it.

feat(Balance): Panels overflows on chart area

---

src/ducks/balance/BalancePanels.jsx
src/ducks/balance/BalancePanels.styl
src/ducks/settings/AddAccountLink.jsx

Add the buttons to connect a new bank and go to groups settings on the new balance page design.
The buttons are very similar to cozy-ui's `ButtonAction`, but required some customizations. I will see with @joel-costa if that's changes that should be generic or not.
https://testbanksbalancebuttons-banks.cozy.works/

Add actions on balance page with panels

---

src/ducks/balance/BalancePanels.jsx
src/ducks/groups/helpers.js
src/ducks/groups/helpers.spec.js
src/locales/en.json
src/locales/fr.json

Groups were sorted on their translated label. So "other accounts" was not always the last group.

feat(BalancePanels): Sort groups with undefined last

---

src/components/ExpansionPanel/ExpansionPanelSummary.js
src/ducks/balance/Balance.styl
src/ducks/balance/BalancePanels.styl
src/ducks/balance/components/AccountsList.jsx
src/ducks/balance/components/AccountsList.styl

On desktop we show more informations. I used Grid layout since it's widely compatible and the `fr` unit is very useful here. I tested it via Browserstack to make sure the compatibility is good: it is.
You can see the changes live on https://testbanksgrouppanelsdesktop-banks.cozy.works/#/balances

Balance panels desktop layout

---

src/ducks/groups/helpers.js

If a group have a type that we don't have a translation for, we put it in the "other accounts" virtual group.

feat(groups): Put groups with not handled type label in 'other accounts'

---

src/ducks/balance/BalancePanels.jsx
src/ducks/balance/BalancePanels.styl

So Claudy does not cover actions
Before:
After:

feat(BalancePanels): Add padding on bottom

---

src/ducks/balance/Balance.jsx
src/ducks/balance/BalancePanels.jsx
src/ducks/balance/components/AccountRow.jsx
src/ducks/balance/components/AccountRow.styl
src/ducks/balance/components/AccountsList.jsx
src/ducks/balance/components/GroupPanel.jsx

Show the accounts with a balance under the configured limit in orange; and accounts with a negative balance in red.
See https://testbanksaccountrowcolor-banks.cozy.works

feat(GroupPanels): Show accounts state with colors

---

src/components/Info/__snapshots__/index.spec.js.snap
src/components/Info/index.js
src/components/Info/styles.styl

There was a problem on chrome. This was due to unneeded flex display.
Before:
After:

fix(Info): Layout problem on Chrome

---

src/ducks/balance/components/BalanceTable.styl

fix(BalanceTable): Account column was not 100% width on small screen

---

src/components/Chart/LineChart.jsx

I change just value of `y0` to start gradient on minimum

fix: Gradiant should start on min y

---

src/components/Switch.jsx
src/ducks/balance/Balance.jsx
src/ducks/balance/BalancePanels.jsx
src/ducks/balance/components/AccountRow.jsx
src/ducks/balance/components/AccountRow.styl
src/ducks/balance/components/AccountsList.jsx
src/ducks/balance/components/GroupPanel.jsx
src/ducks/balance/helpers.js
src/ducks/balance/helpers.spec.js

This adds the possibility to check/uncheck groups and accounts.
The rules are the following:
* When we uncheck a group, we want the accounts rows to be disabled, but their checked state remains the same (ie. unchecking a group doesn't uncheck the switches of all its accounts)
* We need to know the state of each account in each group. It means we can't flatten the object holding the state. This is because we still put an account balances in the balance history computation until it is unchecked in all the groups it's part of (this is not part of this PR because I wanted to cut the work to avoid monstrous PR)
I used an object with the following shape to hold the state:
```
{
[GROUP_ID]: {
checked: boolean,
accounts: {
[ACCOUNT_ID]: {
checked: boolean,
disabled: boolean
}
}
}
}
```
The reason …

Groups and accounts checked/disabled state management

---

src/components/Chart/LineChart.jsx
src/ducks/balance/Balance.jsx
src/ducks/balance/History.jsx
src/ducks/balance/HistoryChart.jsx
src/ducks/balance/helpers.js
src/ducks/balance/helpers.spec.js
src/locales/en.json
src/locales/fr.json

This adds the link between groups/accounts switch and the balance history chart on the balance page.
We look the switches state object to find which accounts are enabled, then we pass them to the chart and we compute the balance only on them.

Update chart when checking/unchecking groups/acounts

---

src/ducks/balance/Balance.jsx
src/ducks/balance/BalancePanels.jsx
src/ducks/balance/components/GroupPanel.jsx
src/ducks/balance/helpers.js
src/ducks/balance/helpers.spec.js

The panels state is now fetch from settings on the initialization, and saved to it when we change something (expand/collapse; switches...). This way the user has the same state on every device.

Save and get balance panels state with settings

---

src/ducks/categories/helpers.js
src/ducks/categories/helpers.spec.js

In `getCategoryId` helper we now do the following:
* If there's a manual categorization: use it
* Else if the local categorization is enabled and there's a local category with a probability higher than 0.8: use it
* Else if there's a cozy category with a probability higher than 0.8: use it
* Else use the automatic category

feat(categories): Enable global categorization model

---

package.json
yarn.lock

This fixes the `can't convert undefined to object` error on transactions page.

fix(deps): Update cozy-client to v5.7.2

---

src/ducks/balance/Balance.jsx
src/ducks/settings/Configuration.jsx
src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js

This removes the setting to enable/disable the history chart on current balance page. We now always show it.

Enable history chart on current balance page for everybody

---

src/ducks/categories/helpers.js
src/ducks/categories/helpers.spec.js

We use `0.9` because the model is not fully battle tested yet.

feat(categories): Increase the global model usage threshold to 0.9

---

src/components/Switch.jsx
src/ducks/balance/components/AccountRow.jsx
src/ducks/balance/components/AccountRow.styl
src/ducks/balance/components/GroupPanel.jsx
src/ducks/balance/components/GroupPanel.styl

* Restore switches clickable area to 48px wide (it increases the dimensions so to keep the design consistent I had to remove some paddings and margins)
* Fix the height of the panel summary content to `3.5rem` so there are no more area above and beyond it that expand/collapse the panel on click. The whole area redirects to the transactions page
https://testbanksfixespanels-banks.cozy.works/

Group panel clickable areas

---

src/ducks/settings/AccountSettings.jsx
src/ducks/settings/AccountsSettings.jsx

I forgot to update the accounts details pages when I updated accounts types translations.
https://testbanksfixaccountdetails-banks.cozy.works

Fix account type translations in account details

---

src/ducks/balance/History.jsx
src/ducks/balance/helpers.js
src/ducks/balance/helpers.spec.js
src/ducks/filters/index.js
src/ducks/filters/index.spec.js
src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/TransactionsPage.spec.jsx
src/ducks/transactions/helpers.js
src/locales/en.json
src/locales/fr.json

- Use .date || .realisationDate in filters
- Use .date for history
- Added tests
- Show debitDate as tooltip if different from realisationDate

Fix filters realisation date

---

src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.spec.jsx
src/ducks/transactions/TransactionsPage.jsx

We were not showing the transactions correctly because we were slicing on unordered data. Now we sort the transactions by date, then we slice it, then we do the grouping.

Fix transactions sorting

---

package.json
scripts/publish.js

- Prevent overwriting a file on downcloud
- Do not use babel-node as it is detrimental to perf and
quite unnecessary since node has async now

feat: Improvements to publishing process

---

src/ducks/balance/History.jsx

The balance history was crashing if some transaction was `null`. This fixes it.

fix(History): Check that transaction exists

---

src/ducks/transactions/TransactionSelectDates.jsx
src/ducks/transactions/TransactionSelectDates.spec.jsx
src/ducks/transactions/TransactionsPage.spec.jsx
src/ducks/transactions/helpers.js
src/ducks/transactions/helpers.spec.js
test/fixtures/demo.json

Check if the account linked to a transaction if of type `CreditCard` or not to return the date of a transaction.

feat(transactions): Use realisationDate if the account is CreditCard

---

src/ducks/balance/HistoryChart.jsx

Le mois ne s'affichait pas correctement il était en anglais.

feat: Use format date from cozy-ui

---

src/components/KonnectorUpdateInfo/index.js

Allow to display only banking konnectors when redirecting to the Store

Add banking category to update redirection

---

src/components/SelectDates/SelectDates.styl

Before:
After:
Primary color version is OK too:

fix(SelectDates): Disabled arrow color

---

src/ducks/balance/components/AccountRow.styl
src/ducks/balance/components/GroupPanel.jsx
src/ducks/balance/components/GroupPanel.styl

* The panel summary and arrow should be grey when not checked
* The bank logo should be opacified when the line is not checked
https://testbankspaneldisabled-banks.cozy.works

Fixes on balance panels disabled state

---

src/ducks/client/index.js
src/ducks/client/mobile.js
src/main.jsx

Lorsque l'on mettait à jour le token de la __cozy-bar__ on lui passait l'intégralité des informations alors que la bar s'attend juste à recevoir l'`accessToken`.
Nous sauvegardons dans le store le nouveau token.

Update refresh token

---

docs/account-types.md
src/ducks/account/helpers.js
src/ducks/account/helpers.spec.js
src/ducks/settings/AccountSettings.jsx
src/ducks/settings/AccountsSettings.jsx
src/locales/en.json
src/locales/fr.json

The goal of this PR is to group more account types than before. This way we don't have too much virtual groups that contain only one account type, and the types are more understandable than before.
I added some documentation so we don't lose the original types list.
https://testbanksmergeaccounttypes-banks.cozy.works/#/balances

Rationalize account panels

---

src/utils/flag.js

This enable the flag. So for now we still have the old code, but it is silent. We will remove it after the new UI proved it works well for a while on production.

feat: Turn on balance panels UI by default

---

src/ducks/categorization/services.js
src/ducks/categorization/services.spec.js

This is the first part of a too large closed PR https://github.com/cozy/cozy-banks/pull/881
Added another safeguard to avoid a too high strenght of amounts tags in categorization. After having learnt the local model's parameter, we cast to log the sub-parameters associated to amounts.

fix: Second safeguard for local categ by reweighting amounts tokens

---

src/ducks/categories/Categories.jsx
src/ducks/categories/CategoriesHeader.jsx
src/utils/flag.js

* Split `transaction-history` flag into `categories-header-primary` so it's easier to enable or disable each one separately (and because there is no history chart on categories page)
* Enable `transaction-history` and `categories-header-primary` by default

Enable movements chart

---

src/ducks/mobile/utils.js

The problem was that after logout on the mobile app, we couldn't scroll anymore. This was caused by the fact that when we open the cozy-bar, it sets an `overflow: hidden` (and other stuff to prevent scroll) on the `body`. But on logout, we simply destroy the cozy-bar DOM node. So we still had the `overflow: hidden` on the `body`. Now I just erase all styles applied on `body` on logout, but we may think of a better API like `destroy` or `unmount` directly in the cozy-bar to handle this correctly.

fix(mobile): Scroll after logout

---

src/ducks/balance/components/AccountRow.jsx
src/ducks/balance/components/KonnectorIcon.jsx
src/ducks/balance/components/utils.js
src/ducks/balance/components/utils.spec.js
src/ducks/transactions/TransactionsPage.jsx

AppIcon does not work directly on mobile. To make it work, you need
to provide a special fetchIcon function that returns the URL of the
icon. This cannot be used for konnectors since konnectors do not have
the `links.icon` attribute (when fetching from `/konnectors/slug`).
This is why I implemented a custom way, by fetching directly the SVG
data and setting it in the HTML directly. One improvement IMHO over the
way AppIcon was used is that now we use `withClient` to get the cozyURL,
it is easier for the developer. I think AppIcon could work like that (check
if client exists in the context).
The SVG data is memoized per domain for 30s.

feat: Fix mobile konnector icons

---

src/assets/icons/icon-broken.svg
src/components/App.jsx
src/components/ErrorBoundary.jsx
src/components/ErrorBoundary.styl
src/locales/en.json
src/locales/fr.json

Lorsqu'il y a une erreur sur une page on a ce design :
Voir [la documentation React](https://reactjs.org/docs/error-boundaries.html)

feat: Add error boundary

---

src/ducks/mobile/index.js
src/main.jsx

This is a temporary solution to prevent the bar from having an expired
token. See https://github.com/cozy/cozy-bar/issues/449 for more
informations.

feat(mobile): Ensure the token is refreshed before it expires

---

src/ducks/mobile/MobileRouter.jsx

The filters were not resetted on logout. So if we logged in on an instance, selected a bank account, then logout and login on another instance and go to the transactions page, we had the previously selected account name on the header.

feat(mobile): Reset filters on logout

---

src/ducks/transactions/TransactionsPage.jsx

Show the « load more » button on Android, like we do on iOS.

feat(mobile): Use manual load more on android

---

src/ducks/brandDictionary/brands.json

Adding a brand for an important connector.
No \\b at the end because know identifiers is 'LA MUTUELLE GEN' but we probably want to match something like 'LA MUTUELLE GENERALE' too if it happens.

feat: Add lamutuellegeneral to brand dictionnary

---

package.json
src/components/AppRoute.jsx
src/ducks/mobile/index.js
src/ducks/settings/AppVersion.jsx
src/ducks/settings/Debug.jsx
src/ducks/settings/Settings.jsx
src/ducks/settings/index.js
src/locales/en.json
src/locales/fr.json
src/main.jsx
src/utils/token.js
src/utils/token.spec.js

- Add a debug panel in settings if flag('debug') is set
- Add a button to expire the token in the redux store
- When refreshing the token, an alert is shown if the flag('debug') is set

Debug panel to expire token manually

---

src/components/ErrorBoundary/Error.jsx

The inline onclick handler was failing with real stack CSPs.

fix(Error): Refresh link doesn't fail with CSP

---

src/ducks/settings/Debug.jsx
src/main.jsx

The `Alerter.show` function doesn't seem to exist. I also added the token refresh on app start, because it was only on resume.

Fix debug alert and refresh token on mobile app start

---

src/components/Chart/LineChart.jsx
src/components/SelectDates/SelectDates.jsx
src/ducks/balance/HistoryChart.jsx
src/ducks/transactions/TransactionHeader.jsx
src/ducks/transactions/TransactionSelectDates.jsx
src/ducks/transactions/TransactionsPage.styl

In this case, screenshots are better than words:
Live on https://testbanksmovementsgradient-banks.cozy.works

Select date overlaps history chart on movements page

---

src/components/Chart/LineChart.jsx

We put a transparent point with a diameter of 48px so that the touchable
area is 48px wide instead of the small area of the visible circle

feat(LineChart): Increase the touchable area of the point

---

src/ducks/transactions/helpers.js

Sometimes BI does not return labels that are clean. Clean
labels via RegExps. Behind flag `clean-labels`.

feat: Clean transaction labels

---

package.json
test/fixtures/README.md
test/fixtures/demo.json
test/fixtures/helpers/freshDate.js
test/fixtures/helpers/freshDate.spec.js
test/fixtures/helpers/index.js

This helper's role is to take dates in the past and refresh them. For now it works only for the `demo.json` transactions fixtures, and it works like this:
* Take the latest transaction date
* Get the difference in days between this date and today
* Apply this difference to all transactions
This way, if the latest transaction date is 2019-02-01 and we are currently 2019-02-25, the difference is 24 days. 2019-02-01 becomes 2019-02-25 and 24 days are added to all other transaction dates.

Add freshDate helper in fixtures

---

src/ducks/account/helpers.js
src/ducks/balance/components/AccountRow.jsx

The title says it all. You can test it on https://testbanksdemoaccountupdatedat-banks.cozy.works by activating the `demo` flag: `flag('demo', true)`

Always show "today" as account last update date when demo flag is enabled

---

src/components/List/index.jsx
src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/Transactions.styl

By enabling this flag, the id of each transaction is shown. This is
useful for debug purposes.
Particularly, since demo fixtures transactions dates are now dynamic, it can be hard to mentally do the link between a transaction shown in the app and a transaction in the JSON file. With this, we can link them using the ID, which is more straightforward.

feat(TransactionRow): Add show-transactions-ids flag

---

src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.js
src/ducks/brandDictionary/brands.json
src/index.ejs
src/targets/mobile/config.xml
test/fixtures/demo.json

<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …

Release 0.13.0

---

src/components/Chart/LineChart.jsx

When changing the code not to bring the whole d3 but only some methods, I had an error transition() is not a function. I made a mistake when fixing it, I thought I needed to wrap the d3-selection into a transition. This was unnecessary since merely importing d3-transition adds the `transition` method to `d3-selection`s. `d3-transition` is imported in `utils/d3`.

fix: Bad transition fix when reducing d3 size

---

src/ducks/mobile/MobileRouter.jsx

I forgot this in 6f4d9bc69deca154cb71ec3c6db2578ceaf1deb0 and it's
breaking the mobile app.

fix(MobileRouter): Default route is always /balances

---

src/ducks/filters/index.js
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/TransactionsPage.spec.jsx

When changing the filtering doc while on a specific month, we didn't
update `limitMin` and `limitMax`. But it could be wrong since the number
of transactions changed. Now, on update we trigger `handleChangeMonth`,
which recomputes the limits and the current month.
https://testbanksfixtransactions-banks.cozy.works
Do the following to test:
* Go to an account details
* Select "all accounts"
* Go back one month
* Select "awaiting reimbursements"
* You see the transactions (before the fix, you couldn't see it)

fix(TransactionsPage): Update current month when changing filtering doc

---

config/webpack.config.styles.js
src/styles/main.styl
src/styles/mixins.styl
src/styles/utilities.styl

With the stylus resolver and `./something.styl` we were not able to customize stylus files that are not imported in JS files easily.
For example, since `src/styles/palette.styl` was imported with `@require './palette.styl'`, even if we created an override for this file in a customization repository, it would never be used because stylus-loader resolved the file by its path.
To fix this, I did two things:
* Use the webpack resolver in stylus-loader using [the preferPathResolver option](https://github.com/shama/stylus-loader#prefer-webpack-resolving)
* Use relative imports without `./` when we `@require` stylus files
Now since stylus `@require` uses the webpack resolver and we use the good paths style, we can create overrides files in the customizations repositories for these files.

Use webpack resolver and relative requires in stylus files

---

src/ducks/balance/HistoryChart.jsx

We couldn't use a gradient from a transparent white to full transparent because of iOS. So we hardcoded the colors. Now we derivate the colors from the CSS variable of the theme.

feat(HistoryChart): Use CSS variable for gradient

---

package.json
src/ducks/bar/overrides.js
src/ducks/mobile/utils.js
yarn.lock

For customization needs, we need to be able to pass overrides to
`cozy.bar.setTheme`. Do be able to override it easily, I added a map in
its own file. This way, we can override this single file in every
customization. In the original Banks we don't want any overrides, so it
is an empty object.
See cozy/cozy-bar#473 for the implementation of
the overrides in the cozy-bar side.

feat(bar): Handle bar theme overrides

---

src/components/Chart/Tooltip.styl
src/components/Header/Header.styl
src/ducks/balance/Balance.styl
src/ducks/balance/History.styl
src/ducks/balance/HistoryChart.jsx
src/styles/main.styl
src/styles/mixins.styl
src/styles/palette.styl
src/styles/utilities.styl

By introducing CSS variables for each part of the header, this is much easier to apply another theme to it by creating an override of the `src/styles/palette.styl` file.

Use CSS variables for header

---

.lintstagedrc
package.json
yarn.lock

Not yet added as a husky hook
Linting of partially staged files seem to work well.
Since lint-staged is still quite slow, I am unconfortable
to add it as a husky hook yet and would prefer to have it
optional (see if it works well for us).

chore: Add lint-staged

---

package.json
yarn.lock

It is not a direct dependency anymore. But it is still imported by
cozy-client

fix(deps): Remove cozy-stack-client from dependencies

---

src/ducks/balance/components/GroupPanel.jsx

It makes it easier to override it in customization. For example, if we
want to override the default props so `square` is true by default.

refactor(GroupPanel): Import ExpansionPanel from cozy-ui

---

src/ducks/transactions/actions/KonnectorAction.jsx

I missed this one in https://github.com/cozy/cozy-banks/pull/991

refactor(KonnectorAction): Split cozy-ui imports

---

src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js

The local categoriation model is now enabled by default. The setting is still present so the user can disable it if (s)he wants.
This is a WIP because we are waiting for a potential action on the model from @francoisWeber.

feat(settings): Enable local categorization model override by default

---

src/ducks/categories/helpers.js
src/ducks/categorization/services.js
src/ducks/settings/Configuration.jsx
src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js
src/locales/en.json
src/locales/fr.json
src/targets/services/onOperationOrBillCreate.js

* Set the usage threshold to 0.25
* Remove the setting to allow users to send their manually categorized transactions to feed the model
* Fix a bug due to a bad condition in the categorization service
See https://testbanksglobalmodelupdate-banks.cozy.works

Updates on global categorization model

---

src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx

Debounce has been introduced not to re-render the whole
BalancePage when toggling expansion panels.
https://testbanksdebouncedpanels-banks.cozy.works

fix: Better perf for toggling expansion panels

---

config/webpack.config.base.js
src/utils/empty-mime-db.js

moment is normally used by chart.js but we do not need it.
mime-db is normally used by cozy-stack-client::FileCollection but we do not need it.

feat: Remove modules that we do not need

---

src/ducks/categories/icons.js

`require.context` does not exist in runtime so icons where not displayed. `require.context` was used to detect if we were in tests, so NODE_ENV==test can be used also.

fix: Use NODE_ENV==test to deactivate icons in jest

---

config/webpack.config.piwik.js
config/webpack.target.services.js

We had the Matomo config in 2 places, and in one of them the site ID was
a fake one, causing errors in logs.

fix: Matomo config

---

package.json
src/ducks/balance/HistoryChart.jsx
yarn.lock

Some of our targetted browsers don't support Element.scrollTo, but we
need it.

fix(HistoryChart): Add Element.scrollTo polyfill

---

src/ducks/mobile/statusBar.js
src/styles/palette.styl

So it's not always `primaryColorDark` in customizations.

refactor(mobile): Use an intermediary variable for status bar color

---

src/ducks/categorization/services-fixtures.spec.js

Added a column in the resulting `.csv` allowing to identify to which cozy instance belongs an operation/categorization.

test: Added a column identifying the cozy concerned by the fixtures

---

package.json
src/components/SelectDates/SelectDates.styl
src/styles/palette.styl
yarn.lock

The disabled version of the select dates buttons were semi-transparent. This was a problem as we could see the chart balance line behind. It is solved by using non transparent colors.

Color select dates

---

src/ducks/categories/helpers.js
src/ducks/categories/helpers.spec.js

When building the aggregate of transactions by category, we did not
put categories' `id`, so it was not working with `CategoryIcon`.

fix: Show category icons on CategoriesPage

---

src/ducks/brandDictionary/brands.json

Please merge it and publish in next release.
Connector will be out today or tomorrow

feat: Add tagandpass (Tag&Pass) brand in dictionnary

---

config/webpack.target.services.js

Following #1009, the __PIWIK_SITEID__ variable was not injected in
services build anymore.

chore: Fix services config

---

package.json
yarn.lock

babl-node was implicitly removed by
https://github.com/cozy/cozy-banks/pull/478. Since the uploadStaticFiles
script needs it, I needed to re-add it.

chore: Fix static files upload

---

scripts/release-pr-template.txt

The apps are automatically updated when they are used, so we don't force
the update via rundeck on all instances anymore when releasing a new
version of the app.

chore: Remove rundeck step in PR template

---

package.json
src/components/ErrorBoundary/Error.jsx
src/ducks/balance/Balance.jsx
src/ducks/categories/CategoriesPage.jsx
src/ducks/mobile/BarTheme.jsx
src/ducks/mobile/BarTheme.spec.jsx
src/ducks/mobile/MobileRouter.jsx
src/ducks/pin/FingerprintButton.jsx
src/ducks/pin/PinGuard.jsx
src/ducks/settings/Settings.jsx
src/ducks/transactions/TransactionsPage.jsx
yarn.lock

Pin needs to set bar theme in blue but the theme must go
back to its previous value when Pin is unmounted.
`react-side-effect` allows to build components that generate
a side effect (here changing the color of the bar), and you
can process all the props of side-effects components before
executing your side effect. In our case, processing means
only taking the last, so the innermost/latest React component will
set the bar color. When unmounted, automatically, the color
is set back to the previous color (or default).

feat: Set bar theme for Pin

---

src/ducks/brandDictionary/index.js
src/ducks/brandDictionary/index.spec.js
src/ducks/transactions/TransactionActions.spec.jsx
src/ducks/transactions/__snapshots__/TransactionActions.spec.jsx.snap
src/ducks/transactions/actions/KonnectorAction.jsx
test/fixtures/unit-tests.json

The KonnectorAction (« My invoices » CTA) now checks if the brand is in maintenance mode or not. This state can be specified in the brand dictionnary by adding the `maintenance: true` property to a brand.

Add maintenance property in brand dictionnary and KonnectorAction

---

src/ducks/balance/components/AccountRowLoading.jsx
src/ducks/balance/components/AccountRowLoading.styl

Spinner is old component, we should always use Icon ;)

refactor: Use Icon instead of Spinner

---

config/webpack.config.dev.js

Not depending on the full path makes it more flexible and compatible
with customizations.

chore: Update webpack config for cozy-bar in dev mode

---

src/components/App.jsx
src/components/ErrorBoundary/Error.jsx
src/ducks/pin/PinAuth.jsx
src/ducks/pin/PinEditView.jsx
src/ducks/pin/PinGuard.jsx
src/ducks/pin/PinKeyboard.jsx
src/ducks/pin/PinWrapper.jsx
src/ducks/pin/index.browser.jsx
src/ducks/pin/queries.js
src/ducks/pin/styles.styl
src/ducks/settings/Configuration.jsx
src/ducks/settings/PinSettings.jsx
src/locales/en.json
src/locales/fr.json

- Add Pin configuration in Settings
- Pin functionality is now basicly functional
Caveats
- Alert for bad pin is behind the Pin screen, need to fix this
- When no pin is configured, you cannot re-enter the app if the pin screen is displayed. As a workaround, you can set a pin-duration for 100s, configure the pin, and then set a lower duration
Visible on https://testbankspinsettings-banks.cozy.works/#/balances
```
flag('pin', true)
flag('pin-timeout', true) // show how much time left
flag('pin-duration', 100) // set the number of seconds before the pin is shown after the last click 
// configure the pin code via settings page
flag('pin-duration', 10) // 5/10 seconds seems reasonable when testing
```

Pin settings

---

.travis.yml

The yarn cache seems to be very big. Disabling it makes the cache goes
from ~1GB to ~200MB. The Travis doc warns about big cache archives:
"If you store archives larger than a few hundred megabytes in the cache,
it is unlikely that you’ll see a big speed improvement." (https://docs.travis-ci.com/user/caching/#how-does-caching-work)
I think the time to download/unpack this cache was longer than
installing dependencies without it, since the build time went from ~12mn
with it to ~8mn without it.
Before: https://www.travis-ci.org/cozy/cozy-banks/builds/509975813
After: https://www.travis-ci.org/cozy/cozy-banks/builds/509994019 / https://www.travis-ci.org/cozy/cozy-banks/builds/510004629

Travis build perf

---

docs/override-cordova-config.md
package.json
src/targets/mobile/config.xml
src/targets/mobile/scripts/beforePrepare.js
yarn.lock

This allows to specify the path to a XSL file in an environment variable. This XSL is applied to `config.xml` in a `before_prepare` hook, so the built app uses the transformed configuration.
« XSL » can be scary to read, as it sounds like an old technology, but it's made for what we want to do : transform XML documents. Otherwise we would have to use a lot of regex and placeholders. Here, we use something that is verbose, but is standard and exists for what we want to achieve.

Allow config.xml transformations at build time

---

package.json
src/targets/mobile/scripts/beforePrepare.js

The whole banks dependencies install should not fail if libxslt install
fails, since it's used only in special cases (when we want to override
the config.xml before building the mobile app)

chore: Put libxslt in optional dependencies

---

package.json
src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx
yarn.lock

Nous utilisons actuellement la lib cozy-realtime directement dans le dépot. Lorsque la nouvelle API sera sorti on pourra utiliser cozy-realtime directement depuis npm.
Relevant PR for realtime new API : https://github.com/cozy/cozy-libs/pull/355

feat(Balance): Fetch triggers or accounts when is necessary

---

src/targets/mobile/config.xml

- Upgrade android since there is a big issue with maven / jcenter recently (see this issue https://issues.apache.org/jira/browse/CB-14127). We can't build the native part of banks on android without this fix (from scratch, you don't see the problem if you have already built once). 
- Upgraded ios, but nothing special to say about it (https://cordova.apache.org/announcements/2018/07/26/cordova-ios-4.5.5.html)

fix(Cordova): Upgrade ios and android engine

---

src/ducks/pin/PinGuard.jsx

We have to clear timeouts when a component is unmounted.

fix: Clear timeout in PinGuard

---

config/webpack.config.cozy-ui.js
src/components/AccountSharingStatus/AccountSharingStatus.styl
src/components/List/List.styl
src/components/PopupSelect/styles.styl
src/components/Select/styles.styl
src/components/SelectDates/SelectDates.styl
src/components/SharingIcon/SharingIcon.styl
src/ducks/balance/components/BalanceRow.styl
src/ducks/settings/AccountsSettings.styl
src/ducks/settings/GroupsSettings.styl
src/styles/palette.styl
src/styles/utilities.styl

Palette.styl emits code so we should not import it.
There are still duplicates in the code, it has not removed
all declarations of CSS color variables.

refactor: Do not auto import palette

---

config/webpack.target.services.js

Since webpack config have become functions (to support
--env), we need to call this functions before merging
them in the config for services.

fix: Webpack config for services

---

src/components/KonnectorUpdateInfo/index.js
src/ducks/balance/Balance.jsx
src/ducks/mobile/MobileRouter.jsx
src/ducks/mobile/utils.js
src/locales/fr.json

When realtime is not correctly configured on the cozy-bar, we should not explode.
- Extracted start/stop of realtime into one method and added try/catch
- The token was not the right one, I think we have two ways of accessing the token with cozyClient, sometimes it is in cozyClient.stackClient.token and sometimes (I think with the OAuthClient, it is in cozyClient.stackClient.token.accessToken)
Removed warnings
- stackClient is accessible with client.stackClient, not with client.client anymore. For clarity
- if setState is called after an await, it can be called when the component is unmounted, and it triggers a warning

fix: Onboarding

---

src/doctypes.js

The goal of this PR is to avoid conflicts with other schema named `accounts`.

Rename accounts schema

---

src/ducks/brandDictionary/brands.json

Connector will be publish now.
Merge and publish this new brand when it's possible.

feat: Add CAF connector in brands dictionnary

---

docs/dev.md

It is necessary to have cordova installed globally for
fastlane cordova plugin to work correctly.

feat: Mention global cordova in doc to build mobile apps

---

src/ducks/transactions/actions/AppLinkAction.jsx

We wrongly showed an action to redirect the user to his Home when we
found "home" in the transaction label

fix(AppLinkAction): Filter cozy home

---

src/components/Chart/LineChart.jsx

The point line color was hardcoded `white`

feat(LineChart): Use lineColor prop for point line color

---

src/ducks/balance/components/HeaderTitle.jsx
src/ducks/balance/components/HeaderTitle.styl

Add the possibility to give it a className and make it manage its own text alignment. The subtitle is well aligned on the balances page because the parent have a `text-align: center`, but if we reuse it elsewhere, it was not well aligned.

Make balance's HeaderTitle reusable

---

src/components/Figure/Figure.styl

The stylus variables doesn't exist anymore. So their names was read as a
value by the browser.

fix(Figure): Use CSS variables

---

src/components/withFilters.jsx
src/ducks/settings/AccountSettings.jsx

When we delete an account, we want to reset filtering doc if it's the account being deleted.

Reset doc filter if it's the account being deleted

---

src/ducks/settings/AddAccountLink.jsx

The enrollment flow is better if we open the user's web browser instead
of an inapp browser: the user is already logged in in his browser.

feat(AddAccountLink): Open a web browser on mobile

---

src/ducks/settings/AccountsSettings.jsx

We want the label to be « Add a bank » / « Ajouter une banque » instead of « Add an account » / « Ajouter un compte »

feat(AccountsSettings): Update add account link label

---

src/ducks/transactions/TransactionActions.jsx
src/ducks/transactions/TransactionActionsContext.jsx
src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/TransactionsPage.jsx

With this, it's easier to override what's needed by the actions to match
and render because we only have to override the context to add things (konnectors, whatever...)

feat(TransactionActions): Get apps urls and brands from context

---

src/ducks/balance/Balance.jsx

When we did not have settings we did not save the state of the panels

fix(Panel): Save always settings configuration

---

src/ducks/transactions/TransactionActionsContext.jsx
src/ducks/transactions/TransactionActionsProvider.jsx
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/actions/KonnectorAction/helpers.js
src/ducks/transactions/actions/KonnectorAction/match.js

The goal of this PR is to be able to override the actions context and matching functions with the less effort as possible.
* Pass all props except children to the context value
* Split `TransactionActionsProvider` from `TransactionActionsContext` to make it overridable without touching `TransactionActionsContext` which is now more generic
* Extract helpers to make `KonnectorAction/match` more generic

Refactor actions context

---

src/main.jsx
src/targets/mobile/config.xml

-  [x] Tested on iOS (& entitlements created)

feat: Support universal link

---

package.json
src/ducks/account/helpers.js
yarn.lock

Use `BankAccount.getUpdatedAt` from cozy-doctypes to get the best update
date possible. See cozy/cozy-libs#423 for more
infos.

feat(account): Show the good account update date

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json

This PR add the new ensap connector in brand dictionnary.
Tests snaphots has been updated.
Connector is already published, merge it as soon as you can.
Thank's

feat: Add Ensap to brand dictionnary

---

package.json
yarn.lock

This cozy-flags version fixes a bug in Node environment. See
https://github.com/cozy/cozy-libs/blob/master/packages/cozy-flags/CHANGELOG.md#161-2019-05-03
for more informations. In banks, it fixes the service, which crashed
due to this bug.

fix(deps): Update cozy-flags to v1.6.1

---

src/ducks/categories/helpers.js

We are confident that even with a `0.15` probability, the results of our
global model are relevant.

feat: Set global model usage threshold to 15%

---

src/ducks/balance/components/NoAccount.styl

NoAccountButton class overrides styles from the Button. Since the order
of CSS between Button and NoAccountButton is not guaranteed, we have
to increase the priority of the selector.
This fixes a margin bug, the button being aligned to the left and not
centrally, on mobile.

fix: Increase priority of CSS selector since we are overriding a Button

---

package.json
yarn.lock

Not to have the flash.
Lots of lines removed from yarn.lock since some dependencies in cozy-authentication were in fact devDeps, and were moved.

feat: Update cozy-authentication

---

docs/dev.md

I had put the docs to the bottom of the template without seeing that there was already a section linking to a dead doc. Fixed :)

docs: Move email docs to the right place

---

src/targets/mobile/config.xml

For Android we need to specify the schema on the `host` attribute in order to works

feat: Universal Links https support Android

---

src/ducks/notifications/html/templates/cozy-layout.hbs

Put the support URL in a block, so we can easily override it.

feat(notifications): Make support link customizable

---

src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx

It seems that on some Android device, the realtime does not work correctly. As a fallback, a simple setInterval loop is used to fetch data periodically.

feat: Realtime fallback

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json

Add the flag maintenance: true in brand dictionnary for darty.
Can be merge as soon as you are ok with the commit.
Thank's

chore: Add Darty maintenance in brandDict

---

src/components/PopupSelect/index.jsx
src/ducks/account/helpers.spec.js
src/ducks/categories/CategoryIcon.jsx
src/ducks/categories/PendingCategoryIcon.jsx
src/ducks/categories/PendingCategoryIcon.styl
src/ducks/categories/categoriesMap.js
src/ducks/categories/helpers.js
src/ducks/categories/helpers.spec.js
src/locales/en.json
src/locales/fr.json
test/fixtures/unit-tests.json

We now have a special status for the transactions: « categorization in progress ». This is shown as a « special » category in the UI, with an animated icon.
The user can still manually categorize these transactions, but this special category is obviously not selectable in the categorization choices.
I also fixed a long lasting bug: the « other » subcategory was always selected alongside the real selected subcategory. This is no longer the case.

UI for transactions waiting for their categorization

---

src/ducks/appSuggestions/AppSuggestion.js
src/ducks/appSuggestions/__snapshots__/services.spec.js.snap
src/ducks/appSuggestions/services.js
src/ducks/appSuggestions/services.spec.js

The apps suggestions were crashing when there was a certain amount of transactions to analyze. There was two problems:
* A request to the DB was made for each transaction to find a potential corresponding app suggestion : now we fetch all existing suggestions in a single request
* The number of transactions listed in the relationships of a `io.cozy.apps.suggestions` document was not constrained, so it could grow very quickly. Writing big documents was  causing errors. We now save only the last 10 linked transactions

Refactor apps suggestions

---

config/webpack.target.services.js
docs/services.md
manifest.webapp
package.json
src/components/PopupSelect/index.jsx
src/ducks/account/helpers.spec.js
src/ducks/categories/CategoryIcon.jsx
src/ducks/categories/PendingCategoryIcon.jsx
src/ducks/categories/PendingCategoryIcon.styl
src/ducks/categories/categoriesMap.js
src/ducks/categories/helpers.js
src/ducks/categories/helpers.spec.js
src/ducks/categorization/services.js
src/ducks/notifications/TransactionGreater.js
src/ducks/notifications/html/data/health-bill-linked.json
src/ducks/notifications/html/data/transactions-greater.json
src/ducks/transactions/helpers.js
src/locales/en.json
src/locales/fr.json
src/targets/services/categorization.js
src/targets/services/onOperationOrBillCreate.js
test/fixtures/unit-tests.json
yarn.lock

This PR introduces the categorization service. This service is able to categorize new transactions.
To avoid race conditions between this service and `onOperationOrBillCreate` service that needs the result of the categorization to do its job, `onOperationOrBillCreate` is not triggered by the `io.cozy.bank.operations:CREATED` event anymore, but it's called programmatically by the categorization service when it has finished its work.

Categorization service

---

src/ducks/transactions/actions/HealthExpenseStatusAction.jsx
src/ducks/transactions/helpers.js
src/ducks/transactions/helpers.spec.js

For health expenses, we want the reimbursement status to be controlled by the reimbursements we matched for a given transaction.
Here is the rule :
* If the user manually placed a reimbursement status, just show it
* If the user didn't manually placed a reimbursement status, check the reimbursements
* If the transaction is fully reimbursed, then show "reimbursed"
* If the transaction is not fully reimbursed, then show "pending"
This way, if we matched some reimbursements, we can show a status reflecting this, but the user can still manually override the status we infered.
By doing this on the client side, we avoid too many refactors and data duplication between the `reimbursementStatus` and the `reimbursements` array.

Automatic reimbursement status on health expenses

---

src/ducks/balance/components/AccountsList.jsx

When importing accounts, the key is based on the slug of the konnector
of the trigger. Since there can be two (or more) triggers on the same
slug, I added the index to the key.

fix: Add index to key otherwise account row can have same key

---

src/ducks/balance/components/KonnectorIcon.jsx

KonnectorIcon can use the app prop to get the slug. This way it behaves
more like an AppIcon and becomes interchangeable.

fix: Ability for KonnectorIcon to be like AppIcon

---

package.json

The style.css required in the emails passed into identity-obj-proxy instead of being served raw.

fix: Emails tests

---

src/ducks/transactions/TransactionActions.jsx
src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/actions/AppLinkAction.jsx
src/ducks/transactions/actions/HealthLinkAction.jsx
src/ducks/transactions/actions/KonnectorAction/index.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/index.js
src/ducks/transactions/actions/UrlLinkAction.jsx

Render a `Chip` instead of a `ButtonAction` for every CTA in the transaction row. This is behind the `reimbursement-tag` flag.

Use Chip for all CTAs on transaction row

---

src/components/AugmentedModal.jsx
src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx
test/fixtures/demo.json

Add an `AugmentedModalOpener` component that acts like a `FileOpener`, but open an `AugmentedModal` for demo purposes.

feat(BillChip): Show an AugmentedModal for vente privée if demo flag

---

package.json
src/ducks/transactions/TransactionActions.jsx
src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/Transactions.styl
src/ducks/transactions/actions/AttachedDocsAction/FileIcon.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/index.js
yarn.lock

Some things that I missed while implementing new actions styles:
* Use `file-outline` icon
* Use `normal` Chip theme when a reimbursement is in pending state
* Properly align transaction row content on mobile

Fixes on new actions

---

src/targets/mobile/config.xml

This fork is up to date, and support the new iOS system for `entitlements`. 
Before, it was not possible to have universal links support by building the app from the cli. It worked from XCode, though. 
Now, with this forks, we can build from testflight... ;)

fix: Use a more recent universal link plugin

---

package.json
src/ducks/transactions/helpers.js
src/ducks/transactions/helpers.spec.js
yarn.lock

Using calendar months difference was not the good solution because the
calendar months difference between `2019-05-31` and `2019-06-01` is `1`.
We want to have the difference in full months.

fix(transactions): Late reimbursement use real months difference

---

src/ducks/account/helpers.js
src/ducks/reimbursements/HealthReimbursements.jsx
src/ducks/transactions/helpers.js

The reimbursement tag was not taken into account on these pages. This is now the case. Still behind the `reimbursement-tag` flag.
The health reimbursement virtual account's balance is computed by taking only pending reimbursements. And the reimbursements page split the transaction according to their reimbursement tag.

Handle reimbursement tag on balance and health reimbursements pages

---

test/fixtures/demo.json

Use manualCategoryId instead of automaticCategoryId so the transactions
don't appear as "categorization in progress" when we inject it in an
instance

chore(fixtures): Use manual categories

---

src/ducks/balance/components/AccountRow.jsx

The `u-c-pointer` class is not automatically imported by cozy-ui because no react component uses it. So for now we use a custom `u-clickable`.

fix(AccountRow): Show a pointer when hovering the row

---

src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusModal.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusModal.styl

On iOS, clic on the radio buttons is not registered because the clic area
is too small. Here I make the Radio the same height as the list Rows.

fix: Make the Radio the same height as the List Row

---

package.json
yarn.lock

This cozy-ui release fixes an alignement issue on `Chip`

fix(deps): Update cozy-ui to v20.10.1

---

src/ducks/account/helpers.js
src/ducks/categories/CategoriesPage.jsx

When categories page is display, it reset filter if filtering doc is reimbursements accounts

feat: Don't display reimbursements accounts on categories

---

src/ducks/reimbursements/HealthReimbursements.jsx

There was no loading indicator on the health reimbursements page, causing a « jump » in the rendering.

feat(HealthReimbursements): Add loading indicator

---

src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusModal.styl

The fact that label had a span children created an incompatibility with
fastclick. We remove pointer-events on the children so that the click
arrives directly on the label and can be picked up by fastclick correctly.

fix: Make click work reliably on Radio buttons

---

src/components/Loading/Loading.styl

Vertical margins had disappeared after 5acaf522a8717a2c8764ab10d23d687899b04b5f

fix: Add vertical margins to Loading

---

package.json
yarn.lock

The main goal is to have a cozy-bar with a fresh cozy-ui (20.7.0). This
indirectly fixes an issue when building for mobile: cozy-bar's cozy-ui
stylesheet is overriding the app's cozy-ui stylesheet. Which means that
if the cozy-bar has an old cozy-ui, we can have weird bugs on the mobile
app.

fix(deps): Update cozy-bar to v6.28.5

---

src/components/ScrollToTop.jsx
src/ducks/reimbursements/ReimbursementsPage.jsx

When navigating to this page, the scroll level from the previous page is
kept. We need to scroll to the top of the page when it is mounted.

feat(ReimbursementsPage): Scroll to the top of the page on mount

---

src/components/KonnectorChip/KonnectorChip.jsx
src/components/KonnectorChip/index.js
src/components/KonnectorChip/readme.md
src/components/Section/Section.jsx
src/components/Section/Section.styl
src/components/Section/index.js
src/components/StoreLink/StoreLink.jsx
src/components/StoreLink/index.js
src/ducks/reimbursements/HealthReimbursements.jsx
src/ducks/reimbursements/HealthReimbursements.spec.jsx
src/ducks/reimbursements/HealthReimbursements.styl
src/ducks/settings/AddAccountLink.jsx
src/ducks/transactions/actions/KonnectorAction/index.jsx
src/locales/en.json
src/locales/fr.json
styleguide.config.js

* Show some messages when there is no pending reimbursements and/or reimbursed transactions
* Show a link to the store filtered on insurance konnectors when there is no reimbursed transactions
* Dinstinguish the sections visually
* Some minor style updates
Live on https://testbanksemptyreimbursementspage-banks.cozy.works

Empty health reimbursements page

---

src/ducks/notifications/Notification.js
src/ducks/notifications/Notification.spec.js

We had a `this.generateURLs is not a function` error. Using the class name (`Notification`) fixes it.

fix(Notification): Reference class name instead of this

---

package.json
src/lib/sentry.js
yarn.lock

This is not the reason why communication with sentry failed (see https://github.com/cozy/cozy-doctypes/pull/92 for that), but this way we use the latest raven-js version. We must keep in mind that this SDK is now deprecated and only receives bugfixes.

Update raven-js to v3.27.2

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json

Some amazon bank transaction label includes the string `amazn` instead
of `amazon`. Setting the `o` to be optional matches these cases.

feat(brands): Update amazon regexp

---

src/ducks/settings/Configuration.jsx
src/ducks/settings/ToggleRow.jsx
src/ducks/settings/ToggleRow.styl
src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js
src/locales/en.json
src/locales/fr.json

This is a first step of the implementation of the new health reimbursement notification: the UI. The toggle is hidden behind the `late-health-reimbursement-notification` flag.

Add late health reimbursement notification UI

---

src/components/App.jsx
src/ducks/transactions/helpers.js
src/ducks/transactions/helpers.spec.js

Before, we showed that a health reimbursement is late if it was pending for more than 1 month. Now, we want to use the late health reimbursement notification value instead of the hard coded `1 month`.
To do that, we need the setting. Since we don't want to fetch the settings everytime we want to show a reimbursement status, and we will need it in services too, we store the value in a flag just like we did for the local categorization model override setting.

Use late health reimbursement notification value to show status

---

src/ducks/client/mobile/redirect.js

Sometimes the iOS app can not retrieve the remote json apple app site validation. In this case the user can not login. 
We add a new fallback attribute only when login on mobile device to resolve this issue.

fix: UL bug on iOS

---

src/utils/flag.js

The user has access to the setting to enable the late health reimbursement notification by default.

feat(notifications): Enable late reimb notif flag by default

---

src/index.ejs
src/targets/mobile/config.xml

We need to use our fork because we have a fix to handle correctly iOS 12. There is already a PR upstream (https://github.com/cjpearson/cordova-plugin-keyboard/pull/85). 
To work, we have to set the meta `viewport-fit=cover`. Without this attribute, the view-size is not well calculated and we have a wrong value. It makes the form not having the right size and having the footer displayed on the "input".

fix: Issue with keyboard on iOS during login

---

src/ducks/transfers/TransferPage.jsx

- Some accounts have no IBAN so they could not be matched with beneficiaries. We can use
account number instead of IBAN.
- We need to have all recipients, so we use fetch more to load them all.

fix: Transfers

---

src/ducks/settings/Debug.jsx

This adds two things in the settings debug panel:
* Show the device token so we can grab it and use it to send a test notification directly from Firebase UI
* Show a « send notification » button that asks the stack to send a dummy notification when we press it. This is not working on mobile app for now. The backformers will have a look at it asap

Notifications debug

---

src/ducks/transactions/actions/ReimbursementStatusAction/index.js
src/ducks/transactions/actions/index.js

ReimbursementStatusAction can match but render nothing. By putting it at
the latest position, we ensure that it doesn't prevent another action
from rendering.
This could be fixed in a better way, but there is a demo need for today.

fix(actions): Put reimbursement status last

---

src/components/AccountIcon/index.jsx
src/components/AccountIcon/styles.styl
src/ducks/transfers/TransferPage.jsx

Needed to have a larger icon on password slide. Added a size prop
to AccountIcon

feat: Large account icon for password

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json

Added to maintenance : autolib, booking, cultura, deezer, deliveroo, engie, leclercdrive, zalando
Added : electricitestrasbourg, ldlc, macif

fix: Add connectors to "maintenance"

---

package.json
yarn.lock

This dependency seems to have been added by mistake since it is only a
security holding package (see https://npmjs.org/yarn.lock).
Closes #1293.

chore(deps): Remove yarn.lock

---

package.json
src/targets/mobile/config.xml

<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …

Release 1.2.0

---

src/targets/mobile/config.xml

Actually the plugin works great on iOS 10 and iOS 12 but not on iOS 11. So removing it ATM.

fix: Remove keyboard plugin since it works on iOS 10 & 12 but not on 11

---

src/components/List/index.jsx

Since I changed to use List.Radio instead of Radio, the classname
removing pointer-events on the children was not added to the element.

fix: Click on list radio was not working well

---

src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx
src/ducks/transactions/actions/AttachedDocsAction/BillChip.spec.jsx

When a bill has no invoice, it throws an error but we didn't catch it, so it was propagated until the error boundary. So the whole app crashed. Now we catch it and render nothing.

fix(BillChip): Render nothing if a bill has no invoice

---

src/ducks/reimbursements/HealthReimbursements.jsx

The context for actions was not used, thus the actions were not
receiving all the data they need to be able to work properly. Now the
page is wrapped in a provider.

fix(HealthReimbursements): Use transactions actions context

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json
src/ducks/transactions/actions/ReimbursementStatusAction/Card.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/Card.spec.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/Card.styl
src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusModal.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/__snapshots__/Card.spec.jsx.snap
src/locales/en.json
src/locales/fr.json

Brands contacts can include their mobile app. In that case, we check if the current platform matches the contact app platform to show a card or not. The card redirects the user to an URL that allows him to open the app.

Handle app contacts in reimbursement status modal

---

src/ducks/transactions/actions/ReimbursementStatusAction/Card.styl

As usual, we need to double a selector so it's applied on the mobile app, where the cozy-bar's CSS is taking precedence over app's CSS. This issue will be fixed when the cozy-bar really bundles its own cozy-ui.

fix(ReimbursementStatusAction): Card styles are applied on mobile app

---

src/ducks/transfers/TransferPage.jsx

UIAppIcon does not reload icon when fetchIcon changes which meant that AccountIcon would not correctly update in the transfer flow if changing accounts. 
Adding a key forces the usage of a completely new component, bypassing
the need for a componentDidUpdate.
https://github.com/cozy/cozy-ui/issues/1076

fix: Correctly update Icon

---

package.json
src/doctypes.js
src/ducks/settings/Configuration.jsx
src/ducks/settings/DelayedDebitAlert.jsx
src/ducks/settings/DelayedDebitAlert.styl
src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js
src/locales/en.json
src/locales/fr.json
yarn.lock

Previously the delayed debit alert UI was using an object like `{ creditCardAccount: id, checkingsAccount: id  }` stored in `io.cozy.bank.settings`. But after thinking about what could happen when a user removes an account that is part of the associations, I thought this solution was not good enough because we would have to manually update the object everytime the user removes an account.
I think using a relationship on the account is better because it automatically handles bank accounts removal:
* If the credit card account is removed, then the relationship is also removed
* If the checkings account is removed, then the relationship is null
There are two remaining things to do:
* ~~Update cozy-client after https://github.com/cozy/cozy-client/pull/473 has been merged (we are using …

feat(DelayedDebitAlert): Use bank accounts relationships

---

src/ducks/settings/Configuration.jsx

We need to export the "dumb" component to use the next override method.

fix: Export dumb configuration component

---

src/ducks/transactions/TransactionSelectDates.spec.jsx

Mock the date so we don't have problem on each new month.
This fixes the issues we currently have with tests. See https://travis-ci.org/cozy/cozy-banks/jobs/552657202#L642

test(TransactionSelectDates): Don't fail on each new month

---

src/ducks/transactions/TransactionRow.jsx

The `brands` and `urls` props were manually passed to `TransactionActions` instead of letting it use the ones from the context. This caused a bug in which when you click on the reimbursements status default CTA on mobile, the reimbursement status modal opened without contacts infos.

fix(TransactionRow): Default CTA on mobile

---

test/fixtures/notifications-service/delayed-debit.json

This fixture sets a big `comingBalance` on the `Léa Credit Card`
account, so it will trigger the delayed debit alert with all checkings
accounts from fixtures

chore(fixtures): Add delayed debit notification fixture

---

package.json
yarn.lock

Since cozy-doctypes is a peerDep of cozy-procedure, we need to be up to date in banks to have access to new methods

chore: Upgrade cozy-doctypes

---

src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx

We now show the vendor name of each reimbursement bill on the `AttachedDocsAction` (if the bill has a vendor).

feat(AttachedDocsActions): Show reimbursements vendors

---

src/ducks/brandDictionary/withBrands.jsx
src/ducks/reimbursements/HealthReimbursements.jsx
src/ducks/reimbursements/HealthReimbursements.spec.jsx
src/ducks/transactions/TransactionActionsProvider.jsx

Previously we showed a link to the store when there was no reimbursed transactions. Now, we show it if there is neither reimbursed transaction nor health brand triggers.

feat(HealthReimbursements): Show store link if no health brands

---

src/AppContainer.jsx
src/components/App.jsx

This makes the icons available everywhere in the app, including on the
mobile app's welcome screen.

fix: Import cozy-ui icon sprite at higher level in components hierarchy

---

.lintstagedrc
package.json
yarn.lock

It happens many times that we push some code, then realize that there is a lint issue or we forgot to update tests. Linting updated files and running related tests on precommit will make an error pop in front of us a lot quickier than by waiting for the CI to be red, then see it some minutes after, then have to refresh your mind about what you were doing (switching context is hard).
Obviously, this would make the `git commit` not instant anymore. But I personally prefer waiting a few seconds and fix issues after that than waiting for the CI to tell me if something is wrong and switching context too many times. And for those who want to commit and think about lint and tests later, there is still `--no-verify` flag :)
Also, lint-staged now supports partially staged files, so we don't have …

Lint updated files and run related tests on precommit

---

package.json

Disabling sending stats makes ios:install_pods work faster

feat: Disable sending stats when installing pods

---

src/ducks/stats/services.js
src/ducks/stats/services.spec.js

Periods used in tests were wrong and led me to wrongly subtract 1 to the number of months in `getMeanOnPeriod` function. Actually after correcting the period in tests, we don't need to subtract anything.

fix(stats): No need to subtract a month to compute mean on period

---

src/targets/services/stats.js

We previously used only the additional income subcategory, but we actually want to include all incomes except activity incomes in this sum.

Compute additional income using all income subcategories except activity income

---

config/webpack.target.mobile.js

When using the minified bar, after building banks production,
the bar code is minified two times and what seems like a minification bug happens.
The bug happens in the react-select code : https://github.com/JedWatson/react-select/blob/c22a4b20aef2161ebaa3a0373de7e0e179e73693/packages/react-select/src/components/Menu.js#L250
`alignToControl` is inlined by the minification, and `placement ? placementToCSSProp[placement] : "bottom"` gets simplified into `"bottom"` which forces the react-select menu to always come on top.
---
in bar.min.js
```js
menu: function(e) {
var t, n = e.placement,
r = e.theme,
o = r.borderRadius,
a = r.spacing,
i = r.colors;
return F(t = {}, function(e) {
return e ? {
bottom: "top",
top: "bottom"
} [e] : "bottom"
}(n), "100%"), F(t, "backgroundColor", i.neutral0), …
```

fix: Do not use minified bar

---

src/actions/accounts.js
src/actions/accounts.spec.js

When an account is deleted, we want to also delete its correspondig `io.cozy.bank.accounts.stats` document if it exists.

feat(settings): Delete accounts stats when an account is deleted

---

manifest.webapp

We want the stats service to be run when a transaction is updated. This way when a user recategorizes a transaction, the stats are computed again.
Also, the service now uses a 1mn debounce.

Update stats service trigger and debounce

---

package.json

ATM, our internal jenkins can not run node 10 (so we can't deploy new version) . Let's remove this requirement ATM until our internal tools can run on node 10. (in a few days)

Chore: Do not force node 10 usage

---

package.json
src/components/AppRoute.jsx
src/ducks/balance/Balance.jsx
src/ducks/client/mobile/mobile.js
src/ducks/mobile/MobileRouter.jsx
src/ducks/mobile/bar.js
yarn.lock

We previously `render null` while settings were being fetched. This resulted in a brief totally white screen when the user launched the app or switched to the balances page.
This exposed some previously unknown bugs related to cozy-authentication and cozy-bar. That's why these dependencies are upgraded in this PR.
See https://github.com/cozy/cozy-libs/pull/656 and https://github.com/cozy/cozy-bar/pull/613 for more infos.

Fix white screen when switching to balances page

---

package.json
src/ducks/transfers/steps/Amount.jsx
yarn.lock

The amount field in the transfer wizard did not have a unit.

feat: Use a FieldGroup to add the euro unit

---

package.json
yarn.lock

Since we're using cozy-logger in this code base, we should add it as a dependencies right?

fix: Add cozy-logger as a dep

---

package.json
yarn.lock

We need the `queryAll` method that is available since v6.54.0

fix(deps): Update cozy-client to v6.55.0

---

package.json
src/main.jsx
src/targets/mobile/config.xml
webpack.config.js

<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …

Release 1.4.0

---

src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx
src/ducks/transactions/actions/AttachedDocsAction/index.js

We had two problems :
* If the transaction has the same bill attached in `bills` and in `reimbursements` (which occurs in our matching algorithm), then each bill was shown two times. To avoid that, we `uniqBy` on the bills ids
* We shown `bill.vendor` in the bill chip, but sometimes this is a real name, sometimes this is a slug. To avoid showing a slug, we search the brand in our dictionnary and we get its name from here

Fix in AttachedDocsAction

---

src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.js
test/fixtures/matching-service/cases/17.js

We use `realisationDate` in priority for every transactions since this
is the most accurate date for each account types. This is particulary
true for credit card accounts, for which transactions always have a date
at the last day of the month. For other types, the `realisationDate` is
very close to the `date`, so we can use it safely in the matching
context.

fix(Linker): Use realisationDate in byDate filter

---

scripts/import_mobile_keys
src/components/Delayed.jsx
src/ducks/transactions/TransactionsPage.jsx

We delay the rendering of transactions for the transactions page to be shown right away (initially only with the header) after user click.
Visible on http://testbanksadddelaytransactionspage.cozy.works/

feat: Delayed render for snappier user XP

---

package.json
src/ducks/categories/helpers.js
src/ducks/categories/helpers.spec.js
yarn.lock

I extracted `getCategoryId` logic in cozy-doctypes because we needed it in cozy-procedures (see https://github.com/cozy/cozy-libs/pull/701). In this PR I refactor `getCategoryId` so it only gets the `local-model-override` flag and pass it to `BankTrasaction::getCategoryId`.

refactor(categories): Use cozy-doctypes BankTransaction::getCategoryId

---

src/ducks/billsMatching/Linker/Linker.spec.js
src/ducks/billsMatching/Linker/billsToOperation/findNeighboringOperations.js
src/ducks/billsMatching/Linker/billsToOperation/helpers.js
src/ducks/billsMatching/Linker/billsToOperation/helpers.spec.js
src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.js
src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.spec.js
src/ducks/billsMatching/matchFromBills.js
src/ducks/billsMatching/matchFromBills.spec.js
src/ducks/billsMatching/matchFromTransactions.js
src/ducks/billsMatching/matchFromTransactions.spec.js
test/fixtures/matching-service/cases/18.js
test/fixtures/matching-service/cases/19.js
test/fixtures/matching-service/cases/20.js
test/fixtures/matching-service/cases/21.js

The `io.cozy.bills` documents can now carry some matching criterias (see https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.bills.md#optional-attributes-but-some-are-important-depending-the-context). This PR updates the matching algorithm so these criterias are taken into account if they exist. If a bill doesn't have its own matching criterias, the previous defaults criterias apply.
This PR misses the combined bills with criterias case. I'm going to handle it in its own PR so this one is not delayed in its entirety.

Handle bills matching criterias in matching algorithm

---

src/ducks/billsMatching/Linker/Linker.js
src/ducks/billsMatching/Linker/Linker.spec.js
test/fixtures/matching-service/cases/22-combined-health-bills.json
test/fixtures/matching-service/cases/23-combined-health-bills-with-criterias.json

This was the last missing piece in https://github.com/cozy/cozy-banks/pull/1465. Now we also handle matching criterias when we try to combine bills by making the union of the different matching criterias. At the moment, we can't find a real application to this, but it ensures that the matching doesn't crash if it happens.

Handle matching criterias in combined bills

---

package.json
src/ducks/notifications/html/templates/index.js
src/targets/services/onOperationOrBillCreate.js
test/readFileESM.js

There were two problems:
* We recently update raw-loader from v1 to v3. But since v2 it uses ES modules, so we had to reflect that when using it to import handlebars templates
* `matchFromBills` could be executed with an empty array, which is useless

Fixes in services

---

renovate.json

I am trying to group related packages to have less noise in GitHub notification area.
If it works well for banks, we could put this into the renovate config for cozy.

chore: Grouping related packages

---

src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.js
src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.spec.js

Until now, we maintained a vendors list to check if a bill has the
health type or not. This is not very scalable because we have to add new
vendors when new connectors are released, and we can do typos. Using the
bill `type` property is much more reliable.

fix(Linker): Don't use vendor to check bill type

---

src/ducks/balance/History.jsx

On first render the `size` prop contains an empty object. We need to
handle that case or the width passed to the `HistoryChart` component can
be `undefined`, creating a glitch on the appear animation.
Before:
After:

fix(History): Don't render the chart if width is undefined

---

package.json
src/ducks/notifications/html/templates/index.js

In https://github.com/cozy/cozy-banks/pull/1476 I forgot one place where the raw-loader is used and it introduced a regression in the notifications mails styles. Because basically no more styles from `styles.css` were imported.

fix(notifications): Correctly import stylesheet

---

docs/demo.md
docs/dev.md
toc.yml

We want to add our documentation to docs.cozy.io. This PR prepares this by reworking the development guide and adding a TOC file.
Some parts of our documentation looks old. We must update it, but doing it in one-shot can be hard. I propose we open small PRs from time to time to enhance it.

Make doc publishable on docs.cozy.io

---

src/ducks/categorization/services.js

While doing a totally unrelated exploration on services, I found that they receive a`COZY_TIME_LIMIT` environment variable that can be used in the `categorization` service instead of the hard coded time limit we had.

Use COZY_TIME_LIMIT env variable in categorization service instead of hard coded time

---

src/targets/services/helpers.js
src/targets/services/helpers.spec.js
src/targets/services/onOperationOrBillCreate.js

With this we can now pass arguments to the `onOperationOrBillCreate` service. For example by doing `cozy-stack --domain default.cozy.tools:8080 jobs run service --json '{"slug": "banks", "name": "onOperationOrBillCreate", "file": "onOperationOrBillCreate.js", "arguments": {"transactionsMatching": false, "billsMatching": { "lastSeq": "0"  } }}'` we can run the service and make it try to match all bills but bypass the matching from transactions.

feat(onOperationOrBillCreate): Get options from env and CLI

---

src/ducks/transfers/steps/Amount.jsx
src/ducks/transfers/transfers.js
src/ducks/transfers/transfers.spec.js

A forgotten hard coded string blocked transfers for other banks
than Caisse d Epargne.
Added a test to cover this.

Fix transfers

---

src/components/Carrousel.jsx
src/components/ErrorCard/index.jsx
src/components/ErrorCard/styles.styl
src/components/KonnectorUpdateInfo/index.js
src/components/KonnectorUpdateInfo/styles.styl
src/components/effects.js
src/ducks/balance/Balance.jsx
src/ducks/balance/components/AccountRow.jsx
src/ducks/balance/components/AccountRow.styl
src/ducks/transactions/TransactionPageErrors.jsx
src/ducks/transactions/TransactionPageErrors.spec.jsx
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/TriggerErrorCard.jsx
src/locales/en.json
src/locales/fr.json
src/utils/triggers.js
src/utils/triggers.spec.js
test/fixtures/triggers.json
test/fixtures/unit-tests.json

When one of the connection has a problem, we tell the user inside Banks so that they can fix that in the Home.
- Display connection status in Balance page
- Display more information and a button to the Home in Transaction page
- The connection problem banner is displayed in function of the account filter; if we are seeing a revolut account, we will not have a banner signalling the the caisse d'epargne account has a problem
- Since it is possible that groups contain one or more accounts with problems, we can display more than 1 error at a time. To reduce visual clutter, we display the errors in a carrousel.

Display connection problems in Banks

---

manifest.webapp
src/targets/services/onOperationOrBillCreate.js

When a user manually categorizes a transaction, we want to apply the
matching algorithm to it. For example, if a transaction is recategorized
to health expense category, maybe we can find a related bill that didn't
match previously because the category was not good.
I see a possible problem with that though: the service will be run twice when a transaction matched with a bill, because the matching updates the transaction. I don't know how I can do better than that actually. The only solution I have in mind is to compare the document and its previous revision to see precisely what changed and skip some parts of the service if needed. But the service will still be run twice.
I think it shows that we need to split the `onOperationOrBillCreate` service into multiple ones. Any thoughts?

feat(onOperationOrBillCreate): Find bills for all updated transactions

---

package.json
src/components/withContext.jsx
src/ducks/balance/components/AccountRow.jsx
src/ducks/brandDictionary/withBrands.jsx
src/ducks/transactions/TransactionActions.jsx
src/ducks/transactions/TransactionActions.spec.jsx
src/ducks/transactions/TransactionPageErrors.jsx
src/ducks/transactions/actions/index.js
src/utils/triggers.js
test/fixtures/demo.json

findMatchingActions was not called again if context changed. I think after
the perf improvements, some re-renders of the entire list were stopped before
reaching the TransactionActions, that were not re-rendered. Hence, it needs
to re-render, and recalculate matching actions by itself.

fix: Actions

---

docs/dev.md
package.json
src/ducks/bar/statusBar.js
src/ducks/bar/statusBar.spec.js
src/styles/palette.styl
src/targets/mobile/config.xml

Il faut savoir que sur iOS, si on ne fournit pas les splashscreen dans la résolution du device, alors iOS se met en mode "compatibilité" et ajoute les barres noires en haut et en bas. 
L'idée est donc de ne plus utiliser chaque splashscreen pour chaque résolution. Donc on met un splashscreen générique (celui qu'on copie à la fin), en faisant ça, on change le projet XCode pour passer de "AppImage" à "Launch Screen file". Ainsi, cordova génère un `LaunchStoryboard` qui devrait fonctionner partout.

feat: Supports iPhone X screen

---

src/ducks/bar/statusBar.js
src/targets/mobile/config.xml

iOS introduced recently the ability to have a dark mode. In this mode,
the default style for the status bar has white text so when the background
was white, we had invisible text.
The solution is to force light mode in Banks as suggested in the thread
on StatusBar's github (linked in comment).

Force Banks in light mode

---

renovate.json

- Group tooling packages + automerge
- Create master issue to have one place where we see renovate updates (less
noise in PRs and we will be able to close PRs that we will not merge soon)

Tweak renovate config

---

src/components/Chart/LineChart.jsx
src/ducks/account/AccountSwitch.jsx
src/ducks/apps/withAppsUrls.jsx
src/ducks/balance/Balance.jsx
src/ducks/balance/components/BalanceHeader.jsx
src/ducks/categories/CategoriesPage.jsx
src/ducks/categories/helpers.js
src/ducks/categories/helpers.spec.js
src/ducks/categories/selectors.js
src/ducks/chart/selectors.js
src/ducks/client/index.js
src/ducks/client/mobile/mobile.js
src/ducks/reimbursements/HealthReimbursements.jsx
src/ducks/transactions/TransactionsPage.jsx
src/main.jsx
src/selectors/index.js
src/store/configureStore.js

Features and refactors are mangled in this PR, I think it is helpful to have
both to understand the need for the refactors, but I can split this PR if
it is deemed necessary.
- In transaction page, history chart now updates based on month, this will
surely need more work to be perfect but it is usable right now
- In category page, go to the first month with data if current month does
not have any data
- Extract data mangling from the components
- Put cozy-client's store inside our own store to have easy access to cozy-client's
queries in our selectors without using the `enhancedState` semi-hack
fix #1131 
<details>
<summary>Changes:</summary>
c8298177 (Patrick Browne, 4 hours ago)
feat: Chart corresponds to selected month
a8d0a64d (Patrick Browne, 9 hours ago)
feat: Set filter to month …

Chart and categories improvements

---

src/ducks/commons/Nav.jsx

When opening the app, no tab was highlighted. The reason was just a typo on the `to` props for the balances nav item.

fix(Nav): Balances tab is highlighted by default

---

scripts/ci/mattermost_comment.sh
src/ducks/account/AccountSwitch.jsx

Recently, AccountSwitch was wrapped into translate() (by me :/) which
was a bad idea since it need to be passed t directly to work when
rendered inside the Bar.

AccountSwitch translation fix

---

src/ducks/transactions/TransactionPageErrors.spec.jsx

Since https://github.com/cozy/cozy-banks/commit/77783752c2dcc52e2b572e0babb6da78f4baa5b3, tests were broken because the flag check that was added is falsy in test env.
It makes our build red on master and all new PRs.

test: Fix TransactionPageErrors tests

---

src/ducks/categories/helpers.js

The import was changed in https://github.com/cozy/cozy-banks/pull/1605/commits/3fbe228fc1a0f96423a434a41770ff0600386871 but I didn't catch this while reviewing.
Maybe your intent was to move the `getCategoryIdFromName` from `ducks/categories/categoriesMap` to `ducks/categories/helpers` @ptbrowne?

fix(stats): Export getCategoryIdFromName from categories helpers

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json

This PR remove Deezer from long term maintenance in banks
If possible we need to synchronise publication of :
this PR,
the same kind of change in home : https://github.com/cozy/cozy-home/pull/1352
and the registry update (easy to do when we need it)

chore: Remove Deezer from maintenance in banks

---

docs/bills-matching.md
scripts/visualizer/index.html
scripts/visualizer/src/server/index.js
src/ducks/billsMatching/Linker/Linker.js
src/ducks/billsMatching/Linker/billsToOperation/helpers.js
src/ducks/billsMatching/Linker/billsToOperation/helpers.spec.js
src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.spec.js
src/ducks/billsMatching/matchFromBills.js

We had some inconsistency between the Linker's options names and the bills matchingCriterias properties names. This fixes it so the Linker code is more understandable.
Related to #1525

Use bills matchingCriterias names in Linker options

---

src/ducks/commons/Nav.jsx

When we navigated to pages with nested routes (like clicking on "manage my accounts" on the home page to navigate to `/settings/groups`), the selected element of the nav as not updating properly.
I first added the regular expressions for each route. It was not OK when navigating, but it was OK when refreshing or coming on the app on a specific route directly.
Removing the `React.memo` call around `NavLink` fixes the issue while navigating. Actually, a `NavLink` props don't change when navigating to another page without clicking directly on a `NavLink`, so it seems we can't use memo here.

fix(Nav): Show selected item on nested routes

---

src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.spec.jsx
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/actions/KonnectorAction/helpers.js

Transactions.jsx now knows if on subcateg and does not show the error
banner if we are on a subcategory.

feat: Do not show connection errors banner when browsing via categ

---

src/ducks/transactions/TransactionPageErrors.jsx
test/fixtures/unit-tests.json

Since all errors are not actionable for the user, we don't show all
errors, but some of them:
CHALLENGE_ASKED
DISK_QUOTA_EXCEEDED
TERMS_VERSION_MISMATCH
USER_ACTION_NEEDED
USER_ACTION_NEEDED.CHANGE_PASSWORD
USER_ACTION_NEEDED.ACCOUNT_REMOVED
We don't show LOGIN_FAILED errors because we have too many false
positives for this error.

feat(transactions): Show only actionable accounts errors

---

src/ducks/balance/components/AccountRow.jsx
src/utils/flag.js

We want to be able to activate the transactions-error-banner flag on the
transactions page without activating it on the balances page. To achieve
this, we use a different flag (balance-account-errors) on the balances page.
Also enabled transactions-error-banner flag by default.

Dissociate transactions-error-banner flag and balance-account-errors flags

---

docs/services.md
src/ducks/categorization/services.js
src/ducks/settings/Debug.jsx

We used a format that is working but that is not the one that is really
expected by the stack. It resulted in a weird job structure in the
io.cozy.jobs couch base and Bender was not able to show the service
name.
See https://github.com/cozy/cozy-stack/issues/2159

fix: Use the good format when calling services

---

src/components/SelectDates/SelectDates.styl
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/TransactionsPage.spec.jsx

Fixes an inconsistency bug on the currentMonth state variable when navigating
between accounts/groups from the transaction page.
More explanation in the concerned commit.

fix: Month selector inconsistencies

---

src/targets/mobile/config.xml

Since the 1st November, android app needs to target at least SDK 28. We can update our cordova-android, but it's easier and safer to only specify this target in the config.

fix: Android targetSDKVersion

---

src/ducks/client/index.js
src/ducks/filters/index.js
src/ducks/loan/LoanListPage.jsx

When reloading the page, the accounts were not present, so when we tried
to access to the group's accounts relationship, the app crashed. To fix
this, I connected the component to the accounts query and ensured we
have the data before showing the accounts list. While data is loading,
a spinner is shown.

fix(loan): Don't crash on reload

---

src/ducks/client/mobile/mobile.js
src/ducks/client/mobile/mobile.spec.js
src/ducks/settings/Debug.jsx

Plugin like Push and Sentry were not correctly initialized since the
register method was called instead of the registerPlugin method.
Unfortunately the register method exists on the client and does not
fail in case of wrong argument.

Fix plugin initialisation

---

package.json
src/ducks/settings/Settings.styl
yarn.lock

Introduced after cozy-ui put flex-basis auto on tab items

fix: Tabs no longer take all the width of the screen

---

src/components/MultiSelect/index.jsx
src/ducks/categories/CategoryChoice.jsx
src/ducks/categories/CategoryChoice.spec.jsx

Since the others category is also the parent category, we have
to check at which level we are when reporting if the item is
selected.
Added tests on CategoryChoice.

Two items selected in CategoryChoice

---

src/utils/flag.js

We want to enable the new loan details page for everyone.

feat: Enable loan details page flag by default

---

src/components/MultiSelect/index.jsx
src/components/Row/index.jsx
src/ducks/balance/BalanceDetailsHeader.spec.jsx
src/ducks/balance/components/GroupPanel.spec.jsx
src/ducks/budgetAlerts/CategoryBudgetNotificationView.js
src/ducks/budgetAlerts/index.js
src/ducks/budgetAlerts/service.spec.js
src/ducks/categories/CategoryChoice.jsx
src/ducks/categories/CategoryChoice.spec.jsx
src/ducks/categories/categoriesMap.js
src/ducks/categories/categoriesMap.spec.js
src/ducks/settings/CategoryAlerts/CategoryAlertCard.jsx
src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.jsx
src/ducks/settings/Configuration.jsx
src/locales/en.json
src/locales/fr.json
test/fixtures/unit-tests.json

A flaw in the data model (ids for parent categories are the same as the
the one used for "others" subcategories) is now handled through the use
of an attribute on the alert. If the `categoryIsParent` boolean attribute
is true, all categories pertaining to this category will be included in
when checking for expenses. If it is false, it means that the user has
configured the alert with the "others" category of this parent category.
```
{
categoryId: '400600'
}
// Others: health
{
categoryId: '400600',
categoryIsParent: true
}
// Health parent category
```

feat: Correctly handle parent categories in budget alerts

---

src/ducks/balance/components/GroupPanel.jsx
src/ducks/settings/CategoryAlerts/CategoryAlertCard.jsx
src/ducks/settings/CategoryAlerts/CategoryAlertCard.styl
src/locales/fr.json
src/styles/utilities.styl

- Change text of buttons for buttons of modal not to be on two lines on mobile
- Increase click area of remove alert button (area shown below)

UI tweaks for category alerts

---

src/components/App.jsx
src/ducks/pin/LockedBody.jsx
src/ducks/pin/PinAuth.jsx
src/ducks/pin/PinGuard.jsx
src/ducks/pin/PinGuard.spec.jsx
src/ducks/pin/plugin.js
src/ducks/pin/plugin.spec.js
src/ducks/pin/storage.js
src/ducks/settings/Debug.jsx
src/main.jsx

- Do not wait for pin doc to be fetched before showing pin (if already fetched once, use localStorage to store pinDoc)
- While app is mounting, do not flicker the screen without auth if last interaction
was too long ago (use localStorage to store last interaction)
- Clear values stored locally on client's logout

Pin improvements

---

src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusAction.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusAction.spec.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/match.js
src/ducks/transactions/actions/ReimbursementStatusAction/match.spec.js
src/ducks/transactions/helpers.js
src/ducks/transactions/helpers.spec.js

By using the same condition, we ensure that when we match, we can render
something.
In c537e0367e49f00047617936b245ede5172014c6 you added a comment Drazik, I think I am doing what you meant but if you can confirm :)

refactor: Same condition for rendering and matching for reimbursements

---

src/ducks/transactions/helpers.spec.js

Some tests related to reimbursements hydratation were ignored via
xdescribe. I reworked the tests to use createClientWithData and
client.hydrateDocument, which should be closer to what we do outside
of tests.
There remains a test "should not be hydrated if transaction not in the health category" which I had to mark a `xit`. I think we should remove this
test as it seems to be out of date now that normal transactions can have
reimbursements. @drazik ?

Tests reactivate tests on reimbursements hydratation

---

src/ducks/account/services.js
src/ducks/account/services.spec.js
test/client.js

This route returns the myself contact if it exists and creates it with
basic infos if it doesn't.
See https://docs.cozy.io/en/cozy-stack/contacts/#post-contactsmyself
So now we get myself contact from this route and we don't have to worry if the contact exists or not. The stack creates it with at least the instance email address if it doesn't exist.
We bail out if the request to the stack to fetch myself contact fails, though.

feat(linkMyselfToAccounts): Use stack's POST /contact/myself

---

package.json
src/components/Table/styles.styl
src/components/Title/Title.styl
src/doctypes.js
src/ducks/account/helpers.js
src/ducks/balance/Balance.jsx
src/ducks/balance/BalancePanels.jsx
src/ducks/balance/components/AccountRow.jsx
src/ducks/balance/components/AccountRow.styl
src/ducks/balance/components/AccountsList.jsx
src/ducks/balance/components/GroupPanel.jsx
src/ducks/settings/AccountSettings.jsx
src/ducks/settings/AccountsSettings.jsx
src/ducks/settings/AccountsSettings.styl
src/ducks/settings/NewAccountSettings.jsx
src/ducks/settings/NewAccountSettings.styl
src/ducks/transactions/__snapshots__/TriggerErrorCard.spec.jsx.snap
src/locales/en.json
src/locales/fr.json
yarn.lock

This adds all features around the bank accounts owners.
On the home page, we show the owners if there are more than 1 differents unique owners accross all bank acounts. On desktop, we add a column on each row. On mobile, I had to update a little the DOM structure because vertical alignment between columns depends on the presence of owners (see screenshots below). (this is behind the `balance.show-owners` flag. It is also possible to use the `balance.force-show-owners` flag to force owners rendering, even if there is only one unique owners).
On the accounts list parameters page, we want to show the owners on each line. (this is behind the `settings.show-accounts-owners` flag).
On the account parameters page, we show a completely new component (behind the `settings.new-account-details-page` …

Show and edit bank accounts owners

---

src/ducks/settings/AccountsSettings.jsx
src/ducks/settings/AccountsSettings.styl

When the label and/or the owners are too long, they are cut with ellipsis.

feat(AccountsSettings): On mobile, show owners alongside the label

---

scripts/release-pr-template.txt
src/ducks/settings/CategoryAlerts/CategoryAlertCard.jsx
src/ducks/settings/CategoryAlerts/CategoryAlertCard.spec.jsx
src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionModal.spec.jsx
test/AppLike.jsx

- Correct i18n string for category alert card when the alert is configured for a group
- Correct text in alert when application date of a transaction is changed
back to the original month

Backported fixes from release 1.8.0

---

scripts/release-pr-template.txt

Removed unused tasks from PR (flo does the tasks directly on the Play Store
and Itunes Connect)

chore: Remove unused tasks from release PR

---

package.json
scripts/release-pr-template.txt
src/ducks/transactions/TransactionPageErrors.jsx

We now want to show LOGIN_FAILED errors on the transactions page. They were previously not shown because we had false positives.

feat(TransactionPageErrors): Add LOGIN_FAILED to actionable errors

---

package.json
src/ducks/settings/CategoryAlerts/AccountGroupChoice.spec.jsx
src/ducks/settings/helpers.js
src/ducks/settings/helpers.spec.js
test/fixtures/unit-tests.json

To correctly label a group, we need to pass `t` in case it is
a virtual or auto group.

fix: Crash when selecting group in notification setting

---

src/ducks/loan/LoanProgress.jsx
src/ducks/loan/LoanProgress.spec.jsx

A loan account does not necessary have all the required amount
properties to show a progress bar. When it doesn't have it, we simply
show nothing.

fix(LoanProgress): Render nothing if some data is missing

---

src/ducks/notifications/BalanceLower/index.js
src/ducks/notifications/BalanceLower/index.spec.js
src/ducks/notifications/TransactionGreater/index.js
src/ducks/notifications/TransactionGreater/index.spec.js
src/ducks/notifications/services.js
src/ducks/notifications/services.spec.js

User can choose an account or a group to further filter a notification.
Implemented on 
- BalanceLower
- TransactionGreater

Implement account or group filtering for notifications

---

src/components/BackButton/index.jsx
src/components/BackButton/style.styl
src/components/EditionModal/EditionModal.jsx
src/components/Title/Title.styl
src/ducks/reimbursements/ReimbursementsPage.styl

BackArrow were not applied correctly.
We badly need automated screenshots.

fix: Back button styles were wrong on mobile

---

package.json
src/ducks/client/index.js
yarn.lock

When the user wants to add a contact to a bank account via the « add a contact » button of the ContactPicker, but don't have the contacts app installed, we want to redirect him to the store. That's the job done by https://github.com/cozy/cozy-ui/pull/1326. But for it to work, we have to register a realtime plugin to our client. For now the realtime plugin is implemented here and we will be able to extract it elsewhere (cozy-client? cozy-realtime?)
Todo:

Handle uninstalled contacts app

---

src/components/App.jsx
src/ducks/balance/components/GroupPanel.spec.jsx
src/ducks/notifications/LateHealthReimbursement/index.js
src/ducks/notifications/LateHealthReimbursement/index.spec.js
src/ducks/reimbursements/selectors.js
src/ducks/reimbursements/selectors.spec.js
src/ducks/settings/helpers.js
src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusAction.jsx
src/ducks/transactions/helpers.js
src/ducks/transactions/helpers.spec.js

The setting for health reimbursements late limit was "transferred" to flags
at app initialization. This was a shortcut/hack to easily get the late
limit in helpers. Now that we can more easily use selectors, it's better to
use them since they will refresh if the value is changed

refactor: Remove reimbursement late flag

---

package.json
src/ducks/balance/BalanceDetailsHeader.spec.jsx
src/ducks/balance/components/AccountRow.jsx
src/ducks/balance/components/GroupPanel.jsx
src/ducks/balance/components/GroupPanel.spec.jsx
src/ducks/settings/GroupSettings.spec.js
src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionsPage.spec.jsx
src/ducks/transactions/__snapshots__/TransactionModal.spec.jsx.snap
src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx
src/ducks/transactions/actions/AttachedDocsAction/BillChip.spec.jsx
src/ducks/transactions/actions/AttachedDocsAction/__snapshots__/BillChip.spec.jsx.snap
src/locales/en.json
src/locales/fr.json
test/client.js
test/fixtures/unit-tests.json
test/jest.setup.js
test/jestUtils.js
test/mockRouter.js
yarn.lock

Remove some warnings in tests. We are almost there ! At some point we will be able put
```
console.warn = logAndThrowException
```
Warnings are a useful tool when there are a small number of them but we had so much of them that the ratio signal / noise was too low, making us ignoring them where they can be of good help when refactoring / spotting bad patterns.

Warning tests

---

test/jest.setup.js

- Remove warning ignorer for connect() since we upgrade react-redux
- Add warning ignorer for react-swipable-views

test: Warnings

---

src/ducks/settings/__snapshots__/helpers.spec.js.snap
src/ducks/settings/constants.js

We have to update  the default settings to use the new multi rule format.

fix: Convert default alert rules to list

---

src/ducks/categories/withUpdateCategory.jsx
src/ducks/transactions/TransactionCategoryEditor.jsx
src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionModal.spec.jsx
src/ducks/transactions/Transactions.jsx

After refactoring TransactionCategoryEditor so that it can appear not 
necessarily in a modal, we forgot the one place where it should be in a modal

fix: Not in modal TransactionCategoryEditor

---

src/ducks/groups/helpers.js
src/ducks/groups/helpers.spec.js
src/targets/mobile/config.xml
static-files.txt

<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …

Release 1.12.0

---

config/webpack.config.hot-reload.js
docs/dev.md
package.json

I'm a cozy-scripts user so I'm a bit biased. But I can affirm that changing from Drive to Banks and not having the HMR working it's not very convenient... Fixed by using the same env var name. 
https://github.com/cozy/create-cozy-app/blob/v1.12.x/packages/cozy-scripts/utils/constants.js#L9

chore: Change ENV name var for HMR

---

src/components/KonnectorUpdateInfo/index.js
src/components/SelectDates/scrollAware.js
src/doctypes.js
src/ducks/account/AccountSwitch.jsx
src/ducks/account/services.js
src/ducks/budgetAlerts/CategoryBudgetNotificationView.js
src/ducks/budgetAlerts/index.js
src/ducks/groups/services.js
src/ducks/notifications/services.js
src/ducks/pin/queries.js
src/ducks/settings/AccountSettings.jsx
src/ducks/settings/AccountsSettings.jsx
test/client.js

Client.all is deprecated, we prefer to use Q that does not
induce us in errror.

Use Q instead of client.all

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json

This led to an io.cozy.app.suggestions containing the wrong slug, which
led to the suggestion of the humanis connector even if it was already
installed.
https://trello.com/c/uyYGL72O/339-%F0%9F%92%B6-pfm-suggestion-de-connecteur-en-double

fix: Humanis konnector slug was the wrong one in brands

---

test/fixtures/demo.json

Some transactions had an action or bill that was assigned to it but
shouldn't

chore: Clean actions and bills in fixtures

---

src/targets/mobile/config.xml

Since we need to have access to Crypto Web APIs, we have to drop iOS 10 support. (see https://github.com/cozy/cozy-stack/pull/2310)

feat: Drop iOS 10 support

---

src/ducks/account/helpers.js
src/ducks/account/helpers.spec.js
src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx
src/ducks/balance/helpers.js

In this PR, the main commit is a6008601. It's the intended fix. The problem was that when we tried to check or uncheck a virtual reimbursements account, it did nothing.
The reason is that the getPanelsState function was looking for a property called `id`. On
regular accounts it exists, but not on virtual accounts. Since in the same
function we use `_id` for groups, I updated it to also use `_id` on
accounts. But I also added an `id` property on virtual accounts, so they
have the same shape as a real account from the stack.
The others commits are things I saw along the debugging process and that I did so the code looked clearer.

Fix virtual accounts switches state

---

src/ducks/balance/components/AccountsList.jsx
src/ducks/balance/components/AccountsList.spec.jsx

For "classic" groups, we want to sort the accounts by ascending balance.
But for the reimbursements virtual group, we want to keep to original
order in which we created them (Health / professional / others)

feat(AccountsList): Keep original accounts order for reimbursements

---

src/components/Section/Section.jsx
src/components/Section/Section.styl
src/components/Section/index.js
src/ducks/reimbursements/Reimbursements.jsx
src/ducks/reimbursements/Reimbursements.spec.jsx
src/ducks/reimbursements/ReimbursementsPage.jsx
src/locales/en.json
src/locales/fr.json

* Use a specific title when the reimbursements group is selected
* Use a specific empty message for the reimbursements group
* Avoid a double border

Updates on reimbursements details page

---

src/ducks/categories/CategoriesHeader.jsx

The income toggle was hidden behind the fixed header with the date
select. Adding a top margin is a quick way to fix this, but we may have
a look at how to automatically add a margin when we have an additional fixed header
like this one
Before:
After:

fix(CategoriesHeader): Show income toggle again

---

scripts/import_mobile_keys

- Variables are declared at the same place
- Gangsters directory is no longer there, directories are organized by
apps
Check-dir now tries to check for the cozy-banks directory inside
the password store, otherwise we could have a false positive, since we
could check existence of the root password directory instead of the
cozy one.

fix: Update mobile import keys scripts

---

src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx

Since we were waiting for triggers to be loaded and they are not
stored in offline storage, we would display a loading spinner
even when we had data.

Fix balance when offline

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json

I think this PR is still needed to advertise the connector in banks if needed.
I updated the unit testing snapshots.
Seems good to me.

feat: Add brand Viasanté to dictionnary

---

src/components/Chart/LineChart.jsx
src/ducks/balance/History.jsx
src/ducks/reimbursements/Reimbursements.jsx
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.styl
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/TransactionsPage.styl
src/ducks/transactions/scroll/InfiniteScroll.jsx

Due to a change of HTML structure (remove one level of nesting), the
infinite scrolling was broken on desktop.

Infinite scroll fixes

---

src/ducks/recurrence/RecurrencePage.jsx
src/ducks/recurrence/utils.js
src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionRecurrenceEditor.jsx
src/ducks/transactions/TransactionRecurrenceEditor.styl
src/locales/en.json
src/locales/fr.json

When editing a transaction's recurrence through the modal, a new
choice is added : "New recurrence". When selected, this will
- create a new recurrence with information from the transaction. The
frequency is set to 30 days.
- attach the transaction to the newly created recurrence

Recurrence UI 6 : Ability to create a new recurrence

---

config/webpack.target.services.js
docs/services.md
manifest.webapp
src/ducks/recurrence/DebugRecurrencePage.jsx
src/ducks/recurrence/api.js
src/ducks/recurrence/service.js
src/targets/services/onOperationOrBillCreate.js
src/targets/services/recurrence.js
webpack.config.js

- Repair service build
Since the use of cozy-scripts, the build of services was broken.
App related configs were used even if we were in a service which
led to unexpected things like process.env being set to `{ USE_REACT: true }`.
This prevented services to run correctly as they rely on
environment variables to get COZY_URL and COZY_CREDENTIALS.
Now, app related configs are not used when building services.
- Extract recurrence service from onOperationOrBillCreate
At first, recurrence matching was made part of onOperationOrBillCreate
but this was a bad idea since other services have already been
isolated into their own services. For metrology and isolation purposes,
it is better to have each service function on its own.

Fix recurrence service

---

src/ducks/brandDictionary/brands.json

Banking transactions for "Le monde diplomatique" are
not necesarily formatted with a dash.
```
> a = new RegExp("\\bmonde[\\-\\s]diplomatique\\b", 'i')
/\bmonde[\-\s]diplomatique\b/i
> a.test('Le monde Diplomatique')
true
> a.test('Le monde-Diplomatique')
true
```

fix: Support monde diplomatique with a space

---

src/utils/flag.js

Connect the flag store to Figure defaultProp "blurred" so that when
the flag amount_blur is changed, the default prop is changed. Before,
we needed to reload the page/app after changing the setting.

fix: No need to reload page when changing blur setting

---

config/webpack.config.manual-resolves.js

We should not mock moment as empty in services, 
otherwise the stat service fails

fix: Moment should be present in stat service

---

config/webpack.config.plugins.js
src/ducks/recurrence/RecurrencesPage.jsx
src/main.jsx
src/utils/d3.js
src/utils/d3.spec.js

When choosing spanish, Banks would crash and show a blank page.
1. Spanish is added in builds
2. We do not crash if an unknown locale is chosen

fix: Do not crash when spanish locale is chosen

---

src/ducks/balance/components/BalanceHeader.jsx
src/ducks/balance/components/BalanceHeader.styl
src/ducks/search/SearchPage.jsx

Add a way to go to search page from balance page.
The goal is to have a 1st version of the search available for internal
use.

feat: Add search icon in balance page and back button in search page

---

src/ducks/account/helpers.js
src/ducks/account/helpers.spec.js
src/ducks/recurrence/RecurrencesPage.jsx
src/targets/mobile/config.xml

2 unrelated small improvements
- fix: Do not create virtual accounts if there are no transactions
If we have virtual accounts we do not display the special Empty page that
is shown if the user has no data
- feat: Sort bundles by category then by recency
In the recurrence page, we want the recurrence bundles
grouped by category and then sorted by date.

Improvements

---

src/ducks/balance/BalancePanels.jsx
src/ducks/balance/BalancePanels.styl
src/ducks/settings/AddRuleButton.jsx
src/ducks/settings/Rules.jsx

Using an overridable file for AddRule button since the
component changes completely
Export a component with theme overridable via defaultProps
for AddAccountButton since only the theme should be overridable.

Make buttons on BalancePage + settings overridable

---

src/components/BackButton/index.jsx
src/components/BackButton/style.styl
src/ducks/settings/GroupSettings.jsx
src/ducks/settings/GroupsSettings.styl
src/ducks/settings/NewAccountSettings.jsx
src/ducks/settings/NewAccountSettings.styl
src/styles/main.styl

BarTheme was not used in GroupSettings and AccountSettings
which broke colors (white title on blue background on a
white background bar).
Also fixed some little annoying things (border for menu
button, padding, ellipsis).

Fix bar color in accounts and group settings

---

config/webpack.target.services.js
scripts/ci/mattermost_comment.sh
src/targets/services/onOperationOrBillCreate.js

- A bug in the bundling of node-fetch would make the service fail.
- The failure was not appearing on our dashboards since the exit 1 was not reported

Repair push notifications

---

src/components/Header/Header.styl
src/ducks/balance/Balance.styl
src/ducks/balance/NoAccount.styl
src/styles/palette.styl

While theming, we want the no account special page to have a background
that is the same as the header color. Since in some themes, the header
is not the same color as the primary color, we cannot use the primary
color in the NoAccount styles, we use the inverse header color.
I renamed some variables with headerPrimary to headerInverted to better
make the distinction between the primary color and the "inverted" color.

feat: NoAccount background colors takes header inverted color

---

src/ducks/settings/GroupSettings.jsx
src/ducks/settings/GroupSettings.spec.jsx

When I refactored to use the new switch, I left a bind()
that kept the function from being called on click.

Correctly toggle an account in a group

---

config/webpack.target.services.js
src/ducks/notifications/BaseNotificationView.js
src/ducks/notifications/services.js
webpack.config.js

Since the introduction of cozy-scripts in the banks repository, we use
the TerserPlugin from cozy-scripts. Previously, we would configure this
plugin not to mangle function names in the webpack.target.services file.
Now, we need to directly tweak the options of cozy-scripts to achieve
the same goal.

Blank emails

---

src/ducks/analysis/AnalysisTabs.jsx
src/ducks/commons/Nav.jsx
src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionModal.spec.jsx
src/ducks/transactions/TransactionRow.jsx

Now that it has been tested on our prod, we can remove the flag. This
way, self-hosted cozynautes will be able to use recurrence
functionality.

feat: Activate recurrence flag

---

package.json
yarn.lock

This upgrade contains a bug fix for running banking connectors in maif-epa-custom context

chore: Upgrade harvest to version 2

---

manifest.webapp
package.json
src/components/AccountIcon/index.jsx
src/components/App.jsx
src/components/AppRoute.jsx
src/components/Spacing/Padded.jsx
src/components/__snapshots__/AppRoute.spec.jsx.snap
src/doctypes.js
src/ducks/balance/KonnectorIcon.jsx
src/ducks/settings/AccountsSettings.jsx
src/ducks/settings/HarvestBankAccountSettings.jsx
src/ducks/settings/HarvestSwitch.jsx
src/ducks/settings/HarvestSwitch.spec.jsx
src/ducks/settings/OldAccountSettings.jsx
yarn.lock

AccountSettings now use Harvest to edit an account.
- This functionality is behind the flag "banks.harvest-accounts-settings"
- Since banks is on react-router@3, we cannot use directly the routes from
Harvest and we have to simulate a Switch on our end.

Harvest in banks

---

package.json
src/ducks/settings/AccountsSettings.jsx
src/ducks/settings/AccountsSettings.spec.jsx
src/ducks/settings/HarvestBankAccountSettings.jsx
src/locales/en.json
src/locales/fr.json
yarn.lock

Previously, the bank accounts objects, in case they were disconnected
from their io.cozy.accounts (when the io.cozy.accounts has been
deleted by the user), would be stored in the state. Storing them in
the state prevented them to be updated in the DisconnectedAccountModal
when one was deleted.
Here we store only the connectionId in the state, and we get the accounts
by filtering them (on their connectionId) from the accounts coming
from the store. This ensures we do not show a stale UI.
...and other small commits.

fix: Refresh the DisconnectedAccountModal when an account is deleted 

---

src/ducks/settings/AccountsSettings.jsx
src/ducks/settings/AccountsSettings.spec.jsx

Historically, the bank connectors would not link the
io.cozy.bank.accounts they retrieved with the io.cozy.accounts that ran
the connector. We did not support this usecase. This is done by grouping
those unconnected accounts by konnector slug. This is not optimal as
ideally, we would like those to be grouped by io.cozy.accounts and not
by io.cozy.konnectors. But since we cannot know the io.cozy.accounts,
it is the best we can do.

fix: Handle io.cozy.bank.accounts without connection relationship

---

src/utils/cozyBar.js
test/jest.setup.js

For a time, banks needed a new version of the bar and we had relied
on the bar from the node_modules. This is different from the other
apps and we need now to revert this. Having the bar served from
the stack has several advantages:
- It diminishes the build size of the app
- It allows apps to cache the bar
- Every app uses the same bar

feat: Rely on the bar from the stack

---

package.json
src/ducks/recurrence/RecurrencePage.jsx
yarn.lock

Following an update of cozy-ui, ActionMenu were rendered incorrectly
- Need to reset the CozyTheme when rendering an ActionMenu inside
a CozyTheme otherwise the text is white inside the ActionMenu
- Need to reset the line-height otherwise text is cut inside ActionMenu
items

fix: Recurrence ActionMenu are rendered correctly

---

src/components/AccountIcon/index.jsx
src/ducks/balance/AccountRowLoading.jsx
src/ducks/balance/AccountsList.jsx
src/ducks/balance/KonnectorIcon.jsx
src/ducks/recurrence/search.spec.js
src/ducks/settings/AccountsSettings.jsx

KonnectorIcon from banks was replaced by KonnectorIcon from Harvest
but the API differed a bit, preventing the icons from being shown.
I am merging as soon as this is green.

fix: Show konnector icons

---

src/ducks/recurrence/RecurrencePage.jsx
src/ducks/recurrence/queries.js

Without a "fake" selector, the index could not be inferred by PouchDB,
breaking the loading of the recurrence bundle data.
Since there was no check to see if the query loading was in "failed"
status, the "no data found" message was shown to the user.

Fix recurrence bundle page loading

---

package.json
yarn.lock

This includes the removal of various direct dependencies of the bar, which means that an old version of babel-preset-cozy-app is no longer hoisted. This old version would "override" the babel-preset-cozy-app from cozy-scripts and would cause a build bug (jsx syntax not recognized).

feat: Update cozy-bar

---

src/ducks/tracking/browser.jsx
src/ducks/tracking/tracker.js

To be able to override the getTracker, we need to extract this function from the browser.jsx otherwise functions inside browser.jsx that use getTracker would retain a reference to the original getTracker function.

refactor: Extract getTracker to be able to override it

---

src/ducks/settings/BalanceLowerRules.jsx
src/ducks/settings/DelayedDebitAlertRules.jsx
src/ducks/settings/TransactionGreaterRules.jsx

We need to add the namespace to tracking event.
```patch
- pfm:alerte-budget
+ pfm:parametres:configuration:alerte-budget
```

fix: Add namespace for tracking event

---

src/targets/services/konnectorAlerts.js
src/targets/services/konnectorAlerts.spec.js

If there was a success after the last error, we must not take into account
the last error, and send a notification even if the last error was
actionnable.

fix: Send notification if there has been a success after the last error

---

package.json
src/ducks/settings/Rules.jsx
src/ducks/settings/makeRuleComponent.jsx
src/ducks/tracking/browser.jsx
yarn.lock

I was sending the complete page name (with parametres:configuration) instead
of only sending "alerte-solde_bas-on".

fix: Only send the last part of the page name for events inside edition modal

---

src/components/EditionModal/EditionModal.jsx
src/components/ModalStack.jsx
src/ducks/recurrence/RecurrencePage.jsx
src/ducks/recurrence/RecurrencesPage.jsx
src/ducks/tracking/browser.jsx
src/ducks/transactions/TransactionModal.jsx

- For events to correctly be attributed to each page, when closing the modal, we need to send a hit to the parent page.
- The transaction modal cannot know from where it is opened so it needs to send a page name that depends on the previous page. To achieve this, a functional variant of trackPage is added.
- Also fixed a bug where the events in the alert edition modal were sent with the complete page name, when we want only the events to have the last part.

Improve tracking in modals

---

package.json
yarn.lock

The new version of cozy-bi-auth embedded in this new version of cozy-harvest-libs contains BI information to be able to create Orange Bank connections from user browser.

feat: Upgrade cozy-harvest-lib to get Orange Banks with new cozy-bi-auth

---

manifest.webapp

With a recent change in the stack^1, it is no longer mandatory to have
a trigger for each service. So, we can remove the triggers for services
that are called from other services in the manifest.
1: https://github.com/cozy/cozy-stack/pull/2672

Remove the fake triggers in the manifest

---

package.json
src/ducks/search/SearchPage.jsx
src/ducks/search/SearchPage.spec.jsx
src/services/cli.js
yarn.lock

When arriving on the search page via the search icon on the transaction
modal, we have to perform the search immediately at mount.

Fix search via params

---

package.json
src/doctypes.js
src/ducks/balance/BalanceDetailsHeader.jsx
src/ducks/balance/BalanceHeader.jsx
src/ducks/filters/index.js
src/ducks/legal/LegalMention.jsx
src/ducks/transactions/TransactionHeader.jsx
src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/TransactionsPage.styl
src/ducks/transfers/TransferPage.jsx
src/selectors/index.js
yarn.lock

Add a placeholder component that can be overrided to show a legal mention.
- Balance page
- Transactions Page
- Transfer page
I had a problem with the transactions header since adding the legal mention
would modify the header height. Since the header is fixed, the list beneath
it has a padding-top for its content to end up lower than the header. Thus,
the padding-top and the header height should be the same. It was previously
done manually in CSS. Unfortunately, I could not override the stylus file:
there were build errors due to MiniCSSExtractPlugin. An alternative solution
was to compute dynamically the height in JS and set the padding-top accordingly.

Add legal mentions

---

package.json
yarn.lock

As commit described.
Upgrade cozy-harvest-lib.

chore: Upgrade cozy-harvest-lib to enable some new banking connectors

---

src/ducks/tracking/browser.jsx
src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionModal.spec.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusModal.jsx

/!\ Tracking is only activated if the Cozy user has opted in.
- Fix a tracking bugs in transaction modal
- Prevent double hits at "framework" level

Tracking improvements

---

src/ducks/settings/Debug.jsx

Native event sending was done for debug purposes, we can remove
it now.

feat: Remove native event sending

---

src/ducks/balance/NoAccount.jsx
src/ducks/categories/AddAccountButton.jsx

- buttonTheme has highlight as default value for Account
and AddAccountButton components
- Export NoAccount and AddAccountButton components

fix: Change highlight value theme to buttonTheme property

---

src/ducks/account/AccountSwitch.jsx
src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/Transactions.jsx

Two bugs with clicks in Chrome responsive are solved here.
It seems that Chrome responsive triggers click events a bit after the normal
click, leading to bugs like that. ev.preventDefault() fixes those bugs. I
would have preferred not to have this (I thought the change of structure
to remove the transaction modal from the transaction row would have sufficed)
but I do not see another solution.

Fix clicks

---

src/ducks/categories/Categories.jsx
src/ducks/categories/CategoriesHeader.jsx
src/ducks/categories/CategoriesHeader.styl
src/ducks/categories/CategoriesPage.jsx
src/ducks/future/PlannedTransactionsPage.jsx
src/ducks/recurrence/RecurrencesPage.jsx

- Display neatly the follow pages: Reccurences, Categorization and PlannedTransaction
- Simplify simple condition

fix: Display neatly some empty pages

---

src/ducks/pin/PinGuard.jsx
src/ducks/pin/PinGuard.spec.jsx
src/ducks/settings/PinSettings.jsx
src/locales/fr.json

- Change timeout to 30sec (prev: 1min)
- Show PinCode when app is restart 
- Add withClient to avoid props.client is undefined when the pin is disabled in Settings

fix: Show PinCode when app is restart and change timeout

---

src/ducks/transfers/TransferPage.jsx

In NoBank component (Transfer page}:
- addition of the nominal header and changing of text by "Transfer"
- The label (with : "Ajoutez une banque pour pouvoir effectuer
un virement") is added above "Add a bank" button
- Add of spacing between label and button

fix: Change header for transfer page when there is no bank

---

docs/dev.md

Remove yarn watch:mobile:hot (does not exist anymore)
instead use watch: mobile

fix: Remove of  command info about hot reload on app mobile

---

src/components/Title/Title.jsx
src/components/Title/Title.styl
src/components/Title/__snapshots__/Title.spec.jsx.snap
src/ducks/account/AccountSwitch.jsx

- AccountSwitch did not close after click
- All accounts was not correctly selected
Those regressions were introduced after the AccountSwitchMenu was
converted to a Dialog.
Also, convert the reimbursements page title to a Typography component,
this way it adapts to the theme automatically.

Fix: Close AccountSwitch after selection

---

src/components/Section/index.js
src/ducks/account/helpers.js
src/ducks/account/helpers.spec.js
src/ducks/balance/AccountRowCaption.jsx
test/fixtures/triggers.json

This fixes the fonctional bug where the account is shown not to have been
updated when its data has not changed. This is due to the fact that the
banking konnectors only update bank accounts when they have changed. Thus
the cozyMetadata.updatedAt attribute can be unchanged for a long time for
account without a lot of changes (savings account for example).
It could confuse users that expect to see the last synchronisation date, 
not the date where the object has been changed, in the AccountRow.
Here, the trigger last success date is used to determine the last sync date
shown in the account row. We keep the logic to take the bank account last
update date, in case the user has uninstalled the konnector. If the trigger
exists, its last success date is prioritized over the account update.

feat: Look inside the trigger for bank account update date

---

src/targets/services/konnectorAlerts.js
src/targets/services/konnectorAlerts.spec.js

Triggers are not only for konnectors and can be used for sharing / notes 
etc... If we do not scope the query, we end up with all the trigger states
inside the io.cozy.bank.settings that tracks the konnector trigger states,
where we only need the states for konnector triggers. In a given cozy, we
stored 173 trigger states, and now we only store 23.

fix: Only need to store konnector triggers for konnectorAlerts service

---

src/actions/accounts.js
src/ducks/settings/__snapshots__/helpers.spec.jsx.snap
src/ducks/settings/constants.js
src/ducks/settings/helpers.js
src/ducks/settings/helpers.spec.jsx
src/locales/en.json
src/locales/fr.json
test/fixtures/unit-tests.json

Disable notifications if they are focused on an account or group
that gets deleted.

feat: Disable notifications when corresponding account/group is deleted

---

src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx

Issue:
When all groups (from a bank) are deleted, the "Balance" page is not
refreshed with the new data and sometimes there are empty groups.
We must have fills groups with the accounts values.
Fix:
Keep realtime on allows to have an always up-to-date UI. 
Not the best for the app (see [2009](https://github.com/cozy/cozy-banks/issues/2009) issue)

fix: Keep real time active when focus on balance page

---

src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx

Revert fix: 
Didn't fix when all groups (from a bank) are deleted, the "Balance" page is not
refreshed with the new data and sometimes there are empty groups.
See: https://github.com/cozy/cozy-banks/pull/2010

fix: Revert "Merge pull request #2010 from cozy/fix-keep-realtime-on"

---

src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx

The first [PR] (https://github.com/cozy/cozy-banks/pull/2010) does not correct the problem of empty groups but keeps the interface up to date.  An [issue](https://github.com/cozy/cozy-banks/issues/2009) is open in order to optimize real time.
Empty groups remained displayed because they were not monitored and therefore not updated when the automatic group creation job was completed.
So I added GROUP_DOCTYPE in the list of doctypes to watch

fix: Empty groups after adding a bank

---

src/ducks/balance/Balance.jsx

Fetching groups when realtime is active
Related to PR [#2012](https://github.com/cozy/cozy-banks/pull/2012)

fix: Add missing groups.fetch

---

src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx

Issue:
When adding a bank after deleting all accounts
for several seconds (1 to 5 sec) the groups are empty.
With "realtime" there are multiple fetching like "accounts" and "groups"
which are called in parallel.
When we fetch groups when there are no accounts, the groups are empty.
No need to search for groups as long as there are no accounts, otherwise there are empty groups.
Fix:
When the realtime is active, we call fetch Accounts
so when there are data we can fetching the groups.

fix: Allows not to have an intermediate state

---

src/ducks/transactions/TransactionPageErrors/ReconnectTriggerButton.jsx
src/ducks/transactions/TriggerErrorCard.jsx

Can be useful for specific errors, for example when reconnecting a nestor
account

Add error proptype for ReconnectTriggerButton

---

src/main.jsx

This allows harvest to get the connection id resulting from a webauth
connection.
The connection id is then saved in the account and the webauth popup can
be closed

feat: Let harvest intercept webauth callbacks

---

src/components/AccountIcon/index.jsx
src/ducks/account/helpers.js
src/ducks/account/helpers.spec.js
src/ducks/settings/AccountsSettings.jsx

The slug for show the konnector icon was provided by the createdByApp.
In the event that the nestor konnector is used for the first time with
a Boursorama account and after we connect with the Boursorama konnector
with the same account.
So the nestor icon was always displayed instead of icon from the
last connected konnector.
In this example it will be boursorama icon.
Now Accounts and settings/accounts page show correctly icons

fix: Show correct icons in Accounts and settings page

---

src/components/AccountIcon/index.jsx
src/ducks/account/helpers.js
src/ducks/account/helpers.spec.js
src/ducks/settings/AccountsSettings.jsx

We revert because the bank accounts can be edited by apps/konnectors other than a bank connector.
We cannot trust updatedByApps.
We keep the fact of displaying an icon from the createdByApp, it is the banking konnector that
takes care of updating the createdByApp field.

Revert "Merge pull request #2018 from cozy/fix-konnector-icons"

---

src/ducks/categorization/services.js

The categorisation service did not start the
onOperationOrBillCreate on the right banks.

feat: Use the banking.banking-app-slug

---

src/targets/services/onOperationOrBillCreate.js

To properly use flags coming from the server, we need to register the flag plugin and wait for its complete initialization. Here, flags were only coming from the settings document in ad-hoc way (predating the existence of flags stored on the server / context / instance).

fix: Wait for flag initialization in onOperationOrBillCreate

---

babel.config.js
docs/services.md
package.json
src/ducks/balance/AccountsList.jsx
src/ducks/client/manifest-babel-node.js
src/ducks/groups/services.js
src/ducks/groups/services.spec.js
src/utils/getPermissions.js
test/client.js
test/jest.setup.js

In production, we have seen cases where there were duplicated accounts
in groups. Here, we add the removal of duplicate accounts in the
autogroups service.

Deduplicate accounts in autogroups service

---

src/ducks/balance/SetFilterAndRedirect.jsx
src/ducks/balance/SetFilterAndRedirect.spec.jsx
src/ducks/settings/Debug.jsx

The SetFilterAndRedirect is used when a user comes from a notification
with a `/balances/<accountId>/details` route. Its role is to set the
`filter` inside redux and then to redirect to the "normal" `/balances/details`
route.
It seems there was a typo or a bad refactor at some point since the routes
file was using a component constructor function instead of the component:
when this route was matched, a blank page was shown to the user.
- Export a component, not a component constructor
- Added tests

fix: Blank page when coming from notif to /balance/<account>/details

---

src/AppContainer.jsx
src/components/App.jsx
src/components/JobsContext.jsx
src/doctypes.js
src/ducks/balance/AccountRowLoading.jsx
src/ducks/balance/AccountRowLoading.spec.jsx
src/ducks/balance/AccountsImporting.jsx
src/ducks/balance/AccountsImporting.spec.jsx
src/ducks/balance/Balance.jsx
src/ducks/balance/Balance.spec.jsx
src/ducks/balance/GroupPanel.jsx
src/ducks/balance/ImportGroupPanel.jsx
src/ducks/balance/ImportGroupPanel.spec.jsx
src/ducks/settings/AccountsListSettings.jsx
src/ducks/settings/AccountsSettings.jsx
src/locales/en.json
src/locales/fr.json
test/AppLike.jsx

We want to view when an account import is in
progress on the balance page and in the settings
page. For that we activate the realtime on the jobs
when we are on one of these 2 pages otherwise we
stop it. We also want to display a notification to
the user whether it went correctly or not.

Better import in progress

---

src/components/JobsContext.jsx

There is a toast when we try to connect with bad credentials
on boursorama konnector.

fix: Handle message only if there is an account

---

package.json
src/ducks/transactions/FileOpener.jsx
yarn.lock

This is necessary due to a circular dep between drive and banks. With
previous drive, back arrow at the top left of the viewer does not work. So
we will use the cross button of the dialog to close it. When drive has been
published, we will set the flag to true in production so that the cross is
hidden
I am merging as soon as this is green since it is very small.

feat: Add flag to hide close button

---

src/ducks/recurrence/RecurrencePage.jsx
src/ducks/recurrence/queries.js

Due to https://github.com/cozy/cozy-client/issues/903, we have
to manually specify the index fields.

fix: Specify index fields otherwise wrong index is chosen

---

src/AppContainer.jsx
src/ducks/categories/CategoryChoice.jsx
src/ducks/search/SearchPage.jsx
src/ducks/search/SearchPage.spec.jsx
src/ducks/transactions/FileOpener.jsx
test/AppLike.jsx

Fixes small problems related to categories.
* fix: Category change is reflected in the search page
Before, we would store complete transactions in the state of the search
page. After a recategorization, the transactions were not updated in
the state of the component. Here, we store only the transaction ids
in the results and we retrieve the transactions from the "live"
transactions col that is updated when an item inside is updated.
* Sort sub categories inside category choice dialog
Subcategories were not sorted and this could lead to inconsistencies. Now subcategories are sorted alphabetically, and the "Others" category is last.
* Remove unnecessary flag
* Remove icon sprite

Categories improvements

---

package.json
src/components/App.jsx
src/components/AppRoute.jsx
src/components/__snapshots__/AppRoute.spec.jsx.snap
src/ducks/devtools/Queries.jsx
src/ducks/devtools/banksPanels.js
src/ducks/devtools/common.jsx
src/ducks/devtools/index.jsx
src/ducks/devtools/useLocalState.js
src/ducks/settings/Settings.jsx
yarn.lock

Add start of a devtool panel that could be reused across apps. It is displayed via a floating-action-button only shown if the flag('debug') is set.
- Add queries viewer that list all queries from cozy-client with their fetch status and data
- Ability to receive devtools panels from the app, this way we can move the debug page from settings to this panel

feat: Add devtools

---

src/ducks/balance/Balance.jsx

Starts setInterval loop when realtime is not started
[Issue 2047](https://github.com/cozy/cozy-banks/issues/2047)

fix: Start realtime fallback

---

src/ducks/categories/CategoriesHeader.jsx
src/ducks/future/selectors.js
src/ducks/recurrence/RecurrencePage.jsx
src/ducks/recurrence/RecurrencesPage.jsx
src/ducks/recurrence/utils.js
src/locales/en.json
src/locales/fr.json
yarn.lock

* feat: Add mention for "deprecated" bundles
Show that some bundles will not accounted for in 30-day blanace.
* feat: Add fade ins for appearing elements in categories header
This smoothens the transaction from parent page to children page

Deprecated recurrence mention

---

src/ducks/context/BanksContext.jsx
src/ducks/context/BanksContext.spec.jsx
src/ducks/context/JobsContext.spec.jsx

We check if there are items in jobsInProgress
but if there is none so we have to update with empty
value jobsInProgress
Otherwise in the user interface the last job in
progress remains displayed

Fix banks context

---

src/targets/services/onOperationOrBillCreate.js

This will fix "ReferenceError: fetch is not defined" warning message in
this service which caused no bank operation link to bills since 19
March.
cozy-client needs this polyfill to be available in globals to work
properly

fix: Add missing fetch polyfill for onOperationOrBillCreate service

---

src/ducks/transactions/actions/KonnectorAction/index.jsx

Clicking on a transaction action chip should not open the transaction
dialog. Here, actions are responsible to call ev.preventDefault() on
their click event so that the transaction row can check ev.defaultPrevented.
A common solution is to check ev.currentTarget === ev.target to filter but this
does not work properly as I want to click everywhere on the row to 
open the transaction dialog, putting the check would remove this ability
since sometimes ev.currentTarget would be a `td` and not a `tr`.
I am not super pleased with this thing, if you see another solution, please
tell me.
Depends on https://github.com/cozy/cozy-ui/pull/1798

fix: Do not open transaction dialog when clicking on chip

---

src/ducks/transactions/TransactionRow.jsx
src/ducks/transactions/actions/KonnectorAction/index.jsx

Again, a click on a modal that is displayed for a transaction action would trigger the transaction dialog. Here, we filter events that do not come from an element inside the row (like the modal and the portal).

Fix bad open of transaction dialog

---

src/actions/accounts.js
src/ducks/context/JobsContext.jsx
src/ducks/recurrence/DebugRecurrencePage.jsx
src/ducks/recurrence/RecurrencePage.jsx
src/ducks/recurrence/api.js
src/ducks/recurrence/constants.js
src/ducks/recurrence/service.js
src/ducks/recurrence/utils.js
src/ducks/transactions/TransactionRecurrenceEditor.jsx
src/ducks/transactions/actions/AttachedDocsAction/index.jsx
src/ducks/transactions/helpers.js
src/ducks/transactions/helpers.spec.js

When a transaction is set as not recurrent, we check if the recurrence
still contains transactions. If it's empty, we remove it.

Delete recurrence if there are no more transactions in it

---

src/ducks/future/useEstimatedBudget.jsx
src/ducks/recurrence/DebugRecurrencePage.jsx
src/ducks/settings/GroupSettings.jsx
src/ducks/settings/HarvestBankAccountSettings.jsx

If fetch status is pending or loading so show spinner, it avoids to try access at "attributes" which is undefined and provokes this error.
For further, I also changed several fetchStatus === 'loading' by isQueryLoading because since this [Cozy Client PR](https://github.com/cozy/cozy-client/pull/925) fetchStatus through pending and after loading.
So it is therefore preferable to use this function which checks if it is pending or loading

fix: Use isQueryLoading

---

manifest.webapp

This would trigger unwanted notifications, a paper Notifications doublées dans Banks describes in more detail the problem.

feat: Do not trigger onOperationOrBillCreate on change of category

---

src/ducks/budgetAlerts/CategoryBudgetNotificationView.js
src/ducks/budgetAlerts/service.spec.js
src/ducks/future/useEstimatedBudget.spec.jsx
src/ducks/notifications/BalanceLower/index.js
src/ducks/notifications/BalanceLower/index.spec.js
src/ducks/notifications/DelayedDebit/index.js
src/ducks/notifications/TransactionGreater/index.js
src/ducks/notifications/utils.js
test/fixtures/unit-tests.json

Amounts with a floating part should be formatted with 2 numbers after
the comma (before we could have 10.5) in the push notification
- TransactionGreater
- BalanceLower

feat: Format floating amounts with 2 numbers after comma

---

src/ducks/transactions/TransactionRow.jsx

onRef is not passed in the recurrence bundle page since it is not needed.
In those cases, TransactionRow should not try to bind the onRef function.

fix: Do not bind onRef if its not passed

---

package.json
yarn.lock

Allows you to have certain requested features, in particular :
- feat: Remove references to "cozy" in harvest locales
Makes it easier to customize and whitelabel the UI
- Show konnector error in both data and configuration tab in harvest
- Open external links in a new tab not to lose the Cozy context
BREAKING CHANGES
When using the TriggerManager outside the main Harvest Routes, you need to import { IntentTriggerManager } from 'cozy-harvest-lib', instead of `import { TriggerManager } from 'cozy-harvest-lib'.
For more information on features: 
[CHANGELOG](https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/CHANGELOG.md)

feat: Upgrade harvest

---

src/components/KonnectorUpdateInfo/index.jsx
src/components/KonnectorUpdateInfo/index.spec.jsx

fix: Add missing query string to show only pending update
Before we display all the store's bank connectors, now only those that are awaiting update

fix: Add missing query string

---

src/ducks/balance/Balance.jsx
src/ducks/categories/CategoriesPage.jsx
src/ducks/settings/Settings.jsx

in the case of override where we add a navigation
with tabs that have an animation. The user has an
impression of slowness / lag. To avoid this, we
use a delay which allows the content to be
rendered a few ms later.
By default in banks There's no delay

fix: Hack to avoid slower transition in tabs

---

src/ducks/recurrence/rules.js
src/ducks/recurrence/rules.spec.js

The recurrence service no longer worked. (Otherwise we have an error of the type: Cannot read property 'label' of undefined)
Before we filtered if there were no upstream operations then on updated the recurrences
```
const recurrences = (await fetchHydratedBundles(client)).filter(
x => x.ops.length > 0
)
findAndUpdateRecurrences(...)
```
Now we do it after, so it's necessary to check if there is at least one value in ops.
Because access to a property is impossible if the array is empty.

Fix recurrence

---

src/ducks/recurrence/rules.js
src/ducks/recurrence/rules.spec.js

In production the recurrency service we have type errors :
`TypeError: Cannot read property 'date'`
If there are no operations in either, we are not able to merge category ids so we return an empty array.

Check if obj or src has operations in recurrency service

---

package.json
src/ducks/categories/CategoriesHeader.jsx
yarn.lock

- Upgrade harvest to 6.1.1
Contains : BI Two FA naming error + unit tests
- Display issue about SelectDate component (Page Analysis -> Categorisation)

Upgrade harvest and fix display select date component

---

src/components/KonnectorUpdateInfo/index.jsx
src/components/KonnectorUpdateInfo/index.spec.jsx

We had a param duplicate`&pendingUpdate=true&pendingUpdate=true`in url
This param is include in useRedirectionURL.

fix: Duplicate pendingUpdate param

---

package.json
yarn.lock

Now in AppSections component we can pass
`displaySpecificMaintenanceStyle` to show a specific
style when the app is in maintenance.
See PR :
https://github.com/cozy/cozy-ui/pull/1829

feat: Add custom display in maintenance

---

src/AppContainer.jsx

When overriding the application there is a problem
with class duplication in production.
Consequently, during the first display,
the override style is not applied.
A solution found was to add a `productionPrefix` to avoid this issue.
This is a known problem:
Issue :
https://github.com/mui-org/material-ui/issues/11843
PR:
https://github.com/mui-org/material-ui/pull/11846

fix: Duplicate class on overrided style component

---

src/components/__snapshots__/AppRoute.spec.jsx.snap
src/doctypes.js
src/ducks/balance/Balance.jsx
src/ducks/balance/BalanceHeader.jsx
src/ducks/balance/History.jsx
src/ducks/settings/AccountsSettings.jsx
src/utils/currencySymbol.js

Part of the effort to decrease the data loaded by banks (see https://github.com/cozy/cozy-banks/issues/2101).
Here, the request for the chart showing the evolution of the account is changed : only the last year transactions are loaded and only relevant fields for the graph are fetched (account, currency) etc..

feat: Load less data for home page

---

src/ducks/recurrence/api.js
src/ducks/recurrence/api.spec.js

Previously, we'd use the default 100 limit when fetching bundle
transactions. When more than 100 transactions were linked to bundles,
some recurrences were fetched with the wrong number of transactions,
possibly 0. If a bundle was fetched with 0 transactions, it would
be deleted.
To prevent this problem, we use queryAll to fetch all documents
regardless of the pagination limit. The limitBy is increased to 1000
since we are in the context of a service, this not a problem fetch
large document batches.

fix: Use queryAll to fetch all recurrence bundle transactions

---

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap
src/ducks/brandDictionary/brands.json
src/ducks/recurrence/DebugRecurrencePage.jsx
src/ducks/recurrence/__snapshots__/search.spec.js.snap
src/ducks/recurrence/config.json
src/ducks/recurrence/fixtures2.json
src/ducks/recurrence/rules.js
src/ducks/recurrence/rules.spec.js
src/ducks/recurrence/search.js
src/ducks/recurrence/search.spec.js
src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx
src/ducks/transactions/actions/KonnectorAction/match.js
test/jestUtils.js

Add split brands rule to prevent any recurrence bundle to contain
operations from two different brands.
Since the first rule to group operations is a bit simple (amount
and categoryIds) are considered, we sometimes had cases where
operations from two different brands were mixed in the same bundle.
This would break the stats computations and the bundle was not
recognized.
Since we have a brand dictionary that already serves to detect if
an operation pertains to a particular brand, we can use this
detection mechanism to split any bundles containing operations
from more than one brand.

Improve recurrence detection

---

package.json
src/ducks/account/AccountSwitch.jsx
src/ducks/account/AccountSwitch.spec.jsx
yarn.lock

If groups have not yet been loaded, groupsCollection.data is null and
cannot be spread.

fix: Do not crash when groups have not yet been loaded

---

src/ducks/categories/Categories.jsx
src/ducks/categories/CategoriesHeader.jsx
src/ducks/categories/CategoriesPage.jsx

On mobile, the bar showing data loading was placed in the middle of the page, below the chart.
HeaderLoadingProgress is now displayed by CategoriesHeader as it was
not possible to control correctly where to display the progress bar
if it was rendered inside the categories page (since we need on mobile to
display the progress bar above the chart, whereas on desktop it needs
to be below the header).
The progress bar is also now hidden if the round spinner is displayed.
The progress bar is thus only shown if there is already some data
showing and we are loading new data.
mobile first load
mobile previous/next month load
desktop first load
desktop previous/next month load
(the progress bar is very faint here since the load happened quickly)

fix: HeaderLoadingProgress at wrong place on categories page mobile

---

src/ducks/appSuggestions/services.js
src/ducks/appSuggestions/services.spec.js
src/targets/services/helpers.js
src/targets/services/helpers.spec.js

Recently, the code was changed to use DocumentCollection.fetchChanges and
the include_docs: true option was forgotten.
Without include_docs, docs are not fetched when retrieving changes, and 
this leads to the return value of fetchChanges to have no documents. Since
notifications are sent based on changes, there were no more notifications
sent for transactionGreater/balanceLower.
See https://github.com/cozy/cozy-client/issues/966 to discuss about the
ergonomics of fetchChanges.
---
Also, a small regression was introduced recently for appSuggestions since
now we can have brands without konnectorSlug.

fix: Send transaction greater and balance lower notifications

---

src/ducks/future/PlannedTransactionsPage.jsx
src/ducks/future/selectors.js
src/ducks/future/useEstimatedBudget.spec.jsx
src/locales/en.json
src/locales/fr.json
test/fixtures/unit-tests.json

- Order planned transactions by descending date
- Add suggestion to mark operations as recurrent to improve prediction

Improve planned transactions page

---

src/ducks/settings/__snapshots__/helpers.spec.jsx.snap
src/ducks/settings/constants.js

Settings document now are all "named" with a specific id. It makes
it easier to find them and guarantees their unicity

feat: Add configuration id to io.cozy.bank.settings

---

src/ducks/transactions/TransactionModal.jsx
src/ducks/transactions/TransactionModal.spec.jsx
src/ducks/transactions/queries.js
src/ducks/transactions/queries.spec.js

* When a transaction just has been deleted, the transaction modal is still
rendered while it requests to be closed by its parent. At this point, the
transaction is no longer in the store, thus the TransactionModal should not
render anything instead of crashing.
*  When clicking on balance page top amount,
filteringDoc is an array of account ids and the query
maker for the transaction page should handle this case

Fix 2 crashes

---

src/ducks/balance/AccountRow.jsx
src/hooks/useFullyLoadedQuery.jsx
src/hooks/useFullyLoadedQuery.spec.jsx

There were no guard against multiple fetch more calls inside
useFullyLoadedQuery. This seemed to trigger infinite loops. It is
not exactly clear why but with the additional checks that were
added, the infinite loop behavior could not be reproduced.
Added checks:
- do not call fetchMore() while already running
- do not call the effect with res as dependency, only with the
the fetchStatus and hasMore

useFullyLoadedQuery infinite loop

---

src/ducks/categories/CategoriesHeader.jsx
src/ducks/categories/CategoriesHeader.styl
src/ducks/categories/CategoriesPage.jsx
src/ducks/settings/GroupSettings.jsx
src/ducks/transactions/TransactionSelectDates.jsx
src/ducks/transactions/queries.js
src/ducks/transactions/queries.spec.js

- Categories: Display Empty in desktop when no transactions in the period in categories page
- Categories: Transaction select dates min/max dates were not correct
- Categories: Take into account the filter to load categories page transactions
- Settings: Correctly display auto group labels

Fixes to categories page

---

package.json
src/ducks/context/SelectionContext.jsx
src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx
src/ducks/transactions/TransactionRow/TransactionRowMobile.jsx
src/ducks/transactions/Transactions.spec.jsx
src/ducks/transactions/Transactions.styl
src/ducks/transactions/header/TableHead.jsx
yarn.lock

On souhaite pouvoir faire une sélection de plusieurs transaction afin de les catégoriser, également sur desktop (on a déjà la feature sur mobile)

feat: Add possibility to select multiple transaction on desktop

---

src/ducks/transactions/TransactionRecurrenceEditor.jsx

NestedSelect options are keyed by the title of the option
or by the key attribute of the option. Since both
options had the same title "Salaire", we had a warning
during tests because two react keys were the same.
To remove the warning, we can set "key" as the _id of each recurrence in
in the NestedSelect options.

fix: Remove during tests warning

---

src/ducks/context/SelectionContext.jsx
src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx
src/ducks/transactions/TransactionRow/TransactionRowMobile.jsx
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.spec.jsx

Optimisation du fonctionnement du SelectionContext pour éviter des re-render intempestifs, et notamment éviter de re-render toutes les lignes de transactions à la modification d'une seule ligne.
Ajout également du fait de vider le context en sortant de la page en cours.

SelectionContext optimisations

---

src/ducks/context/SelectionContext.jsx
src/ducks/selection/SelectionBar.jsx
src/ducks/selection/helpers.js
src/ducks/transactions/Transactions.jsx
src/locales/en.json
src/locales/fr.json

On souhaite avoir un bouton dans la barre de sélection qui permet de sélectionner toutes les transactions visibles.

feat: Add select all button in selection bar

---

package.json

To speed up local git manipulations 🙏 . We still have the CI as safety net

chore: Remove post/pre push/commit hooks

---

scripts/ci/mattermost_comment.sh

MATTERMOST_CHANNEL is a JSON dump like : `{"dev":"Gangsters", "beta": "gangsters,publication", "stable": "gangsters,publication"}`
that allows to target multiple channels following the type of release.
Since MATTERMOST_CHANNEL contains a config object with channels for
each release mode (dev, beta, stable), we cannot use it here.
Since we want the message for the APK to be sent directly to the gangsters
channel, we can hardcode it.

fix: Send APK message to mattermost

---

src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx
src/ducks/transactions/TransactionRow/TransactionRowDesktop.spec.jsx
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.spec.jsx
test/fixtures/unit-tests.json

Transactions should be re-sorted after coming from the stack since we
display the realisationDate for credit cards. If transactions are sorted
"only" by date, the order of displayed transactions seems wrong since the
date that the user sees is the realisationDate. For delayed debit card
accounts, the realisation date can be at the beginning of the month whereas
the date is at the end of the month.
After the switch to incremental queries, the wrong transactions were used,
here we switch to using transactions from before, transactions that are
sorted by displayed date.
The test has to be updated to account for that since now even in the UI 
test, transactions are sorted by displayed date. Since only the top 
transactions are really displayed, we could not click on transactions that
were at …

fix: Wrong order of transactions for credit card accounts

---

src/ducks/categories/CategoriesPage.jsx
src/ducks/transactions/queries.js
src/ducks/transactions/queries.spec.js

Delayed credit card transactions happen at the very end of the month. Here
the selector, having only day and not the hour, would not pick transactions
of the last day (because 2021-01-31 < 2021-01-31T12:00, the first date
being the upper bound of the query, and the second date the date of the
transaction), and thus no transaction were visible in the categories page.
- Extracted the code for it to be more testable
- Added the hours for the query to fetch correctly transactions for the
last day

fix: Delayed credit card transactions weren't displayed in analysis page

---

src/components/SelectDates/SelectDates.spec.jsx
src/components/SelectDates/utils.js
src/components/SelectDates/utils.spec.js
src/ducks/categories/CategoriesHeader.jsx
src/ducks/transactions/TransactionSelectDates.jsx
src/hooks/useFullyLoadedQuery.jsx
src/hooks/useIsMounted.jsx
src/hooks/useSafeState.jsx

Symptom: On the categories page, if an account has only 1
transaction, the select date is broken, and the page does not
show anything.
2 problems are fixed here
1. Month range did not behave correctly and would not return any
item if both min and max were the same. This meant that the
select date did not have any option when an account had only
1 transaction and was thus unusable
2. After loading the "extent" (meaning the earliest and latest
transaction for the current filter), the transaction select
date was not updated with the current period; the options
are there so it is possible to wake up the select date by
opening it and selecting another option, but before that,
"All year" is shown in the month part of the select, and
the categories page is on the current month (right now)
which …

Fix transaction select dates for accounts with only 1 transaction

---

package.json
src/ducks/context/SelectionContext.jsx
src/ducks/selection/SelectionBar.jsx
src/ducks/selection/helpers.js
src/ducks/transactions/TransactionRow/TransactionOpener.jsx
src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx
src/ducks/transactions/TransactionRow/TransactionRowMobile.jsx
src/ducks/transactions/TransactionRow/helpers.js
src/ducks/transactions/TransactionRow/helpers.spec.js
src/ducks/transactions/TransactionRow/index.spec.jsx
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.spec.jsx
src/ducks/transactions/Transactions.styl
src/locales/en.json
src/locales/fr.json
yarn.lock

- correction : avec la lib Tappable lorsque l'on swipait vers le bas sur mobile, en prenant une ligne de transaction comme point de départ, cela avait aussi pour effet de cliquer sur la ligne et donc d'ouvrir la modale de transaction. C'est n'est plus le cas avec Hammerjs. En revanche on avait réussi à mocker Tappable pour faire un vrai test fonctionnel sur mobile, je n'ai pas réussi à faire de même avec Hammer. J'ai donc supprimé le test. On a encore le test fonctionnel sur desktop en revanche :+1:
- modification : l'activation de la SelectionBar n'est plus lié à son contenu. Elle peut donc être active sans avoir aucun élément sélectionné. C'est d'ailleurs ce qu'on souhaite faire sur mobile (pas sur desktop).
- ajout : un bouton pour déselectionner tout

Selection and mass categorisation update

---

src/components/BarSearchInput/index.jsx
src/ducks/categories/CategoriesHeader.jsx
src/ducks/transactions/TransactionSelectDates.jsx
src/ducks/transactions/TransactionSelectDates.spec.jsx
src/hooks/useTransactionExtent.jsx

onExtentLoad would be called even if there was no transactions

fix: TransactionSelectDates crashed if the account had no transaction

---

src/ducks/transactions/TransactionsPage.jsx
src/ducks/transactions/scroll/TopMost.js
src/hooks/useIntersectionObserver.jsx

- Fetch more was called in a loop because the component becuase the 
compoentn would call fetchMore, the list would be re-renderred, then
the list would see that it was at the end of the list, then would
call fetchMore etc... Normally the collection inside cozy-client should
have status="loaded" and the call to fetchMore would not happen, but
apparently it can happen.
Now the component keeps a ref on the promise returned by the fetchMore
promise so that the component cannot launch 2 fetchMore calls.
- There could be a null node in the internals of TopMost and the getBoundingClientRect
method call would crash. This is checked now.

Transaction list scroll stabilisation

---

src/ducks/categories/CategoriesHeader.jsx

It was a wrong idea to automatically set the period here since the
SelectDates changes between the category page and the subcategory page
and the period is reset. I do not know yet what could be a better fix.

fix: Period filter was reset when navigating into subcategories

---

src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx
src/ducks/transactions/TransactionRow/TransactionRowMobile.jsx

Since the Typography is done manually, we can use the disableTypography 
props otherwise the Typography wrapper twice.

feat: Do not wrap transaction row content in Typography twice

---

src/components/SelectDates/SelectDates.jsx
src/components/SelectDates/SelectDates.spec.jsx
src/ducks/categories/CategoriesHeader.jsx

available value
When the date selector receives new options, it will call its onChange prop
if the value is not available in the new options. It calls the onChange
callback with the available option that is nearest to the current value.
This algorithm was already coded but was not called when new options were
received.
When we have selected a category, we need to look if the number of 
transactions within this category is 0. Previously we would look at the
first category instead of the selected category (the first category might
have transactions)

Fixes on categories page

---

docs/data-fetching.md
src/doctypes.js
src/ducks/budgetAlerts/index.js
src/ducks/transactions/queries.js
src/ducks/transactions/queries.spec.js

We need to add _id to the selected fields otherwise Pouch does
not send it back, and this is not supported by cozy-client
I have opened on issue on cozy-client to discuss about the difference of behavior between pouch and couch, and to see if we should solve this problem at the cozy-client level https://github.com/cozy/cozy-client/issues/985.
The $or query would fail with Pouchdb, with a "no index is usable for
this query". Seems like the $or query is not well supported by Pouch.
Fortunately, the $in operator can replace the the $or here
and seems more performant. It seems that we should avoid the $or
operator for our queries to be compatible between Couch and Pouch.

fix: Mobile fixes

---

src/actions/accounts.spec.js
src/ducks/client/web.js
src/index.ejs
src/main.jsx
src/utils/cozyData.js
src/utils/lang.jsx

Utiliser `data-cozy="{{.CozyData}}"` dans le template plutôt que de lister chaque attribut manuellement :
```
data-cozy-token="{{.Token}}"
data-cozy-domain="{{.Domain}}"
data-cozy-xxx="{{.XXX}}"
...
```
Ceci afin de permettre l'utilisation des nouvelles variables injectées par la stack, sans avoir besoin de mettre l'app à jour.

feat: Replace cozy-data-* by cozy-data

---

src/components/KonnectorUpdateInfo/index.jsx
src/components/KonnectorUpdateInfo/index.spec.jsx

- Use normal theme
- Reactivate icons that used the string api to load icons
- Use the new API from infos

fix: Konnector update infos UI update

---

src/main.jsx
src/utils/lang.jsx
src/utils/lang.spec.jsx

Fix [issue #2181](https://github.com/cozy/cozy-banks/issues/2181)
In mobile version we don’t have dataset and so we
can’t parse this data.
Now we check root.data.cozy value before
to parse it.

fix: Crash on mobile version

---

docs/dev.md
test/e2e/mock-server.js

It can be useful while debugging to connect the stack to a fake
push notifications server to see push notifications that are sent (similarly
to what we do with mailhog). Previously, the mock server could only
be instantiated programmatically. Now, the mock-server.js file can be launched
through node for debugging purposes. It will print the body of each request
that it receives.

feat: Ability for push notifications mock server to be launched with node

---

CHANGELOG.md
src/ducks/transactions/Transactions.jsx
src/ducks/transactions/Transactions.spec.jsx

A la première implémentation de la feature, on ne pouvait pas simplement activer le mode Selection sans avoir de transaction sélectionnées. Il fallait sélectionner une transaction pour activer le mode. Donc le fait de vider les sélections suffisait à désactiver le mode Sélection. Ce n'est plus le cas maintenant puisque nous avons un bouton sur mobile qui permet d'activer le mode Sélection, sans pour autant sélectionner de transaction.

fix: Disables selection mode when leaving an account page

---

CHANGELOG.md
src/ducks/transactions/TransactionsPage.jsx

on tablet
**Before**
**After**

fix: First transactions are no longer trimmed on the balance page

---

CHANGELOG.md
src/ducks/categories/colors.js

Since v49.0.0 of cozy-ui we removed some css variable colors so in that case we fallback to the palette

fix: Missing colors for categories in the chart on the analysis page

---

CHANGELOG.md
src/ducks/transactions/queries.js
src/ducks/transactions/queries.spec.js

Sur la page d'analyse pour tous les comptes, `filteringDoc` est null et dans ce cas on devrait indexer les doc selon la date et l'id puisque c'est la requête que retourne le "constructeur de requête" `makeFilteredTransactionsConn`. Sauf que les selector sont forcés en dur sur la date et l'account dans la fonction d'ajout de période `addPeriodToConn`.
Ce qui déclenche une erreur sur mobile au niveau des selecteurs.
Je ne sais pas pourquoi il n'y a pas le souci sur browser, mais à la lecture du code (d'ailleurs pour les autres fonction qui ajout des infos à la définition de la requête on récupère bien les selectors de la requête initiale) et de l'erreur ce fix reste pertinent.

fix: Analysis page retrieves information when viewing all accounts

---

CHANGELOG.md
src/components/LogoutModal/LogoutModal.jsx
src/doctypes.js
src/ducks/context/BanksContext.jsx
src/ducks/pin/queries.js
src/ducks/settings/PinSettings.jsx
src/ducks/settings/PinSettings.spec.jsx
src/ducks/settings/ToggleRow.jsx

A render loop was happening since the pin doc was fetched over and over
after login. If we set a fetch policy, we no longer have a problem since
the pin will not be refetched if it has been less 30s that it has been
fetched.
Also smaller fixes/features:
- Better logout page
- No pin setting rendered if pin had not yet been saved
- Add fetch policies for other queries

fix: Prevent loop refresh due to lack of fetch policy on query

---

CHANGELOG.md
src/ducks/account/services.js
src/ducks/groups/services.js
src/ducks/groups/services.spec.js
src/ducks/settings/helpers.js

Update or create settings depend if settings has _rev prop or not
should fix autogroups and linkMyselfToAccounts services
Avant on faisait `client.collection(doctype).update(newSettings)` un qui retournait `Bad Request(400): You must either provide an _id and _rev in document (update) or neither (create with fixed id).' }` lorsque le doc `io.cozy.bank.settings.configuration` était `undefined` (donc pas encore créé). Dans ce cas là il ne faut donc pas faire une `update` mais un `create`. `client.save()` s'occupe de ça pour nous.

fix: Updating settings now create or update

---

src/ducks/recurrence/rules.spec.js
src/ducks/recurrence/search.js
src/ducks/recurrence/search.spec.js

After looking in the app and in the services. We notice that the key field is not used.
The field is now deleted

fix: Remove key field (not used)

---

CHANGELOG.md
src/ducks/recurrence/__snapshots__/search.spec.js.snap
src/ducks/recurrence/rules.js
src/ducks/recurrence/rules.spec.js

Median used Array.sort() but this way [1, 2, 120] returns [1, 120, 2]. Lodash sortBy() sorts array correctly.
fix https://github.com/cozy/cozy-banks/issues/2206

fix: Recurrence median function returns the correct number

---

CHANGELOG.md
src/ducks/transactions/TransactionRow/TransactionOpener.jsx
src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx
src/ducks/transactions/Transactions.styl

correction également sur les checkbox de sélection sur le ligne de transaction : elles ne sont plus rognées sur tablette
⚠️ cette PR est un fix sur la branche `release/1.34.0`. Une fois mergé, commit à récupérer pour master.

Transactions are no longer selectable in the projected expenses page

---

CHANGELOG.md
src/ducks/future/HeaderInfoCard.jsx
src/ducks/future/PlannedTransactionsPage.jsx
src/ducks/future/PlannedTransactionsPageHeader.jsx
src/ducks/future/styles.styl

Les block des transactions commençait sous l'en-tête
**Avant**
**Après**
⚠️ cette PR est un fix sur la branche `release/1.34.0`. Une fois mergé, commit à récupérer pour master.

Planned transactions page shows transactions correctly on tablet

---

CHANGELOG.md
package.json
src/components/MigrateAdapterDialog/MigrateAdapterDialog.jsx
src/components/MigrateAdapterDialog/index.js
src/ducks/client/index.js
src/ducks/client/links.js
src/ducks/client/linksHelpers.js
src/ducks/client/mobile/helpers.js
src/ducks/client/mobile/mobile.js
src/ducks/client/mobile/mobile.spec.js
src/ducks/client/web.js
src/ducks/mobile/MobileRouter.jsx
src/locales/en.json
src/locales/fr.json
yarn.lock

This asks the user having an old Pouch adapter (e.g. idb, cordova-sqlite)
if he wants to migrate it. We detect such need by an entry in the
localstorage set by cozy-pouch-link
Same work as we did on Drive : https://github.com/cozy/cozy-drive/pull/2399

Migrate PouchDB adapter

---

CHANGELOG.md
src/targets/services/stats.js
test/fixtures/index.js

to avoid importing the whole lib

refactor: Use deep import for lodash

---

CHANGELOG.md
src/actions/accounts.js
src/ducks/settings/GroupSettings/RemoveGroupButton.jsx
src/ducks/transactions/helpers.js
src/ducks/transactions/helpers.spec.js

Lorsqu'on supprimait un groupe sur mobile, il réapparaissait suite à la synchro pouch<->couch, à cause du fait qu'avant la suppression on envoyait une autre requête qui modifiait le groupe en question.
J'en ai profité pour corriger un bug lié à https://github.com/pouchdb/pouchdb/issues/7290

fix group delete on mobile

---

CHANGELOG.md
src/ducks/recurrence/rules.js
src/ducks/recurrence/search.js
src/ducks/recurrence/search.spec.js
src/ducks/recurrence/service.js

pour le cas `should update existing bundle and create a new one` : 
même cas sauf qu'on ne passe que 2 transactions à la place de 3 pour le nouveau bundle potentiel. On log alors l'erreur `Filter out bundles where the size is below`

feat: Add logs and jsdoc for recurrence

---

CHANGELOG.md
package.json
yarn.lock

See [PR#1908](https://github.com/cozy/cozy-ui/pull/1908)
This update reduces the size of the bundle.
Before:
After:

fix: Update Cozy UI with Sprite excluded from Icon

---

src/ducks/balance/AccountRow.styl
src/ducks/categories/CategoriesHeader.styl
src/ducks/loan/LoanProgress.jsx
src/ducks/pin/styles.styl
src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx

introduced by https://github.com/cozy/cozy-banks/pull/2221
We didn't make all the changes to the BC in v49 of cozy-ui, but since the old version of the cozy-bar was using a version prior to v49 of cozy-ui this was not a problem. Now this is not the case anymore.
⚠️ à rapatrier sur Master https://github.com/cozy/cozy-banks/pull/2240

fix: Use correct css var color for warning and success

---

CHANGELOG.md
src/ducks/balance/HistoryChart.jsx

according to https://v4.mui.com/guides/minimizing-bundle-size/#option-1
on gagne 4ko au passage
avant
après

fix: Remove Third level import from Mui

---

CHANGELOG.md
src/ducks/categorization/services.js

We had a warning during the build telling
us that the variable doesn't exist.
Let's use a variable that exist...

fix: Get the right value for local model

---

CHANGELOG.md
src/ducks/transactions/TransactionModal/TransactionLabel.jsx

fix: Always display the magnifying glass

---

CHANGELOG.md
src/ducks/search/SearchPage.jsx
src/ducks/transactions/TransactionModal/SearchForTransactionIcon.jsx

If the transaction label contained a "/" then the search did not work
since the character was not escaped.

fix: Search when clicking on the magnifying glass

---

CHANGELOG.md
config/webpack.config.plugins.js
package.json
yarn.lock

gain of 20kb for parsed size, 6kb for gzipped size

fix: Shrink lodash bundles with lodash-webpack-plugin

---

CHANGELOG.md
src/ducks/account/helpers.js
src/ducks/account/helpers.spec.js
src/ducks/balance/NoAccount.jsx

revert of https://github.com/cozy/cozy-banks/pull/1828/commits/e061e376b972e86fb6dfe3ee8ae2b3f43effc2b9
il n'y a pas de souci pour autant avec la page Empty lorsqu'il n'y a aucune data (le bloc de remboursement n'apparaît pas pour autant)

Building virtual accounts works even for empty transactions

---

docs/notifications.md
src/ducks/notifications/TransactionGreater/index.spec.js
src/ducks/notifications/helpers.js
src/ducks/notifications/helpers.spec.js

dans le cas entre 23h et 6h du matin, l'objet date utilisé pour la comparaison était muté...

Fix delayed notification system

---

package.json
yarn.lock

To get https://github.com/cozy/cozy-libs/commit/9dda46f.
To change the timeout to get BI token from createTemporaryToken job
and avoid timeout error on BI connectors.

feat: Upgrade Harvest to 6.14.4

---

CHANGELOG.md
src/ducks/transactions/queries.js
src/ducks/transactions/queries.spec.js

We made changes to optimize transaction requests(https://github.com/cozy/cozy-banks/commit/644084663e01cc69792c0f677eed4faf6016fa03).
This resulted in a functional regression, we had displayed data only on
an account-by-account. Except we want to have them first by date.
We know that we are not following our recommendations (https://docs.cozy.io/en/tutorials/data/advanced/#indexes-performances-and-design) but we consider that there are fewer accounts than operations, performance will
be slightly degraded.

fix: Query by date and account

---

CHANGELOG.md
src/targets/services/konnectorAlerts.js
src/targets/services/konnectorAlerts/createTriggerAt.js
src/targets/services/konnectorAlerts/createTriggerAt.spec.js
src/targets/services/konnectorAlerts/helpers.js
src/targets/services/konnectorAlerts/setIgnoredErrorsFlag.js
src/targets/services/service.js

- le service ne fetch plus les triggers donc ne s'arrêtera plus s'il essaye de fetcher un trigger inexistant
- on se base maintenant sur le fait d'envoyer une notif à J pour programmer les J+3 et J+7
- on vérifie seulement les triggers existants dans le futur (et non toutes dates confondues) pour vérifier qu'il y a déjà des triggers de posé ou non

Fix delayed notification

---

CHANGELOG.md
src/ducks/konnectorAlerts/notification.js
src/ducks/konnectorAlerts/notification.spec.js
src/ducks/notifications/helpers.js
src/ducks/notifications/helpers.spec.js

Comme le calcul de l'heure est basée sur l'heure locale, et que les serveurs sont en UTC, on retarde l'envoie de notif d'une heure pour coller à un créneau correct concernant la France.
amélioration possible notée ici https://github.com/cozy/cozy-banks/issues/2298

feat: Change the time for sending notifications from 6am to 5am

---

CHANGELOG.md
package.json
src/ducks/transactions/TransactionsPage.jsx

to avoid `undefined isDesktop` error when changing month

Add missing withBreakpoints in transaction page

---

CHANGELOG.md
package.json
src/selectors/index.js
yarn.lock

Depuis la home, on récupère les transactions pour les stocker dans le store. Mais si on navigue sur la page des remboursements, une nouvelle requête est faite sur les transactions et le store est mis à jour.
Dans la page des remboursements, on se base sur les transactions pour construire les groupes de remboursement. On souhaite donc se baser sur ces nouvelles transactions.
Or malgré le fait que le store soit bien mis à jour avec les nouvelles transactions, le selecteur qu'on utilisait pour construire ces groupes n'était pas ré-exécuté. Car selon la doc https://github.com/reduxjs/reselect/ `un selecteur recalcule un nouveau résultat uniquement si l'un de ses arguments change`. Dans notre cas, l'argument ne changeait pas car un `===` était utilisait sur l’argument, alors que la référence à …

Update groupedExpenses selectors when state documents updated

---

CHANGELOG.md
package.json
test/jest.setup.js
yarn.lock

En lien à https://github.com/cozy/cozy-ui/pull/2072
Il avait était décelé un souci sur Banks à l'upgrade de cozy-ui, on a donc isolé cette feature dans un PR afin de corriger les problèmes éventuels.
C'est donc un besoin purement technique (et Banks bénéficie au passage et amélio cozy-ui). Au final il se trouve qu'il n'y a pas de souci.
note sur les tests : on refuse strictement les warning dans les tests. Sauf qu'ils peuvent venir de lib externe (comme ici), on doit donc faire des exceptions...

feat: Update cozy-ui to 62.1.4 and material-ui to 4.12.3

---

CHANGELOG.md
config/webpack.config.plugins.js
manifest.webapp
src/lib/sentry.js

Suite à la migration de Sentry et le changement du remote doctype https://github.com/cozy/cozy-doctypes/pull/195
On en profite pour rajouter le tag d'instance comme sur Drive https://github.com/cozy/cozy-drive/blob/master/src/drive/lib/reporter.js#L57-L59

Change sentry url + add instance in tags context

---

manifest.webapp

We recently migrated from sentry.cozycloud.cc
to errors.cozycloud.cc. By doing so, we just
change the type of the permission and the stack
doesn't like that ATM.
Also, this change can not be done like it was
done due to the fact that mobile application is
linked to the web application. The OAuth scope
is kind dynamic based on the webapp.manifest.
So if we remove the cc.cozycloud.sentry perm,
then the current mobile app will not have this
right and will not be able to send report to
Sentry.
I know that a better fix should be to deploy
the banks mobile application, but for now we're
not able to do that.

fix: Sentry permission

---

src/ducks/reimbursements/NoReimbursedExpenses.jsx
src/ducks/reimbursements/Reimbursements.jsx
src/selectors/index.js
src/selectors/index.spec.jsx

This PR reverts the fix - but not the styles of this [commit](https://github.com/cozy/cozy-banks/commit/fe4c90cc21c3c7744350b6a99612a21a5f50b737).
Memoization is not needed anymore, since [cozy-client has been fixed](https://github.com/cozy/cozy-client/pull/1122/files).

fix(documentSelector): remove useless memoization after cozy-client fix

---

package.json
yarn.lock

To get the possibility to create a BI connection with webview
Note: this needs the activation of the harvest.bi.webview and a specific
configuration of account types.

feat: Upgrade cozy-harvest-lib to version 9.2.1

---

src/components/App.spec.jsx
src/ducks/balance/ImportGroupPanel.spec.jsx
src/ducks/context/BanksContext.spec.jsx
src/hooks/useBankingSlugs.jsx

client.queryAll returns an array in useBankingSlugs and not an object with data attribute.

fix: UseBankingSlugs konnectors query

---

CHANGELOG.md
package.json
yarn.lock

`cozy-client` as been upgraded to to `29.1.1` to retrieve fix about
broken services from cozy/cozy-client#1180

fix: Upgrade `cozy-client` to 29.1.1

---

CHANGELOG.md
package.json
yarn.lock

To get BI reconnection via webviews and custom Intent api for native apps other than the flagship app

fix: Ugrade harvest to 9.10.1

---

CHANGELOG.md
package.json
yarn.lock

To not show Popup when intentsApi parameter is given. This is a cherry-pick from the release branch

feat: Upgrade Harvest to 9.12

---

CHANGELOG.md
package.json
yarn.lock

To get harvest fixes:
- do not encode oauth url
- do not show popup when intentsApi is given

feat: Update harvest to 9.12.2

---

src/ducks/settings/HarvestBankAccountSettings.jsx

to be able to override it. Override is not possible with relative import
lié à https://github.com/cozy/cozy-banks/pull/2395

chore: Use absolute import instead of relative

---

CHANGELOG.md
src/ducks/balance/ImportGroupPanel.jsx

to prevent accessing an account not yet ready
We stop the click propagation to avoid closing the accordion when
clicking an account
lié à https://github.com/cozy/cozy-banks/pull/2400

feat: Disable account line in import group panel

---

CHANGELOG.md
src/ducks/balance/ImportGroupPanel.jsx

to prevent accessing an account not yet ready
We stop the click propagation to avoid closing the accordion when
clicking an account
PR sur master : https://github.com/cozy/cozy-banks/pull/2400

Disable account line in import group panel

---

CHANGELOG.md
package.json
src/doctypes.js
yarn.lock

Two PR are needed to remove the error message staying, after reconnection of a konnector, this one and https://github.com/cozy/cozy-libs/pull/1697 . We need to update cozy-harvest-lib also to fix the bug. => draft
The [HarvestBankAccountSettings](https://github.com/cozy/cozy-banks/blob/master/src/ducks/settings/HarvestBankAccountSettings.jsx#L253) give data to HarvestAccountModal using the [HarvestLoader](https://github.com/cozy/cozy-banks/blob/dbc8d428fbeac34bafea11213607fd565e8daed7/src/ducks/settings/HarvestBankAccountSettings.jsx#L179) .
I noticed the data "trigger" that contains `trigger.current_state.status` (knowing if errored or done) was given inside the "accountsAndTriggers" . 
I also modified AccountModal.componentDidUpdate to update the data (flowState), used by harvest lib, …

fix(account): Update trigger without fetch policy

---

CHANGELOG.md
src/ducks/transactions/TransactionPageErrors/ReconnectTriggerButton.jsx

lié à https://github.com/cozy/cozy-banks/pull/2408
on souhaite ici simplement supprimer l'icon présent dans le bouton de "reconnexion" dans le push d'erreur lorsqu'un compte est en erreur.

feat: Remove icon on ReconnectTriggerButton

---

CHANGELOG.md
package.json
yarn.lock

lié à https://github.com/cozy/cozy-banks/pull/2411
Pour bénéficier de https://github.com/cozy/cozy-libs/pull/1706 . Suite à une incompréhension on avait modifié par erreur un bouton dans harvest. Cette modif était passé dans la version 9.14 d'harvest. Le correctif fait dans harvest, il faut maintenant mettre la lib à jour ici.

Upgrade cozy-harvest-lib to 9.15.4

---

CHANGELOG.md
package.json
yarn.lock

lié à https://github.com/cozy/cozy-banks/pull/2410
Pour bénéficier de https://github.com/cozy/cozy-libs/pull/1706 . Suite à une incompréhension on avait modifié par erreur un bouton dans harvest. Cette modif était passé dans la version 9.14 d'harvest. Le correctif fait dans harvest, il faut maintenant mettre la lib à jour ici.

feat: Upgrade cozy-harvest-lib to 9.15.4

---

src/ducks/settings/HarvestBankAccountSettings.jsx

This allows any app overriding cozy-banks to customize how harvest
handle an inApp Browser

feat: Add intentsApi prop to HarvestBankAccountSettings

---

CHANGELOG.md
package.json
yarn.lock

To get :
* 9.16.0 :
* Allow EditAccountModal to have intentsApi ([43c5910](https://github.com/cozy/cozy-libs/commit/43c5910aba989fa09534cdfab8933512da606b2e))
* Now open the BI manage webview to the correct connection id ([2f3da74](https://github.com/cozy/cozy-libs/commit/2f3da74213710a06ad8877dd350bcd04b86d5e64))
* 9.17.0 :
* All oauth methods to handle reconection case ([b1a6033](https://github.com/cozy/cozy-libs/commit/b1a6033b393b1732d985807328ea83e1c87e5373))
* Do not show identifiers with bi Webviews ([58e1bb1](https://github.com/cozy/cozy-libs/commit/58e1bb16c7703590c7396c33d50c1c17ec58e512))
* 9.18.0 :
* Add error message display in OAuthForm component ([f29b3c4](https://github.com/cozy/cozy-libs/commit/f29b3c4d8357b3f58b37dfe1a50233ceddd42ff7))
* Handle user dismiss in Oauth …

feat: Upgrade Harvest to 9.18.0

---

CHANGELOG.md
docs/dev.md
package.json
yarn.lock

This makes sure `yarn fixtures` uses the globally installed version of `ACH` and not the local one that is not up to date.

Remove dev dependency to `cozy-ach`

---

CHANGELOG.md
src/ducks/recurrence/api.js
src/ducks/recurrence/api.spec.js

The recurrence service is triggered when transactions are created or
updated but the service itself updates transactions when recurrence
bundles are created or modified, thus triggering another service call.
This behavior is fine as long as it ends in a stable state where no
transactions are updated and no service calls are triggered anymore.
However, the service was updating all bundled transactions whether
they were already bundled before or not thus triggering infinite
loops.
We now only update transactions whose bundle was changed during the
current service call whether the transaction was already in a bundle
or not.

fix: Prevent recurrence service calls loop

---

CHANGELOG.md
src/targets/services/recurrence.js

We could not figure out yet why the recurrence service keeps modifying
transactions thus triggering further calls to itself.
Until we do, we'll prevent the service from running altogether.

fix: Prevent recurrence service from running

---

CHANGELOG.md
package.json
src/components/AppRoute.jsx
src/components/SearchInput.jsx
src/components/SelectInput.jsx
src/ducks/settings/TabsHeader/index.jsx
src/ducks/settings/TagListItem.jsx
src/ducks/settings/TagsList.jsx
src/ducks/settings/TagsListSettings.jsx
src/ducks/settings/TagsSettings.jsx
src/ducks/settings/index.js
src/ducks/settings/tagsSettingsHelpers.js
src/ducks/settings/tagsSettingsHelpers.spec.js
src/locales/en.json
src/locales/fr.json
yarn.lock

This PR is on top of #2426 and thus should wait for it to be merged on master.
This adds a page to see all the tags that have been created. It also implements search and sort on the tags. The "most / least common" criteria is not yet implemented and currently clicking on a tag in the list does not open any dedicated page to the tag.

Add a tab in the settings to list all the tags

---

CHANGELOG.md
src/ducks/notifications/HealthBillLinked/index.js
src/ducks/notifications/HealthBillLinked/index.spec.js
src/ducks/notifications/LateHealthReimbursement/index.js
src/ducks/notifications/LateHealthReimbursement/index.spec.js
src/ducks/notifications/TransactionGreater/index.js
src/ducks/notifications/TransactionGreater/index.spec.js
src/ducks/transactions/helpers.js
src/targets/services/onOperationOrBillCreate.js

Some notifications sent by the `onOperationOrBillCreate` service can
be sent multiple times as we're not saving anywhere the fact that
they've already been sent.
This is the case of `HealthBillLinked` notifications for example.
These are sent when a reimbursement bill is linked to a transaction
but if that transaction gets updated somehow later, then the service
will send another notification once it runs.
The `TransactionGreater` notification class had a mechanism based on
the `cozyMetadata` to save this information on the transactions
themselves so we just use it for all transaction based notifications
(i.e `HealthBillLinked`, `LateHealthReimbursement` and
`TransactionGreater`).
This will generate changes on the transactions as we're saving the
state in their metadata but now that the …

fix: Avoid notifying bill notifications twice

---

src/components/Tag/TagAddModal.jsx
src/components/Tag/TagAddModalContent.jsx
src/components/Tag/TagAddModalContentList.jsx
src/components/Tag/TagBottomSheet.jsx
src/ducks/categories/AdvancedFilterModal/AdvancedFilterModal.jsx
src/ducks/categories/AdvancedFilterModal/AdvancedFilterModal.styl
src/ducks/categories/AdvancedFilterModal/IncomeListItem.jsx
src/ducks/categories/CategoriesHeader/AdvancedFilter.jsx
src/ducks/categories/CategoriesHeader/DesktopFragment.jsx
src/ducks/categories/CategoriesHeader/MobileFragment.jsx
src/ducks/categories/CategoriesHeader/index.jsx
src/ducks/categories/CategoriesPage.jsx
src/ducks/categories/CategoriesPage/enhanceCategoriesPage.jsx
src/ducks/categories/CategoriesTags/TagAdd.jsx
src/ducks/categories/CategoriesTags/TagAddModalOrBottomSheet.jsx
src/ducks/categories/CategoriesTags/TagChip.jsx
src/ducks/categories/CategoriesTags/TagChipList.jsx
src/ducks/categories/CategoriesTags/TagListItem.jsx
src/locales/en.json
src/locales/fr.json

Ce développement permet d'afficher une modale de filtres avancées, reprenant le filtre d'affichage des revenues déjà existant et ajoute le filtre par Tags.
Etant très en retard sur les délais, la refactorisation des composants "Tags" sera fait ultérieurement.

Add advanced filters with tags

---

CHANGELOG.md
src/components/AppRoute.jsx
src/components/RouterContext.jsx
src/components/Tag/TagChip.jsx
src/components/Tag/TagDeleteTagModal.jsx
src/components/Tag/TagRenameTagModal.jsx
src/doctypes.js
src/ducks/settings/TagListItem.jsx
src/ducks/tags/TagDialog.jsx
src/ducks/tags/TagDialogContent.jsx
src/ducks/tags/TagDialogTitle.jsx
src/ducks/tags/TagPage.jsx
src/ducks/transactions/helpers.js
src/locales/en.json
src/locales/fr.json

This PR adds a new route leading to page that:
- list all the transactions linked to a given tag
- allow to rename and delete that tag
Clicking on a tag list item in the settings or on a tag chip on a transaction leads to this page.

Add a page for managing a tag

---

package.json
yarn.lock

The previous version was not compatible with Eslint 8 which is the
version we use at the moment.
This prevents linter errors in editors.

deps: Upgrade eslint_d

---

src/AppContainer.jsx
src/doctypes.js

Read each commit description:
Previously:
Now:
Only one fetch for this call

Fix(trigger-konnector): prevent multiple requests + synchronize error message on Harvest Modal

---

CHANGELOG.md
src/ducks/transactions/queries.js
src/ducks/transactions/queries.spec.js

Since the "baseQuery" can have a selector, we need to add this
selector to the indexField in order to have a performant index.
To be able to sort correctly, we need to add the selector to the
sort. So here it is.

fix: Mango request optimization

---

src/components/BarSearchInput/index.jsx

Since a894b8c913d083664327684056c716c50e903b37,
the size of the input was not the good one.
Let's use the fullwidth props to fix the issue.
(no changelog update since the refacto was not added)

fix: Search Input Size

---

CHANGELOG.md
src/ducks/settings/AccountsSettings.jsx
src/ducks/settings/AccountsSettings.spec.jsx

This allows to show the resulting account in settings screen after
account creation

fix: Add realtime on accounts in settings screen

---

CHANGELOG.md
package.json
yarn.lock

Harvest to 9.22.2 to get :
* fix: Do not use biBankId from cache
* feat: Allow disabled banks to be clickable
* fix: Add BI bankIds to createTemporaryToken params
Cozy-client to 32.2.6 to get :
* fix temporary token cache when beginning with an empty cache [PR](https://github.com/cozy/cozy-client/pull/1198)

feat: Upgrade Harvest and CozyClient

---

src/components/Tag/TagAddNewTagModal.jsx

Problème : *Il est possible de créer un label vide*
L'Input étant un champ "non controlé", `trim` les la saisie utilisateur suffit à solutionner le problème

fix: Recipe 1.45.0 beta.6

---

CHANGELOG.md
package.json
yarn.lock

Since https://github.com/cozy/create-cozy-app/commit/fa07a257c90e4b359097b56761d929755b4b5f17
we duplicate the generated CSS. It's bad since we load twice the
same CSS, so in fact we load at least 4 CSS files for Banks.
These CSS are pretty heavy, so let's revert to only get the ones
we really need without duplication.
We'll fix the issue in cozy-scripts later.

fix: Duplicate CSS

---

CHANGELOG.md
src/index.ejs

There is no manifest.json at the moment,
so let's remove the call.
We should certainly add it one day.

fix: Remove 404 call to manifest.json

---

src/components/Tag/TagAddNewTagModal.jsx
src/components/Tag/TagAddNewTagModal.spec.jsx

~~The `maxLength` property is not supported on Android.
This problem is probably caused by the predictive text feature.~~
It's better to make the field controlled
and adapt the previous fix on spaces (0b7cfc9)

fix: The label entry must be limited directly

---

CHANGELOG.md
src/components/SearchInput.jsx
src/components/SelectInput.jsx
src/components/Tag/TagAddModalOrBottomSheet.jsx
src/components/Tag/TagAddNewTagModal.jsx
src/components/Tag/TagAddNewTagModal.spec.jsx
src/components/Tag/TagChip.jsx
src/components/Tag/TagDeleteTagModal.jsx
src/components/Tag/TagRenameTagModal.jsx
src/ducks/categories/AdvancedFilterModal/AdvancedFilterModal.jsx
src/ducks/categories/CategoriesTags/TagAddModalOrBottomSheet.jsx
src/ducks/settings/TagsSettings.jsx
src/ducks/tags/TagPage.jsx

This PR adds logs for some navigation and interaction events related to tags.
This does not include the batch event bindings which will only be part of the override.
The easiest way to test the changes is adding some `console.log()` calls in the `trackerShim` in `tracker.js`.

Add event and page loggers

---

src/ducks/settings/AccountsListSettings.jsx

Or else, this will display a meaningless overlay for such items

fix: Make in progress item in setting not clickable

---

src/ducks/settings/AccountsListSettings.jsx

This case may happen when accounts have been created via a webhook's
payload and the connector has not been run yet to fetch the identifier
In this case, the account identifier is just not displayed
```
* Handle account without ".auth.identifier" attribute without error
```

fix: Handle account without ".auth.identifier" attribute without error

---

package.json
yarn.lock

with an upgrade of Harvest
To open InAppBrowser properly when clicking "reconnect" button in error
message
```
* Harvest 9.26.13 : Add missing intentsApi property
```

fix: Add missing intentsApi property

---

src/ducks/transactions/TransactionModal/DeleteTransactionRow.jsx

```
* Since `tags` are behind a flag, it can appears that we don't have the `tags` relationships at all. Let's be defensive about that case in order to not throw an error. Fix an error when the user can not open a specific transaction 
```

fix: Check if we get relationships or not before maping

---

src/ducks/notifications/BalanceGreater/index.js

to help debugging
no changelog, it's not a feat relative to previous version of banks

feat: Add logs when BalanceGreater notif service find account to notify

---

src/ducks/future/selectors.js
src/ducks/future/selectors.spec.js
src/ducks/recurrence/Bundles.jsx
src/ducks/recurrence/RecurrencesPage.jsx
src/locales/en.json
src/locales/fr.json

Instead of always showing every recurrence bundle in the recurrence tab, this hides deprecated (a.k.a. inactive or marked as finished) ones by default.
They can still be revealed by pressing a "Show inactive recurrences" button.
```
* Hide deprecated recurrence bundles behind a new "Show inactive recurrences" button
```

Hide deprecated recurrence bundles behind a button

---

src/ducks/notifications/services.js

This is a fix for #2493 which is not yet in beta so the changelog is omitted.
Amounts used to be hidden even with the setting disabled.
Basically the variable `amountCensoring` was an object and not a boolean and thus was always truthy.

Correctly retrieve the setting that hides amounts in notifications

---

package.json
yarn.lock

This notably fixes an error that occurred when attempting to rename a recurrence (fixed in 75.0.1).
```
* Upgrade cozy-ui from 74.6.1 to 75.4.0
```

feat: Update `cozy-ui` to 75.4.0

---

src/ducks/transactions/queries.js

The request was wrong when selecting "All accounts", so the user doesn't have any data inside the date picker.
This commit fix this issue with a no pleasant way.
Big hack. We worked to optimize this query see
commit 2bb11660ec40c683898673b3270c763404552cd8
But by doing so, we had an issue where when selecting "all accounts", the result was not right. This is because we indexed by _id first and then date.
So the current fix is :
- If we have a selector on an account, then the index should be indexed by account first and then we ensure that we have the date within the index
- If we don't have a slector on an account, then the index should be indexed first by the date and then by the selector
@todo: We should really split all this query creation to several methods. We can't have optimized …

fix: Categories date picker

---

src/components/SelectDates/SelectDates.jsx

Apparently when the `SelectDates` component updates with "All year" checked, the bare year stored in the Redux store is passed as is (without the `-allyear` suffix) to the component. So this PR makes the component handle such values.
This avoids rerendering with the wrong month when navigating from a category to a subcategory while "All year" is checked.
```
* Make `SelectDates` accept values without months
```

Make `SelectDates` accept values without months

---

src/components/Tag/TagAddModalOrBottomSheet.jsx
src/ducks/transactions/helpers.js

We could not add one or more tags to a transaction, and at the same time delete one or more tags already present.
The transaction was not up to date(_rev) for the second operation
In addition to fetching the latest version of the transaction, it needs to be hydrated so that it has the `tags`(hasManyTags) property
```
* Add and remove tags at the same time on a transaction
```

fix: Add and remove tags at the same time

---

src/ducks/balance/Balance.jsx
src/ducks/balance/BalanceWithBanksJobs.jsx
src/ducks/balance/index.js
src/ducks/context/BanksContext.jsx
src/ducks/context/BanksContext.spec.jsx
src/ducks/context/JobsContext.jsx
src/ducks/context/JobsContext.spec.jsx
src/ducks/settings/AccountsListSettings.jsx
src/ducks/settings/WaitJobQueue.js

Wait jobs allow harvest to tell to banks it is waiting for a job to be
triggered by a BI webhook.
This wait job will displayed like a real job in progress but will be
replaced and removed by the real job with the same slug or after 5
minutes.
Harvest can trigger this wait jobs by sending a realtime notify on
io.cozy.jobs with the slug of the expected job.
Since these wait jobs are triggered before any account or trigger
creation, they don't have any associated account and will be replaced by
any job with the same expected slug

feat: Add wait jobs

---

package.json
yarn.lock

To fix issue within the flagship app since
AppLinker now requires the app props.
It was causing a blank block since we had
error "can not read slug from undefined a.slug"
```
* Fix blank block within the flagship app for the cozy-bar
```

fix: Upgrade cozy-bar

---

package.json
yarn.lock

This property allows to pass custom Properties to OAuthForm wrapper
without unmounting/remounting OAuthForm on each rerender
This avoids the disparition of the BI webview in banks when a new job is
expected
See https://github.com/cozy/cozy-libs/commit/c2461a312fd75dff29452fc99ac968d40e040c83
```
* New OAuthWrapperCompProps in TriggerManager
```

feat: Upgrade Harvest to get OAuthWrapperCompProps in TriggerManager

---

src/components/App.jsx
src/components/App.spec.jsx
src/ducks/categories/CategoriesPage/enhanceCategoriesPage.jsx
src/ducks/context/SelectedTagsContext.jsx

This stores the selected tags in a context, and provide them in the parent route of category pages.
This allows to persist the selection when navigating between category pages, while clearing it when exiting this group of pages.
```
* Preserve selected tags when navigating in categories
```

Preserve selected tags when navigating in categories

---

CHANGELOG.md
src/ducks/transactions/queries.js
src/targets/services/konnectorAlerts/createTriggerAt.js
src/targets/services/konnectorAlerts/createTriggerAt.spec.js
src/targets/services/konnectorAlerts/helpers.js
src/targets/services/konnectorAlerts/helpers.spec.js
src/targets/services/konnectorAlerts/sendTriggerNotifications.spec.js
src/targets/services/konnectorAlerts/shouldNotify.js
src/targets/services/konnectorAlerts/shouldNotify.spec.js

Cherry pick de https://github.com/cozy/cozy-banks/pull/2516 pour faire un patch de la version stable 1.46.0
**Auto mergé dès que CI verte**
```
* Don't notify users about very old konnector run failures (i.e. older than 7 days and 15 minutes which is the maximum delay between the last failure and the scheduled 7 days reminder).
* Prevent scheduling `konnectorAlerts` triggers in the past which would be executed right away by `cozy-stack` ending up sending multiple notifications to the user about the failed konnector run.
```

[1.46.1] fix: Prevent excessive konnector alerts notifications

---

src/ducks/account/AccountSwitch.jsx

The transactions from the virtual accounts were already included in the transaction list on the balance details page when checked on the balance page, but the total count displayed on the account selector was taking into account only the real accounts.
This fixes this mismatch by making the counter also include virtual accounts.
Virtual accounts still can't be directly selected in the selector menu and can only be accessed from the balance page.
```
* Include virtual accounts in the account total count in balance details
```

Include virtual accounts in the account total count in balance details

---

src/ducks/categories/AdvancedFilterModal/AdvancedFilterModal.jsx

It used to be logged for both.
```
* Log event only when hiding incomes and not when unhiding them
```

fix: Log event only when hiding incomes and not when unhiding them

---

CHANGELOG.md
package.json
yarn.lock

To have BI manage webview back + handle the removal of BI connection from the BI manage webview.
```
- Use BI manage webview back
- Close Harvest dialog if the BI connection has been removed in the BI webview
*
*
*
```

feat: Upgrade Harvest to 9.29.0

---

src/ducks/account/AccountSwitch.jsx
src/ducks/filters/index.js

This reverts #2524 to solve the inconsistency the other way: instead of fixing the total count, this fixes the count of selected accounts by ignoring virtual accounts. This is the length of `filteredAccounts` and not the one of `filteringDoc` in the case.
The count still may need to be fixed at other places: at the top of the balance page for example.
```
* Reverts "Include virtual accounts in the account total count in balance details"
* Exclude virtual accounts from the account count in balance details
* Do not show any account when none is selected in balance details
```

Exclude virtual accounts from balance details

---

src/AppContainer.jsx

This realtime is needed to have an account to display as disconnected
when it is removed by cozy-stack after a CONNECTION_DELETED bi webhook
when the user removes the connection from the BI manage webview
```
*
* Update cozy accounts when removed from cozy-stack after BI connection removal from BI webview
*
```

fix: Add realtime on io.cozy.account

---

src/ducks/context/JobsContext.jsx
src/ducks/context/JobsContext.spec.jsx

At the moment, banks display an import success toast when any bank job
related to a banking connector successed.
Since it is now possible to have multiple konnector job successes for
the creation of one connection ore even on the deletetion of a
connection, we need to filter out some jobs.
Here are the rules to consider a job :
- The job is not a webhook (still possible run manually by the user)
- The job is a webhook of type CONNECTION_SYNCED
ACCOUNT_ENABLED, ACCOUNT_DISABLED and CONNECTION_DELETED jobs are
ignored for the detection of running jobs and for the display of success
or error toasts
```
* Do not display success or error toast for webhooks other than CONNECTION_SYNCED
```

feat: Ignore some webhooks for some events

---

src/ducks/account/AccountSwitch.jsx
src/ducks/account/helpers.js
src/ducks/account/helpers.spec.js
src/ducks/balance/AccountRow.jsx
src/ducks/notifications/CategoryBudget/index.js
src/ducks/notifications/DelayedDebit/index.js
src/ducks/reimbursements/ReimbursementsPage.jsx
src/ducks/settings/CategoryAlerts/AccountGroupChoice.jsx
src/ducks/settings/DelayedDebitAlert.jsx
src/ducks/settings/DelayedDebitAlertRules.jsx
src/ducks/settings/helpers.js
src/ducks/transactions/TransactionModal/TransactionModalInfoContent.jsx
src/ducks/transactions/TransactionRow/AccountCaption.jsx
src/locales/en.json
src/locales/fr.json
test/e2e/alerts-existing-cozy.js

This should improve the navigation by:
- adding the virtual accounts to the account switch
- adding the account switch to virtual accounts and virtual groups
This way, the user can go from any account to another without having to go back to the balance page.
```
* Add the virtual reimbursement accounts to the account switch
* Add the account switch to the reimbursement page
```

Add virtual accounts to the account switch

---

package.json
yarn.lock

To get a fixed locale on popin after BI connection removal from BI webview
https://github.com/cozy/cozy-libs/commit/ed2f352467da5f36ef1753de5578f156bb2a1ffb
```
* Upgrade harvest to 9.29.1: Wrong locale on BI connection removal https://github.com/cozy/cozy-libs/commit/ed2f352467da5f36ef1753de5578f156bb2a1ffb
```

feat: Upgrade Harvest to 9.29.1

---

package.json
yarn.lock

To get a proper display of BI connection deletion popup and with account
status update
```
* Update account connection status after BI connection deletion in BI webview
```

feat: Upgrade cozy-harvest-lib to 9.29.4

---

src/AppContainer.jsx

This causes rendering issues on Harvest at the moment.
Another [temporary fix](https://github.com/cozy/cozy-libs/pull/1878) has been
found to update account from harvest waiting for a better fix which will
make OAuthWindow in harvest independent from Harvest components tree.
```
* Remove realtime on accounts
```

fix: Remove realtime on accounts

---

src/ducks/categories/CategoriesHeader/MobileFragment.jsx
src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx
src/ducks/transactions/TransactionRow/TransactionRowMobile.jsx
src/ducks/transactions/header/TableHead.jsx

#2526 removed the `banks.tags.enabled` flag, effectively enabling tags everywhere.
However, it also introduced some regression in environnements that have the `banks.transaction-actions.deactivated` flag set to `true`, where tags in transaction lists were completely hidden.
This PR makes sure the behavior is the same as it used to be before #2526, when the `banks.tags.enabled` flag was set to `true`.
```
* Always show the action column since tags are always enabled
```

Always show the action column since tags are always enabled

---

package.json
yarn.lock

To allow contract synchronisation to work with
https://github.com/cozy/cozy-libs/commit/3715fe70aa334fb10fc0fc40bf9633d24e7ddfd7
```
* Handles accounts created after bi webhooks on contract synchronization
```

feat: Upgrade Harvest to version 9.29.5

---

src/targets/services/service.js

Banks' services can be called by the outside world and mainly by the banking konnector.
We had an issue with our override when the banking konnector was calling the categorization service (by creating the associated job) and then this categorization service called the `onOperationOrBillCreate` by creating by itself the associated job:
https://github.com/cozy/cozy-banks/blob/3412c9389584e6c1b8120feb644fb459e42171ac/src/targets/services/categorization.js#L60
`startService` was creating the job by reading the value of the flag: https://github.com/cozy/cozy-banks/blob/3412c9389584e6c1b8120feb644fb459e42171ac/src/ducks/categorization/services.js#L124-L130
But since when the `categorization` service is called it doesn't init the flag, we call startService, flag is empty and then it fallbacks to …

fix: RunService will always wait for flag to be initialized

---

src/targets/services/konnectorAlerts.js
src/targets/services/recurrence.js

Since https://github.com/cozy/cozy-banks/commit/643ece93c383d5050ee245fb37ce9abad5e3d254 , runService init
cozy-flags.
But we can only init a cozy-client plugin once. So we have to remove
other place where the flags were initialize when not passing by
runService().
I don't konw why konnectorAlerts does a check on require.main & node_env,
but I have created the opposed check in order to be sure.
It should fix the errors we had:
> The service catched an error: Error: Cannot register plugin flags.
A plugin with the same name has already been registered.

fix: Don't register the flag plugin twice

---

package.json
src/AppContainer.jsx
src/ducks/context/JobsContext.jsx
yarn.lock

Harvest is also upgraded to support the update of the current account
even when it is displaying a popup or an InAppBrowser- feat: Activate realtime on cozy accounts
```
* Add realtime update of cozy accounts
* Harvest upgrade to 9.30.1 : 
* Add independent confirm dialog
* Use independant OAuth window
* Better locale for delete BI connection confirmation button
```

feat: Activate realtime on cozy accounts

---

package.json
yarn.lock

To :
- Prevent createTemporaryToken to updateCache twice at the same time
- Follow current trigger jobs even after the first load
```
* Follow current trigger jobs even after the first load
* Prevent createTemporaryToken to updateCache twice at the same time
```

feat: Upgrade cozy-harvest-lib to 9.31.0

---

src/ducks/notifications/HealthBillLinked/index.js
src/ducks/notifications/HealthBillLinked/index.spec.js
src/ducks/notifications/LateHealthReimbursement/index.js
src/ducks/notifications/LateHealthReimbursement/index.spec.js
src/ducks/notifications/TransactionGreater/index.js

Use cozy-client's `saveAll` instead as it is up-to-date and will
cleanup data before sending it to cozy-stack.
This avoids having CouchDB errors because documents have attributes
starting with an underscore (`_type` in this case).
```
* Use `CozyClient.saveAll()` instead of `Document.updateAll()` from deprecated `cozy-doctypes` to avoid CouchDB errors with attributes starting with an underscore (#2547)
* Add more logs around LateHealthReimbursement onSuccess method (#2547)
```

fix: Stop using cozy-doctypes' Document.updateAll

---

package.json
yarn.lock

To get the sendNotification method, needed by harvest
```
* upgrade cozy-realtime to 4.2.9 to get the sendNotification method
```

feat: Upgrade cozy-realtime to 4.2.9

---

package.json
yarn.lock

To get the konnector slug in the trigger passed to onLoginSuccess. This allow b2c
app to send a proper notification with konnector slug
```
* Add konnector slug in fake trigger passed to onLoginSuccess
```

feat: Upgrade cozy-harvest-lib to 9.31.1

---

src/AppContainer.jsx

This is an (untested) fix following #2545, that should make sure Bank disconnect dialogs match Cozy UI theme (and also its override variation).
```
* Swap providers to make some Harvest dialogs match the theme
```

fix: Swap providers to make some Harvest dialogs match the theme

---

package.json
yarn.lock

```
* Upgrade cozy-harvest-lib to 9.32.1 :
* Use OAuthService in KonnectorAccountTabs
* Use OAuthService in OAuthForm
* Update wording for Bank disconnect dialog close button
```

Upgrade cozy-harvest-lib to 9.32.1

---

src/ducks/recurrence/api.js
src/ducks/recurrence/api.spec.js
src/targets/services/konnectorAlerts/createTriggerAt.js
src/targets/services/konnectorAlerts/createTriggerAt.spec.js
src/targets/services/konnectorAlerts/helpers.js
src/targets/services/konnectorAlerts/helpers.spec.js
src/targets/services/konnectorAlerts/sendTriggerNotifications.spec.js
src/targets/services/konnectorAlerts/shouldNotify.js
src/targets/services/konnectorAlerts/shouldNotify.spec.js
src/targets/services/recurrence.js

```
* Don't notify users about very old konnector run failures (i.e. older than 7 days and 15 minutes which is the maximum delay between the last failure and the scheduled 7 days reminder). (#2516)
* Prevent scheduling `konnectorAlerts` triggers in the past which would be executed right away by `cozy-stack` ending up sending multiple notifications to the user about the failed konnector run. (#2516)
* Prevent service call loops by only updating transactions for which we've updated the associated recurrence. (#2429)
* Run recurrence service only if flag is set (#2451)
```

Backport notifications fixes to v1.42.1

---

package.json
yarn.lock

To stop unsubscribing on all realtime events
```
* Do not unsubscribe all realtime events
```

fix: Upgrade cozy-harvest-lib to 9.32.4

---

src/ducks/context/JobsContext.jsx
src/ducks/context/JobsContext.spec.jsx

When a konnector job is successful, we display an "Import success"
message.
We do not want to display this "Import success" message for job
triggered when an account (io.cozy.account) is deleted and for job
triggered by "ACCOUNT_DISABLED" webhooks.
```
* Ignore account delete and account disabled jobs for import success message
```

feat: Ignore account delete and account disabled jobs

---

src/ducks/context/JobsContext.jsx
src/ducks/context/JobsContext.spec.jsx

When detecting the end of the CONNECTION_SYNCED banking connector job,
use an updated jobsInProgress reference to decide if there is still a
job in progress to display.
We use the same hack as already used here https://github.com/cozy/cozy-banks/blob/58d1a6a0438db16addeed2d8ccca6d642545b56d/src/ducks/context/JobsContext.jsx#L65-L67
because the state doesn't have the right value, but the ref yes. 
```
* Remove import in progress in the end of the connector job
```

fix: Remove import in progress in the end of the connector job

---

src/ducks/konnectorAlerts/notification.js
src/targets/services/konnectorAlerts.js
src/targets/services/konnectorAlerts/createTriggerAt.js
src/targets/services/konnectorAlerts/sendTriggerNotifications.js
src/targets/services/konnectorAlerts/sendTriggerNotifications.spec.js
src/targets/services/konnectorAlerts/setIgnoredErrorsFlag.js

Car on souhaite avoir ces logs même si l'instance n'est pas en debug
branche 1.42.1
```
* Force log for konnectorAlerts service even if instance is not in debug mode
```

Use warn log instead of info for konnectorAlerts service

---

manifest.webapp
src/ducks/konnectorAlerts/notification.js
src/targets/mobile/config.xml
src/targets/services/konnectorAlerts.js
src/targets/services/konnectorAlerts/createTriggerAt.js
src/targets/services/konnectorAlerts/sendTriggerNotifications.js
src/targets/services/konnectorAlerts/sendTriggerNotifications.spec.js
src/targets/services/konnectorAlerts/setIgnoredErrorsFlag.js

because of too many logs
```
* Use info log instead of warn for konnectorAlerts service. Sending notification log are still warning
```

Use info log instead of warn for konnectorAlerts service

---

src/ducks/konnectorAlerts/notification.js
src/targets/services/konnectorAlerts.js
src/targets/services/konnectorAlerts/createTriggerAt.js
src/targets/services/konnectorAlerts/sendTriggerNotifications.js
src/targets/services/konnectorAlerts/sendTriggerNotifications.spec.js
src/targets/services/konnectorAlerts/setIgnoredErrorsFlag.js

because of too many logs. Sending notification log are still warning
réucpération de la branche 1.48.1, voir https://github.com/cozy/cozy-banks/pull/2580

chore: Use info log instead of warn for konnectorAlerts service

---

src/ducks/balance/Balance.jsx

```
* Exclude virtual accounts from the counter on the balance page
```

Exclude virtual accounts from the counter on the balance page

---

src/index.ejs

cozy-bar v7 assets were still imported in production mode. It became visible with recent cozy-bar releases where CSS was really different between v7 and v8.
```
* Fix bad display of settings menu
```

feat: Remove cozy-bar v7 assets

---

package.json
src/index.ejs

cozy-client-js is not used anymore in cozy-banks.
```
* Remove cozy-client-js assets
```

feat: Remove cozy-client-js assets

---

src/ducks/analysis/AnalysisTabs.jsx
src/ducks/settings/TabsHeader/index.jsx

This backports #2596.
```
* Use absolute links for analysis tabs
```

Backport "Use absolute links for analysis tabs"

---

src/ducks/balance/AccountsImporting.spec.jsx
src/ducks/balance/BalancePanels.jsx
src/ducks/settings/AccountsSettings.jsx
src/ducks/settings/AccountsSettings.spec.jsx
src/ducks/settings/AddAccountLink.jsx

Lorsqu'on avait un connecteur bancaire qui nécessitait une mise à jour, les liens de redirection d'ajout de connecteur bancaire filtrait la page du store sur les connecteurs à mettre à jour.
On force maintenant en dur l'url avec un utilisation classique de AppLinker.
```
* When a connector needs to be updated, it no longer impacts the add bank connector buttons.
```

Modify AddAccountLink to force using a specific route of Store

---

src/ducks/notifications/CategoryBudget/index.js
src/ducks/notifications/DelayedDebit/index.js
src/ducks/notifications/HealthBillLinked/index.js
src/ducks/notifications/LateHealthReimbursement/index.js
src/ducks/notifications/TransactionGreater/index.js
src/targets/services/helpers/helpers.js
src/targets/services/helpers/helpers.spec.js

```
* LateHealthReimbursement service tried to sent notification even if no match
* global FetchChangesOrAll method on services wasn't using proper data from cozy-client
* Add better log for services
```

fix services helper and LateHealthReimbursement service

---

package.json
yarn.lock

This increase height for the support modal into cozy-bar to match the add of consent checkbox
```
* Increase support modal height to handle adding consent checkbox
```

feat: Update cozy-bar from 8.13.0 to 8.13.1

---

package.json
yarn.lock

The goal of the update is to have the contact page link on settings rather than open a modal
```
* Update cozy-bar from 8.13.1 to 8.14.0
```

feat: Update cozy-bar from 8.13.1 to 8.14.0

---

src/ducks/recurrence/search-with-existing-recurrence.spec.js
src/ducks/recurrence/search.js
src/ducks/recurrence/service.js
src/ducks/recurrence/utils.js

The recurrence service is built in such a way that each call modifying
transactions will trigger another service call to make sure all
transaction-recurrence associations that could be made have been made.
This can result in a long chain of calls, potentially infinite, if
transactions are modified on each run.
We try to limit this effect by not modifying transactions that are
already associated with a recurrence. This should prevent situations
were the service juggles between 2 recurrences with a given transaction.
The fix has the added benefit of not modifying associations that were
made by the user and to present a stable automatic association.
```
* The recurrence service should not modify transactions already associated with a recurrence
* Clarified recurrence service functions and …
```

fix: Prevent extraneous recurrence service calls

---

src/ducks/devtools/Notifications.jsx

Banks devtool is one of our simpliest way to try notifications. I added three properties used by the flagship app to redirect to an app instead of the home after opening the notification to try this new feature.
```
* Add devtools notification content for flagship redirection
```

feat: Add devtools notification content for flagship redirection

---

src/ducks/export/services.js
src/ducks/export/services.spec.js
src/ducks/settings/helpers.js
src/targets/services/export.js

The `export` service fetches all transactions with their associated
relationships and transforms them into CSV lines following our own
schema.
It also transforms accounts without transactions into CSV lines
following the same schema.
The result is uploaded as a CSV file into the user's root directory.
To do so Banks now requires a permission to create and update
`io.cozy.files` documents.
The CSV is generated by the `@fast-csv` library which offers an easy
to use interface with a streamable transformation (although we don't
stream the content to cozy-stack yet as we end up with `EPIPE` errors
when cozy-stack responds with a 409 status response).
The exported accounts without transactions can be found at the top of
the file so they can easily be removed by the user if they want to
process …

feat: Allow exporting transactions/accounts as CSV

---

package.json
src/ducks/export/helpers.js
src/ducks/export/helpers.spec.js
yarn.lock

The query used by cozy-stack to fetch queued and in-progress jobs is
sub-optimal and can timeout when there are lots of jobs.
We by-pass this route and use a mango query with a partial filter to
improve performances and avoid timeouts.
```
* Improve performances of in-progress export jobs lookup
```

perf: Optimize lookup of in-progress export jobs

---

src/components/AppRoute.jsx
src/components/AppRoute.spec.jsx
src/components/__snapshots__/AppRoute.spec.jsx.snap

The best approach for this new method is the following, because we don't want to access the original routes and we want to be able to render a component on a url that could conflict with original routes
First implementation: https://github.com/cozy/cozy-banks/pull/2618/commits/9fe4166fc0f5919a9fbb0d6a49e8a08fa2e5280e

feat: Rework renderExtraRoutesWithoutLayout method

---

package.json
renovate.json
src/ducks/account/services.spec.js
src/ducks/budgetAlerts/service.spec.js
src/ducks/filters/index.spec.js
src/ducks/groups/services.spec.js
src/ducks/settings/CategoryAlerts/CategoryAlertCard.spec.jsx
src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.spec.jsx
src/ducks/settings/helpers.spec.jsx
src/ducks/transactions/TransactionModal/TransactionModal.spec.jsx
src/ducks/transactions/helpers.spec.js
src/targets/services/helpers/helpers.spec.js
test/client.js
yarn.lock

`cozy-stack-client` comes with `cozy-client` and declaring a direct
dependency to it means we need to keep it up-to-date with
`cozy-client`.
Removing this dependency simplifies `cozy-client` upgrades.
To this end, we need to remove all direct usage of `cozy-stack-client`
so we replace our own `createClientWithData` with `createMockClient`
from `cozy-client` as they serve the same purpose.
We take the opportunity to bump `cozy-pouch-link` to keep it up-to-date
and remove outdated versions of `cozy-client` and `cozy-stack-client`
from the bundle.
This should also fix an issue in the export page which requires 
`cozy-stack-client` v35.6.0.
```
* The export page can now request queued and running export service jobs
* Remove direct dependency to `cozy-stack-client`
* Bump `cozy-stack-client` …
```

deps: Remove cozy-stack-client dependency

---

src/ducks/export/services.js
src/ducks/export/services.spec.js

The vendor account ID will be used during the import to reconciliate
accounts while the loan attributes are just data we need to export for
users to have a copy.
```
* Vendor account IDs are exported for every account
* Loan attributes are exported for these accounts
* Transactions value dates are exported as short strings (i.e. `YYYY-MM-DD`)
```

feat: Export loan attributes and vendor account ID

---

src/ducks/export/helpers.js

Backport of #2627 
We have 2 issues with the current in-progress export jobs query:
- not setting the indexed fields ourselves is not compatible with the 
use of an `$or` operator (see 
https://github.com/cozy/cozy-client/issues/1270)
- the index is not created if there are too many jobs in the db
Luckily these can be fixed by using the `indexFields()` and `sortBy()` 
method of `cozy-client`'s `QueryDefinition` object.
See the commits messages for more details.
```
* Create proper, optimized query for in-progress export jobs
```

 fix: Create proper in-progress export jobs query

---

manifest.webapp
src/ducks/import/helpers.js
src/ducks/import/queries.js
src/ducks/import/services.js
src/ducks/settings/AccountsListSettings.jsx
src/services/cli.js
src/targets/services/import.js

This service, invoked programmatically with a `fileId` field, will
fetch the `fileId` file from the Cozy, parse it according to our CSV
schema and import the transactions, accounts, tags and recurrences it
contains.
Accounts without transactions won't be imported though as they're of
questionnable use (they're stale data).
If the Cozy already contains banking data, we'll try our best to
reconciliate the existing and new data to avoid duplicates and
recreate missing relationships.
We use `cozy-doctypes`' `BankAccount` and `BankTransaction`
reconciliation algorithms to make any debbuging easier but we had to
come up with our own reconciliation algorithms for tags and
recurrences (they're really simple though).
```
* Add CSV import service
* Allow grouping bank accounts by institution labels …
```

feat: Add CSV import service

---

src/locales/fr.json

```
* Wording on Export page
```

fix: Wording export title

---

src/ducks/import/services.js

In the import service, we need to index accounts (imported and
existing) so we can associate them with transactions.
We used the account number as key but saved accounts numbers are
normalized by `cozy-doctype`'s `BankAccount.reconciliate()` function
and are not necessarily equal to the originally imported number.
To prevent these differences and make sure accounts are found in the
index, we'll use the normalized form from the very beginning.
```
* Import accounts with a normalized number
```

fix: Import accounts with a normalized number

---

src/ducks/export/helpers.js

The in-progress jobs query for the export feature relies on the
presence of a very specific index to be fast on cozies with a lot of
`io.cozy.jobs` documents.
To make sure the index presence detection goes well, we forced a sort
on the `worker` attribute.
However, since `cozy-stack` uses an index on `worker` and `state`
only, CouchDB fallbacks to this index instead of detecting the index
we want does not exist and runs the slow `$or` query in-memory.
See https://github.com/apache/couchdb/issues/4511 for more details on
this issue.
To prevent this fallback we will sort on a second attribute not present
in the existing `cozy-stack` index: `message.slug`.
```
* Prevent fallback on sub-optimal index for in-progress jobs query.
```

fix: Prevent fallback to existing jobs index

---

src/ducks/import/queries.js
src/ducks/import/services.js
src/locales/fr.json
src/targets/services/import.js

We want to tell the user how many transactions were imported upon
success so they can verify everything they wanted to import was
actually imported (n.b. not importing any transaction is not
considered as a service failure since no errors were raised).
Since the service cannot communicate with the GUI via its
`io.cozy.jobs` document, we'll save this count into the
`io.cozy.bank.settings` document.
```
* Save imported transactions count in `io.cozy.bank.settings` document
* Fix typo in French import success title
```

feat: Save imported transactions count

---

src/ducks/notifications/BalanceGreater/template.hbs

```
* Email notification for balance greater wasn't using the right title
```

fix: Email notification for balance greater wasn't using the right title

---

src/ducks/settings/Import/ImportContents/ImportContentSuccess.jsx

If there are no imported operations, the message must be displayed with the 0

fix: Import success modal

---

src/targets/services/onOperationOrBillCreate.js

The Cozy credentials of a webapp service should remain as secret as
possible, even in ours logs.
The Cozy URL and the job id are already part of the log attributes and
as such, unnecessary.
```
* Remove logs with unnecessary or sensitive data
```

fix: Remove logs with sensitive data

---

src/ducks/transactions/TransactionRow/TransactionOpener.jsx

use firefox in mobile mode to reproduce the behavior
Le souci était qu'au clic sur la transaction, pour certains devices, la modale d'info de la transaction se refermait instantanément. On simplifie le code ici et on supprime simplement le comportement Tap pour utiliser le onClick.
```
* Transaction modale closed by itself on some mobile devices
```

fix: Transaction modale closed by itself on some mobile devices

---

src/ducks/brandDictionary/brandsReducer.js
src/ducks/brandDictionary/brandsReducer.spec.js

```
* We need to check the `latest_version` attribute to know if there is a stable version or not.
Before the fix, we created app suggestion even for beta or dev konnectors.
```

fix: Do not create AppSuggestion for non stable konnector

---

src/targets/services/onOperationOrBillCreateHelpers.js

We catch the error, but don't throw them after that. Resulting that services were considered OK...
```
*
* Make the services failed if they... failed.
*
```

fix: Throw error when there is an error catch

---

docs/services.md

```
* Update services documentation after cozy-scripts migration
```

docs: Update services documentation after cozy-scripts migration

---

src/ducks/billsMatching/Linker/Linker.js
src/ducks/billsMatching/Linker/Linker.spec.js
src/ducks/billsMatching/Linker/billsToOperation/helpers.js
src/ducks/billsMatching/Linker/billsToOperation/helpers.spec.js
src/ducks/billsMatching/Linker/billsToOperation/index.js
src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.js
src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.spec.js
src/ducks/billsMatching/matchFromBills.js
src/ducks/billsMatching/matchFromTransactions.js
src/targets/services/onOperationOrBillCreate.js
src/targets/services/onOperationOrBillCreateHelpers.js

This service no longer worked since the work on `brands`, the cause coming from the call to the `getBrands` function called in `getBillRegexp`.
We now pass the `brands` to him via his arguments.
This is a fix to get the service back up and running while waiting for a better approach.
```
* Fix crash of onOperationOrBillCreate service due to `window`
```

fix: Crash of onOperationOrBillCreate service due to `window`

---

src/targets/services/onOperationOrBillCreate.js
src/targets/services/onOperationOrBillCreateHelpers.js

Now, each errors are thrown... So if there is no database because there is no bills for instance, the service was crashing.
So I took this commit https://github.com/cozy/cozy-banks/commit/7a8a8a33ad353a59d88334076d54bcf9cf80be6c and test if the error is because there is no database before throwing.

VER-180 : fix: Don't crash service if there is no database

---

package.json
src/ducks/transactions/actions/AppLinkAction.jsx
src/ducks/transactions/actions/HealthLinkAction.jsx
src/ducks/transactions/actions/KonnectorAction/index.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusAction.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusModal.jsx
src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusModal.spec.jsx
src/ducks/transactions/actions/UrlLinkAction.jsx
yarn.lock

```
* Show chip action instead transaction action
* Update cozy-ui from 101.2.0 to 103.1.0
```
The action chips are integrated into a ListItem in mobile. When the chip is clicked, the parent modal is shown to the user. This commit avoids this problem by stopping propagation at the chip  level.
**Related PRs:**
- https://github.com/cozy/cozy-ui/pull/2568

[VO-201] fix: Stop event propagation on action chip

---

CODEOWNERS
src/ducks/transactions/TransactionPageErrors/TransactionPageErrors.jsx
src/ducks/transactions/TransactionPageErrors/TransactionPageErrors.spec.jsx
src/hooks/useBankingSlugs.jsx

```
* Show konnector error on transaction list
```
`isBankTrigger` didn't have the `bankingSlug` when it was run with the HOC. As the function with `bankingSlug` is also exposed via a context, so I chose this way. There's also the advantage of having one less request because you don't have to execute the hook several times.

[VO-400] fix: Show konnector error on transaction list

---

config/webpack.target.services.js

The package `mjml` can not be minimized to fix `Element mj-head doesn't exist or is not registered ...` error
when sending a notification at runtime after a build (cf: https://github.com/cozy/cozy-libs/commit/dd7bbf4af452b51b4287cb145e48b0cba2280daf) 
```
* Build configuration to be able to send notifications into a service
```

fix: Build configuration to be able to send notifications into a service

---

src/ducks/categorization/services.js

In order to avoid warning
```
*
*
* Don't log any warning when launching the `categorization ` service (aka remove `Second argument of bulkSave is now an object, please use bulkSave(documents, { logProgress, concurrency })` lokg) 
```

fix: Use the right API

---

src/ducks/transactions/queries.js
src/ducks/transactions/queries.spec.js

https://forum.cozy.io/t/impossible-de-remonter-jusquau-bout-de-lhistorique-doperations-dans-analyse-apres-import-ach/7547/2
description incoming.

fix: Fix query

---

src/targets/browser/index.ejs

Our custom theme CSS was not taken into account because cozy-ui CSS was inserted after.
```
* Custom theme colors were not taken into account
```

fix: Move custom theme CSS at end of <head>

---

src/ducks/notifications/HealthBillLinked/index.js
src/ducks/notifications/HealthBillLinked/index.spec.js
src/ducks/notifications/LateHealthReimbursement/index.js
src/ducks/notifications/TransactionGreater/index.js
src/targets/services/categorization.js

* fixes a small typo `sucessfuly` -> `successfully`

chore: fix "sucessfuly" typo
