package.json, src/ducks/categorization/index.js, yarn.lock
The author of the classificator lib merged my PR and released a new version. I use it so our code is cleaner.
=> feat: use latest version of classificator in categorization service

src/selectors/index.js
I messed up with my ACH import/export and it made me think it was good. But after checking on grrecette, I realized it was not... Sorry.
=> fix: really filter undefined virtual account

package.json, src/documents/transaction.js, src/ducks/flash/index.js, src/ducks/transactions/FileOpener.jsx, src/ducks/transactions/TransactionActions.jsx, src/ducks/transactions/TransactionActions.spec.jsx, src/ducks/transactions/__snapshots__/TransactionActions.spec.jsx.snap, src/ducks/transactions/actions/BillAction.jsx, src/ducks/transactions/actions/HealthExpenseStatusAction.jsx, src/utils/documentCache.js, test/fixtures/operations.json, yarn.lock
=> test: add tests for call to actions

manifest.webapp, package.json, src/ducks/transactions/TransactionActionMenu.jsx, src/ducks/transactions/TransactionActions.jsx, src/ducks/transactions/TransactionActions.styl, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/Transactions.styl, src/ducks/transactions/actions/ActionLink.jsx, src/ducks/transactions/actions/AppLinkAction.jsx, src/ducks/transactions/actions/BillAction.jsx, src/ducks/transactions/actions/HealthExpenseAction.jsx, src/ducks/transactions/actions/HealthExpenseStatusAction.jsx, src/ducks/transactions/actions/HealthLinkAction.jsx, src/ducks/transactions/actions/KonnectorAction.jsx, src/ducks/transactions/actions/UrlLinkAction.jsx, yarn.lock
Waiting for https://github.com/cozy/cozy-ui/pull/437 to be merged and new version of cozy-ui to be released. Then I'll fix the conflicts.
=> feat: use new action buttons on mobile

package.json, src/ducks/categories/CategoryIcon.jsx, src/ducks/transactions/TransactionActions.jsx, src/ducks/transactions/TransactionActions.styl, src/ducks/transactions/TransactionMenu.jsx, src/ducks/transactions/Transactions.styl, src/ducks/transactions/actions/AlertAction.jsx, src/ducks/transactions/actions/AppLinkAction.jsx, src/ducks/transactions/actions/AttachAction.jsx, src/ducks/transactions/actions/BillAction.jsx, src/ducks/transactions/actions/CommentAction.jsx, src/ducks/transactions/actions/HealthExpenseStatusAction.jsx, src/ducks/transactions/actions/HealthLinkAction.jsx, src/ducks/transactions/actions/KonnectorAction.jsx, src/ducks/transactions/actions/UrlLinkAction.jsx, yarn.lock
There were some problems on actions on mobile (wrong button type in the modal mostly).
I also fixed some little things after Joel's design review (transaction row padding, category icon size).
=> fix: actions are more robust

package.json
We don't use standard anymore :)
=> chore: remove standard config in package.json

src/components/AppRoute.jsx, src/ducks/balance/Balance.jsx, src/ducks/categories/Categories.jsx, src/ducks/onboarding/Onboarding.jsx, src/ducks/transactions/actions/BillAction.jsx, src/utils/flag.js
- Demo features are conditionned on `flag('demo')`
+ Vente privée modale
+ Go directly to transactions page
- stephaniedurand and isabelledurand automatically get demo flag
=> ✨ feat: add demo features under flags

docs/dev.md, manifest.webapp, package.json, src/targets/mobile/config.xml
Changes:
f571ace7 (Patrick Browne, 30 seconds ago)
📚 doc: add doc for mobile publishing
5497ebc8 (Patrick Browne, 77 minutes ago)
🔧 chore: keep the build android folder
171b2575 (Patrick Browne, 5 hours ago)
🔧 chore: bump versions
=> mobile publishing improvements

src/components/App.jsx
Merging directly since it breaks the app.
=> fix: react-hint@3.0.0 had breaking changes

package.json, src/ducks/filters/SelectDates.jsx, src/ducks/filters/SelectDates.styl, yarn.lock
There's no shadow on the bottom side for the moment because Joël wants it to be deployed everywhere at the same time.
=> feat(dates filter): new style on mobile

src/ducks/transactions/TransactionModal.jsx
in iOS the button was not correctly rendered
=> 🐝 fix: put CloseButton in the header

src/ducks/transactions/TransactionsPage.jsx
When selecting a date past the most ancient operation, we have to search in the opposite direction.
=> feat: repair select dates when going far away

src/ducks/categories/CategoriesHeader.styl, src/ducks/transactions/TransactionsPage.jsx
* No jumping around when switching transaction page / category page
* Show full year in date selector when showing transactions of a category
=> Small fixes

src/components/Figure/Figure.jsx, src/ducks/account/AccountSwitch.jsx
Some props were failing, this fixes it.
=> fix: fix failing prop types

src/ducks/transactions/InfiniteScroll.jsx
Use `touchmove` event handler `onScroll`.
=> 🐝 fix: scroll handling on ios

scripts/publish.js
Attendons peut être avant de merger
=> fix: publish on dev registry 🙄

.travis.yml, README.md, scripts/deploy-on-cozy
Dans cette PR il y a:
- Réorganisation dans le script travis, on pousse la version sur le registry puis on deploie sur les cozy de test
- J'ai supprimé la partie déploiement du build sur Github
=> fix: Continuous delivery 🛸

config/webpack.config.analyze.js, config/webpack.vars.js, package.json, webpack.config.js, yarn.lock
It can be handy to analyze quickly our bundles
=> ✨ feat: allow to analyze a bundle with webpack-bundle-analyzer

src/components/AccountSharingStatus/AccountSharingStatus.jsx, src/ducks/account/AccountSwitch.jsx, src/ducks/categories/Categories.jsx, src/ducks/categories/CategoriesChart.jsx, src/ducks/categories/CategoriesPage.jsx, src/ducks/categories/Chart.jsx, src/ducks/settings/AccountSettings.jsx, src/ducks/settings/AccountsSettings.jsx, src/ducks/settings/GroupSettings.jsx, src/ducks/settings/GroupsSettings.jsx, src/ducks/settings/Notifications.jsx, src/ducks/transactions/TransactionActions.jsx, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/scroll/InfiniteScroll.jsx, src/utils/backSwipe.js
* `render(props, state)` -> `render () { props = this.props; state = this.state }`
* return null
=> feat: add react compatability

src/ducks/transactions/TransactionModal.jsx
=> Revert "🐝 fix: need to use helper to print institution label to remove secure key part"

package.json, src/ducks/transactions/FileOpener.jsx, yarn.lock
Set width to xxlarge and height to 90vh (via cozy-ui update)
=> Update intent opener size

src/ducks/notifications/html/templates/style.css
=> fix(notifications): separate mail footer links

scripts/upload-static-files.js
When I renamed `files.cozycloud.cc` to `static-files.txt` I forgot to update the path in the script...
=> chore: fix static files upload

package.json, src/components/Select/index.jsx, src/components/Select/styleUtils.js, src/components/Select/styleUtils.spec.js, src/components/SelectDates/SelectDates.jsx, yarn.lock
Before, the area to the left of selects was not clickable.
Had to do some function-fu to merge style objects.
=> fix: increase further the click area

src/locales/en.json, src/locales/fr.json
Fix informative modal translations
=> Fixes informative modal

src/ducks/brandDictionary/brands.json
Pour un meilleur rapprochement entre les marques et les opérations.
=> feat: Update brands regexp 💅

package.json, src/styles/main.styl
- Suppression des valeurs css qui n'ont plus d'utilité et qui rende l'écran d'accueil tout blanc.
- Intallation des pods sous mac
=> Improvement

src/ducks/transactions/Transactions.jsx, src/ducks/transactions/Transactions.styl
Fix transaction table alignments
Before
After
=> Alignment tweaks

package.json, src/components/UserActionRequired/index.jsx, src/components/UserActionRequired/styles.styl, src/ducks/authentication/MobileRouter.jsx, src/ducks/onboarding/ensureIsFirstSynced.js, src/locales/en.json, src/locales/fr.json, yarn.lock
Show a blocking modal that inform the user about a TOS update and ask him/her to read and approve it before continuing his/her adventures in the mobile app.
This modal is shown when the stack is blocking all requests with a 402 error.
=> User action required

src/doctypes.js, src/ducks/authentication/lib/client.js, src/ducks/balance/Balance.jsx, src/ducks/categories/CategoriesPage.jsx, src/ducks/mobile/index.js, src/ducks/mobile/push.js, src/ducks/onboarding/ensureIsFirstSynced.js, src/ducks/settings/Notifications.jsx, src/ducks/settings/index.js, src/utils/client.js
On a 3 façons différentes pour activer les push:
- [lors de l'initialisation](https://github.com/cozy/cozy-banks/pull/288/files#diff-05c90ee3c3a1a8d4973ada444d68c5c1R60)
- [lors d'un changement sur l'interface web et que Pouch rapatrie le changement](https://github.com/cozy/cozy-banks/pull/288/files#diff-bbc287eafd55b40c9b3d44b08d20efdaR52)
- [lors d'un changement dans les settings](https://github.com/cozy/cozy-banks/pull/288/files#diff-6b1a58c949aa39b33365af09e5938e1aR48)
=> Push permission

docs/demo.md
Add docs about our needs for demo instances (fake successful connectors)
=> docs: add doc about fake success connectors

src/ducks/categorization/services.js
The classificator lib fails if we try to categorize something without make the classifier learn something.
So, if there are no manually categorized transactions on the Cozy, we skip the local model.
=> feat: Apply local model only if possible

src/ducks/categorization/services.js
Previously, if there was a problem with the global model, then the categorization would just exit, without applying the local model. Since the models are not correlated, we can apply the local one if the global one fails, and vice versa.
=> fix: Better categorization failure management

src/ducks/categorization/services.js
Debugging the service was a mess. I splitted the main function into two: one for each model (global/local).
I also added some logs and add a pattern in front of them to be able to find them more easily.
=> refactor(categorization service): split function and add logs

src/components/Chart/LineChart.jsx, src/components/Chart/LineChart.md, src/ducks/balance/History.jsx, src/ducks/balance/History.md
This is fairly simple for now. We can do more sophisticated things later.
=> Chart enter animation

package.json, yarn.lock
add Cozy commit convention on each commit
you can find more documentation on [guidelines][guidlines] or on
[commitlint-config-cozy][commitlint-config-cozy] repository.
[guidlines]: https://github.com/cozy/cozy-guidelines#commit-messages
[commitlint-config-cozy]: https://github.com/cozy/cozy-libs/tree/master/packages/commitlint-config
=> chore: Add cozy commit convention 📏

src/ducks/categories/CategoriesChart.jsx, src/ducks/categories/CategoriesChart.styl, src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoriesPage.jsx
you can find commentaire on each commit.
This is a result screenshot:
=> Donut improvements

src/ducks/settings/Configuration.jsx, src/ducks/settings/TogglePane.jsx, src/locales/en.json, src/locales/fr.json
I add header part on `TogglePane.jsx` to add a description on notifications.
You can see the result:
=> feat: Add description on notifications 💬

src/components/Chart/LineChart.jsx, src/components/Chart/LineChart.styl, src/ducks/balance/Balance.jsx, src/ducks/balance/History.jsx, src/ducks/balance/History.styl
This adds some interaction on the line chart : 
As you can see, it lacks some things:
* The tooltip doesn't properly align when it reaches the edges of its container
* The little triangle is commented out in CSS file. Actually it also need some calculation to align properly when the tooltip reaches the edges of its container
* It doesn't animate on mount, so it's visible before the line and other elements
Feel free to edit this PR directly to add missing features :pray:
=> Chart interation

src/ducks/authentication/MobileRouter.jsx, src/ducks/authentication/lib/client.js, src/ducks/client/index.js, src/ducks/client/mobile.js, src/ducks/client/web.js
Dans cette PR il y a plusieurs choses:
- Suppression de code mort
- Ajout des intents coté mobile
- Suppression du resetClient que je vais remettre dans une prochaine PR
=> Amélioration pour le mobile

src/doctypes.js, src/ducks/account/AccountSwitch.jsx, src/ducks/balance/Balance.jsx, src/ducks/groups/helpers.js, src/ducks/groups/helpers.spec.js, src/ducks/settings/GroupSettings.jsx, src/selectors/index.js, src/utils/client.js
Virtual groups were not shown anymore after we refactored the code to use the new cozy-client. This fixes it.
=> Show virtual groups

package.json, src/doctypes.js, src/ducks/transactions/FileOpener.jsx, src/ducks/transactions/TransactionsPage.jsx, test/client.js, yarn.lock
* update stack-client not to have the limit
* add bills to requests for reimbursements to be correctly linked
=> feat: fix bills

src/ducks/settings/AccountSettings.jsx, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transactions/actions/KonnectorAction.jsx, src/locales/en.json, src/locales/fr.json
Il y a 2 modifications dans cette PR:
- pour l'affichage du lien vers les connecteurs lorsque la Home est installée
- pour la modification du lien et du nom lors de la suppression d'un compte
=> Add Cozy Home link

package.json, src/ducks/transactions/TransactionModal.jsx, src/locales/en.json, src/locales/fr.json, src/targets/mobile/config.xml, yarn.lock
Add complete label in transaction modal (behind originalBankLabel flag).
=> Complete label

src/doctypes.js, src/ducks/mobile/MobileRouter.jsx
- Ajout des factures en offline pour permettre l'affichage de la page sans la connexion
- Mise à jour du level d'un log
=>  feat: Add bills doctype offline

src/ducks/transactions/TransactionHeader.jsx, src/ducks/transactions/TransactionsPage.jsx
J'ai créé un composant spécifique pour le header de la page `TransactionHeader` qui lui est chargé même si les requetes à la base ne sont pas encore finis
=> feat: Display Transaction Header quickly 🛸

manifest.webapp, src/ducks/mobile/utils.js, src/index.ejs
Used by the bar to get the `Cozy` prefix
=> Use name_prefix Cozy

config/webpack.target.services.js, package.json, src/ducks/notifications/html/README.md, src/ducks/notifications/html/templates/index.js, src/ducks/notifications/html/testTemplates.js, yarn.lock
When developing on HTML templates, it can be helpful to generate a specific
template with custom data to see that everything looks good.
=> Easier workflow for emails

src/ducks/notifications/html/templates/cozy-layout.hbs
~~Couldn't test it fully, but it looked quite well on [MJML Live editor](https://mjml.io/try-it-live/Hyt80Hi5X).~~
Looks gooood. 
- Footer links are now centered on mobile
- Header columns switch direction from row to column on mobile
=> fix: Mobile notification mail

src/index.ejs
See https://www.w3.org/TR/appmanifest/#obtaining
=> fix: Send cookies when fetching manifest.json

src/ducks/transactions/Transactions.jsx, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transactions/actions/index.js, src/ducks/transactions/scroll/InfiniteScroll.jsx
Trying to decrease memory usage.
=> Perf memory

config/webpack.target.services.js, docs/categorization.md, manifest.webapp, src/targets/services/onOperationOrBillCreate.js
This way it's in sync with its trigger
=> feat(service): Rename to onOperationOrBillCreate

src/ducks/mobile/utils.js
You can merge it only after cozy-bar is update with this PR
https://github.com/cozy/cozy-bar/pull/321
=> refactor: Remove unnecessary code

src/ducks/transactions/TransactionHeader.jsx, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/TransactionsPage.jsx
We messed with the DOM structure, breaking the infinite scroll. I didn't find precisely when. I remember we did some refactoring on the balance history chart someday, but can't find the PR. And I didn't want to lose too many time looking for it. If you think it's important to find it, I can do more research.
=> fix: Infinite scroll

src/ducks/categories/CategoriesPage.jsx, src/ducks/mobile/push.js, src/ducks/settings/TogglePane.jsx, src/ducks/settings/__snapshots__/helpers.spec.js.snap, src/ducks/settings/constants.js, src/ducks/settings/helpers.js, src/ducks/settings/helpers.spec.js, src/ducks/settings/index.js, src/ducks/settings/services.js
Mettre par défaut l'alerte de mouvement >600€ et l'activer par défaut.
Mettre par défaut l'alerte de remboursement de santé.
=> Change default notif settings

config/webpack.config.base.js, config/webpack.config.cozy-ui.js, config/webpack.config.dev.js, config/webpack.config.hot-reload.js, config/webpack.config.preact.js, config/webpack.config.styles.js, config/webpack.vars.js, package.json, src/ducks/transactions/TransactionModal.spec.jsx, src/ducks/transactions/TransactionsPage.jsx, src/main.jsx, src/utils/react-exposer.js, webpack.config.js, yarn.lock
Remove Preact and small refactor/cleanup of webpack configs.
=> Remove preact

src/ducks/transactions/TransactionHeader.jsx
=> fix: Wrong alignment of header

docs/tracking.md
Documentation about the events we track via Matomo
=> docs: Add tracking events

src/components/List/List.styl, src/components/List/index.jsx, src/ducks/categories/withUpdateCategory.jsx, src/ducks/transactions/TransactionRow.jsx, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/Transactions.spec.jsx, src/ducks/transactions/Transactions.styl, src/ducks/transactions/scroll/InfiniteScroll.jsx, src/ducks/transactions/scroll/TopMost.js, src/ducks/transactions/scroll/index.js, src/styles/utilities.styl
Split the transactions page
Do not use a table in mobile
Use a list component (to export to cozy-ui)
=> refactor: Split the transactions page

package.json, yarn.lock
Fixes undefined context on login
=> fix(deps): Update cozy-authentication to v1.4.0-beta1

src/ducks/account/AccountSwitch.jsx, src/ducks/account/AccountSwitch.styl
=> feat: Use Portal to display AccountSwithMenu

package.json, src/ducks/balance/Balance.jsx, yarn.lock
=> fix: Warning that prevents me from seeing correctly the real mistakes

src/components/App.jsx, src/components/Spacing/Padded.jsx, src/components/Spacing/Padded.spec.jsx, src/components/Spacing/Padded.styl, src/components/Spacing/__snapshots__/Padded.spec.jsx.snap, src/components/Spacing/index.js, src/ducks/balance/Balance.jsx, src/ducks/balance/Balance.styl, src/ducks/categories/CategoriesPage.jsx, src/ducks/settings/GroupSettings.jsx, src/ducks/settings/Settings.jsx, src/ducks/transactions/TransactionsPage.jsx, src/styles/main.styl
Remove default padding on cozy-ui Content, it's used to not add negative margin after.
=> feat: Use ResponsiveContent on layout

src/ducks/onboarding/Onboarding.jsx, src/ducks/settings/GroupSettings.jsx
- label for button
- Unused code
=> feat: Improv

docs/dev.md, test/fixtures/matching-service/README.md
Just because it was not documented :)
=> docs: Add matching service fixtures docs

src/ducks/categorization/services.js, src/ducks/categorization/services.spec.js
* Update model parameters so it works better
* Move the appending of a fake transaction (it was not done at the right moment)
* Refactor to make the `localModel` function more readable
* Remove useless tests and add real interesting tests for `localModel`
=> Fixes on local categorization model

package.json, yarn.lock
This fixes the logout while offline issue on the mobile app.
=> fix: Update cozy-client to v4.14.0

src/ducks/brandDictionary/brands.json
As resqueted, for fixing buttons appearance on some konnectors
=> fix: Remove brands for dictionnary for konnectors in maintenance

package.json, yarn.lock
It fixes the issues with environement detection (node vs browser)
=> fix: Update cozy-flags to v1.3.4

src/components/Header/Header.styl, src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoriesHeader.styl, src/ducks/categories/CategoriesPage.jsx, src/ducks/categories/CategoriesPage.styl
The design of the category is different that we are on mobile or desktop, so we return a specific structure for mobile.
before | After
-------|------
=> Fix Category header

package.json, yarn.lock
We are testing the latest cozy-bar on our mobile app to help the backformers. This is not ready to merge yet.
=> fix: Update cozy-bar to v6.8.7

package.json, src/components/Chart/LineChart.jsx, src/ducks/balance/Balance.jsx, src/ducks/balance/Balance.styl, src/ducks/balance/History.jsx, src/ducks/balance/History.styl, src/ducks/balance/HistoryChart.jsx, yarn.lock
On desktop the graph is always on 100% width.
before | after
-------|-----
=> Graph width

src/doctypes.js, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/Transactions.styl
The scroll was in `<div role='main'>` not `js-scrolling-element`
=> Infinite scrolling

src/actions/accounts.js, src/components/App.jsx, src/components/BackButton/style.styl, src/ducks/settings/AccountSettings.jsx, src/ducks/settings/AccountsSettings.jsx, src/ducks/settings/GroupSettings.jsx, src/ducks/settings/GroupsSettings.jsx, src/ducks/settings/TogglePane.jsx, src/locales/en.json, src/locales/fr.json
This PR fixes group and account deletion, and also fixes some prop types and DOM nesting issue in the settings part of the app.
=> Fix group and account deletion

src/components/BackButton/style.styl, src/ducks/settings/AccountSettings.jsx, src/ducks/settings/GroupSettings.jsx
This reverts commit e000acae3ce6c9825651574517cd977db38f4b65.
=> Revert "fix(BackButton): Alignment on AccountSettings and GroupSettings titles"

src/ducks/transactions/TransactionSelectDates.jsx, src/ducks/transactions/TransactionsPage.jsx
I use directly `isCollectionLoading` to watch transaction update
=> Fix setting month

package.json, yarn.lock
This version of the bar fixes the issue with apps icons on mobile that was present in `6.9.3`.
=> fix: Update cozy-bar to v6.9.5

src/ducks/categorization/services.js, src/ducks/categorization/services.spec.js
chore: Removed learning weights
fix: Update alpha computation and tests
test: Updated tests to fit the uniform prior option
=> feat: Use uniform prior in local categorization

src/ducks/settings/TogglePane.styl, src/ducks/settings/ToggleRow.styl
| Before | After |
|--------|-------|
|![image](https://user-images.githubusercontent.com/1606068/50210333-20a1a700-0376-11e9-95bf-83faabb39b5d.png)|![image](https://user-images.githubusercontent.com/1606068/50210285-010a7e80-0376-11e9-853c-c928780cbf9a.png)|
=> Fix margins in configuration settings

src/components/Breadcrumb/index.jsx, src/components/Breadcrumb/style.styl, src/components/Table/index.jsx, src/components/Table/styles.styl, src/ducks/categories/Categories.jsx, src/ducks/categories/CategoriesChart.jsx, src/ducks/categories/CategoriesChart.styl, src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoriesHeader.styl, src/ducks/categories/CategoriesPage.jsx, src/ducks/transactions/TransactionHeader.jsx, src/ducks/transactions/TransactionsPage.styl
You can test this feature on https://testbanksstylecategories-banks.cozy.works
=> Add new style in Categories pages

src/components/ExpansionPanel/ExpansionPanel.js
Hope you can see it on your screen. On my poor calibrated screen, I couldn't.
=> feat(ExpansionPanel): Add shadow

src/components/ExpansionPanel/ExpansionPanelSummary.js
=> feat(ExpansionPanelSummary): Arrow is in the right direction

src/ducks/balance/BalancePanels.jsx, src/locales/en.json, src/locales/fr.json
We used the same translations as the old page actions but we actually wanted "Add a bank" and "Manage my accounts"
=> feat(BalancePanels): Update actions translations

src/ducks/notifications/BalanceLower.js, src/ducks/notifications/TransactionGreater.js, src/ducks/notifications/helpers.js, src/ducks/notifications/helpers.spec.js, src/ducks/notifications/services.js, src/ducks/notifications/services.spec.js
I test it with cozyToDeploy after lunch: https://testbanksfixnotification-banks.cozy.works/#/settings
=> fix(Notification): Config value can be null, so we disable it

src/ducks/onboarding/Onboarding.jsx
env | Before | After
--|-------|------
mobile | ![capture d ecran 2019-01-17 a 08 21 39](https://user-images.githubusercontent.com/1135513/51301880-f56fad80-1a30-11e9-9e92-f01720ccdc45.png) | ![capture d ecran 2019-01-17 a 08 16 51](https://user-images.githubusercontent.com/1135513/51301760-a1fd5f80-1a30-11e9-8768-0d771518850e.png) | 
desktop | ![capture d ecran 2019-01-17 a 08 21 21](https://user-images.githubusercontent.com/1135513/51301890-fc96bb80-1a30-11e9-825b-ac3c56a1f2e5.png) | ![capture d ecran 2019-01-17 a 08 17 23](https://user-images.githubusercontent.com/1135513/51301783-b3466c00-1a30-11e9-89a6-996729c74a9c.png)
=> feat: Update Onboarding design

package.json, src/ducks/categories/CategoriesHeader.jsx, src/ducks/onboarding/EnsureHasAccounts.jsx, src/ducks/onboarding/ensureIsFirstSynced.js, yarn.lock
=> Onboarding refactoring

src/components/SelectDates/SelectDates.jsx, src/components/SelectDates/SelectDates.styl
Le nouveau select de cozy-ui à une div en plus ce qui a changer le design du select des dates.
Maintenant la taille est gérée sur un élement de cozy-banks
=> fix: Selectdates proportion after cozy-ui upgrade

src/ducks/balance/components/AccountRow.jsx, src/ducks/balance/components/AccountsList.jsx, src/ducks/balance/components/GroupPanel.jsx, src/ducks/balance/helpers.spec.js
I merged https://github.com/cozy/cozy-banks/pull/810 too quickly and didn't pushed this stuff.
=> Fixes on balance switches

src/ducks/balance/History.jsx
Avant cette PR on récupérait toutes les opérations avec `cozy-client` en utilisant des critères `mango`. Actuellement la stack limite ce type de requête à seulement [100 documents](https://github.com/cozy/cozy-stack/issues/1726), ce qui peut ralentir l'affichage.
En attendant je propose de récupérer l'ensemble des opérations et de les filtrer coté client. Surtout qu'une fois toutes les opérations dans redux le changement de page vers `Mouvements` devrait (quand cozy-client sera optimisée) ne pas refaire la requête.
=> refactor: Optimize chart requests

src/index.ejs
Insert ThemeCSS variable into templates
=> Add CSS theme

package.json, src/ducks/categorization/services.js, yarn.lock
Update cozy-doctype & add static on `sendTransactions` function
=> fix: Categorization service

src/ducks/account/helpers.js, src/ducks/account/helpers.spec.js, src/ducks/balance/Balance.jsx, src/ducks/balance/components/AccountRow.jsx, src/ducks/balance/components/AccountsList.jsx, src/ducks/balance/components/BalanceRow.jsx, src/ducks/balance/helpers.js, src/ducks/notifications/BalanceLower.js, src/ducks/notifications/TransactionGreater.js, src/ducks/notifications/helpers.js, src/ducks/notifications/html/templates/balance-lower.hbs, src/ducks/notifications/html/templates/index.js, src/ducks/notifications/html/utils.js, src/ducks/transactions/TransactionModal.jsx, src/ducks/transactions/TransactionRow.jsx, src/ducks/transactions/TransactionSelectDates.jsx, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/helpers.js, src/ducks/transactions/helpers.spec.js
This adds the notions of `realisationDate` for transactions and `comingBalance` for accounts.
=> Fixes for deferred debit card accounts

package.json, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transactions/TransactionsPage.spec.jsx, src/selectors/index.js, yarn.lock
Do not show Balance in the cozy bar if we are viewing a category.
=> Fix: Balance should not appear in title bar when in category mode

package.json, src/components/BarBalance/index.jsx, src/components/BarBalance/index.spec.jsx, test/fixtures/unit-tests.json, yarn.lock
- Update cozy-ui for panel border-radius
- AccountBalance in title was wrong for creditCard accounts
=> fix: AccountBalance in title, border-radius

scripts/publish.js
I am working on using cozy-app-publish and drop our custom script, but I needed to publish a version quickly so I had to fix this.
=> chore(publish): Fix remoteFileExists

src/components/Switch.jsx, src/ducks/balance/components/AccountRow.jsx
Default color is grey
Primary color is blue
=> fix: Warning on Switch component

src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoriesHeader.styl
Vous pouvez voir [le nouveau design ici](https://testbankswhitebackgroundonmobile-banks.cozy.works/#/categories).
=> White background on mobile

src/ducks/balance/components/GroupPanel.jsx, src/utils/flag.js
Remove animation on account panels since they are underperforming on mobile.
=> No anim panels

src/components/Switch.jsx, src/components/Switch.md, src/ducks/balance/components/AccountRow.jsx, src/ducks/balance/components/GroupPanel.jsx
=> feat: Correct size and margins for Switch

src/components/Select/index.jsx, src/components/Select/styles.styl
Dates were truncated. Little adjustments to padding and margin fixes
the truncation.
=> feat: Tweaks to select for year filter

src/ducks/client/mobile.js
See https://docs.cozy.io/en/cozy-stack/auth/#linked-applications
=> feat: Link the mobile and web Banks applications

package.json, src/main.jsx, src/styles/buttons.styl, yarn.lock
=> Fix Button style on cozy-banks mobile

src/components/BarBalance/index.jsx, src/components/Figure/Figure.jsx, src/components/Figure/Figure.styl, src/components/Figure/__snapshots__/Figure.spec.jsx.snap, src/ducks/categorization/services.spec.js, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transactions/__snapshots__/TransactionModal.spec.jsx.snap
=> feat: Update Figure style with blue bar

src/components/BackButton/index.jsx, src/components/BackButton/style.styl, src/ducks/categories/CategoriesHeader.jsx, src/ducks/transactions/TransactionHeader.jsx
This fixes the cases in which the arrow was grey on a blue background.
=> feat(BackButton): Add theme prop

src/ducks/balance/Balance.jsx, src/ducks/balance/Balance.styl, src/ducks/balance/components/BalanceHeader.jsx, src/ducks/balance/components/BalanceHeader.styl
To be able to overload the component easily ;)
=> refactor: Create BalanceHeader components

src/assets/icons/icon-health.svg, src/ducks/balance/components/AccountRow.jsx
=> feat(Balance): Add health reimbursements icon

src/locales/en.json, src/locales/fr.json
FR=Remboursements en attente
EN=Awaiting reimbursements
=> feat(locales): Update reimbursements account type translations

src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.js
This modification has been done in cozy-konnector-libs too
=> fix: add missing health vendors

src/ducks/commons/Nav.jsx, src/ducks/transactions/TransactionHeader.jsx, src/ducks/transactions/TransactionsPage.styl, src/locales/en.json, src/locales/fr.json
* Update the translations of the balances tab
* Add a back button on desktop
Live on https://testbanksbalanceupdates-banks.cozy.works
=> Update on merged balance and movements routes

.travis.yml
=> chore: Don't launch Travis with commit on branche

src/components/BackButton/index.jsx, src/components/Breadcrumb/index.jsx, src/components/Breadcrumb/style.styl, src/components/ErrorBoundary/Error.styl, src/components/Header/Header.styl, src/components/KonnectorUpdateInfo/styles.styl, src/components/SelectDates/SelectDates.jsx, src/components/SelectDates/SelectDates.styl, src/components/Table/styles.styl, src/components/Title/Title.styl, src/ducks/account/AccountSwitch.styl, src/ducks/balance/Balance.styl, src/ducks/categories/CategoriesHeader.styl, src/ducks/mobile/statusBar.js, src/ducks/transactions/header/TableHead.styl, src/styles/palette.styl
We were using custom variable names but the good one are the ones used in [cozy-ui](https://github.com/cozy/cozy-ui/blob/ff96bcb4ccab339a053e12029e652630a1f56c9c/stylus/settings/palette.styl#L150-L152). So now we use these names, making the app more customizable.
See https://testbankscolorvars-banks.cozy.works
=> Use the color from injected CSS variables

src/ducks/balance/components/GroupPanel.jsx, src/utils/flag.js
Animation seem fluid enough now (tested by flo and fab).
=> feat: Animation on collapse

src/components/Figure/Figure.jsx, src/components/Figure/Figure.styl, src/ducks/account/AccountSwitch.jsx, src/ducks/balance/components/BalanceHeader.jsx, src/ducks/balance/components/BalanceHeader.spec.jsx, src/ducks/filters/index.js, src/ducks/filters/index.spec.js, src/ducks/transactions/TransactionHeader.jsx, src/locales/en.json, src/locales/fr.json
When clicking on the Balance figure, you filter by the currently
toggled accounts.
=> feat: Click on Balance brings you to transactions

src/ducks/balance/Balance.jsx, src/ducks/balance/Balance.spec.jsx, src/ducks/balance/components/BalanceHeader.jsx, src/ducks/balance/components/BalanceHeader.spec.jsx
BalanceHeader is completely overriden so it makes more sense to implement the click handler in Balance.jsx.
=> refactor: OnClickBalance is implemented in Balance.jsx

docs/categorization-dashboard.md
Add some documentation about categorization tests dashboard.
=> docs: Add doc about categorization dashboard

src/ducks/balance/Balance.jsx, src/ducks/settings/Debug.jsx
Add two button to display no acocunt screen
=> feat(NoAccount): Add debug flag

src/targets/mobile/config.xml, src/targets/mobile/hooks/before_prepare/010_User_Agent_Config_XML.js
Automatically ensures the user agent in config.xml corresponds
to the version in package.json
Done via a Cordova hook before preparing.
=> feat: Auto user agent

src/ducks/balance/Balance.jsx, src/utils/triggers.js, src/utils/triggers.spec.js
This resolve 2 problems:
- when no data the fake page has no banks icon
- fix triggers banks filter
=> No account bug

src/ducks/balance/components/AccountsImporting.jsx, src/ducks/balance/components/NoAccount.jsx
Since we now use a react component to set the bar theme, we have to use it in these two new components
=> Set bar theme in NoAccount and AccountsImporting

src/ducks/client/mobile.js, src/ducks/client/mobile.spec.js
Shame, shame...
I forgot the indexOf() > -1
=> fix: Check for revocation would trigger false positives

src/ducks/categories/AddAccountButton.jsx, src/ducks/categories/AddAccountButton.styl, src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoriesHeader.styl
=> refactor(AddAccountButton): Create button component

src/components/UserActionRequired/index.jsx, src/ducks/mobile/MobileRouter.jsx, src/ducks/mobile/utils.js, src/ducks/pin/FingerprintButton.jsx, src/ducks/pin/PinAuth.jsx, src/ducks/pin/PinButton.jsx, src/ducks/pin/PinEditView.jsx, src/ducks/pin/PinGuard.jsx, src/ducks/pin/PinKeyboard.jsx, src/ducks/pin/PinRestrictedArea.jsx, src/ducks/pin/Round.jsx, src/ducks/pin/constants.js, src/ducks/pin/queries.js, src/ducks/pin/styles.styl, src/ducks/settings/PinSettings.jsx, src/locales/en.json, src/locales/fr.json, src/targets/mobile/config.xml
- No confirm button when entering pins
- Pin edition is protected by pin when it is set
- Pin guard is not active if pin not set
- Logout after too many attempts
- Fingerprint auth is shown automatically if available
...and more ;)
Still no tests, I plan to write them after the components
responsibility, props etc... have stabilized. Soon !
=> feat: Pin screen part II

src/ducks/mobile/MobileRouter.jsx, src/ducks/mobile/utils.js, src/main.jsx
Some custom versions of the CozyBar are needing a injected CozyClient.
=> Inject CozyClient in Bar

package.json, src/AppContainer.jsx, src/main.jsx, yarn.lock
To easly custom authentication page
=> feat: Add debug mode to display authentication page

src/ducks/pin/PinAuth.jsx, src/ducks/pin/PinEditView.jsx, src/ducks/pin/PinGuard.jsx, src/ducks/pin/styles.styl, src/locales/en.json, src/locales/fr.json, src/targets/mobile/config.xml
- Tweak icon size
- Check if pin needed on app resume
=> Fixes on Pin

config/webpack.config.manifest.js
I left some code after removing unused skin code.
=> fix: Error while suppressing unused code

src/ducks/transactions/actions/KonnectorAction/BrowserConfigurationModal.jsx, src/ducks/transactions/actions/KonnectorAction/ConfigurationModal.jsx, src/ducks/transactions/actions/KonnectorAction/InformativeModal.jsx, src/ducks/transactions/actions/KonnectorAction/MobileConfigurationModal.jsx, src/ducks/transactions/actions/KonnectorAction/index.jsx
This refactor's goal is to split each subcomponent in its own file, so it's easier to override small parts in customizations. This way we don't have to copy/paste the whole action file to override small UI parts.
=> Refactor konnector action

config/webpack.target.browser.js, src/index.ejs
Set title via HTMLWebpackPlugin options so that we can override it in customizations repository.
=> feat: Allow custom title via HtmlWebpackPlugin

src/targets/mobile/config.xml, src/targets/mobile/scripts/customizeConfigXML.js
We need to run the config.xml customization manually for iOS.
=> feat: Ability to run customize config xml

src/components/ErrorBoundary/ErrorBoundary.jsx, src/ducks/transactions/index.js
TransactionsPage could not be customized as it relied on relative path
=> Fix customisations

src/ducks/balance/components/AccountRow.jsx, src/ducks/balance/components/AccountRow.styl, src/ducks/balance/components/AccountRowLoading.jsx, src/ducks/balance/components/KonnectorIcon.jsx
=> refactor(KonnectorIcon): Style

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap, src/ducks/brandDictionary/brands.json, src/ducks/transactions/TransactionActions.spec.jsx
Add the following brands to the dictionary:
* EDF
* Humanis
* Impôts
* SNCF
=> Add brands

src/components/Chart/Tooltip.styl, src/styles/palette.styl
It was hardcoded, now it is customizable.
=> refactor(Tooltip): Use a CSS variable for background color

package.json, src/ducks/settings/Debug.jsx, src/ducks/settings/Settings.jsx, yarn.lock
Showing debug flags in Debug view
Waiting for https://github.com/cozy/cozy-libs/pull/358
=> feat: Show debug flags in Debug view

src/ducks/settings/Configuration.jsx, src/locales/en.json, src/locales/fr.json
=> feat(Settings): Add toggle to activate amounts blur

src/ducks/transactions/actions/KonnectorAction/helpers.js, src/ducks/transactions/actions/KonnectorAction/index.jsx, src/ducks/transactions/actions/KonnectorAction/match.js
=> refactor(KonnectorAction): Split match function

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap, src/ducks/brandDictionary/brands.json
Add a brand for a brand new connector ^^
Planète Oui
Connector is already available, merge it please.
Thank's
=> feat: Add Planete OUI to brand dictionnary

package.json, yarn.lock
Needed to have the latest version of the AppLinker component
=> feat: Upgrade UI

package.json, yarn.lock
=> chore: Update cozy-client

src/ducks/balance/Balance.jsx
Tried to simplify realtime state
Transactions were not fetched again which left a timeline
that was incorrect.
=> feat: Simplify realtime logic in Balance

package.json, src/components/Loading/Loading.jsx, src/components/Loading/Loading.styl, yarn.lock
Upgrades cozy-ui to the latest version and fixes the breaking change.
=> fix: Upgrade cozy-ui

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap, src/ducks/brandDictionary/brands.json
The Amazon connector will be released soon, so we update our dictionary to have it in the CTAs.
=> feat(brandDictionary): Add Amazon

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap, src/ducks/brandDictionary/brands.json
Add the brand CESU and update tests snapshots
thank's
=> chore: Add brand CESU to dictionnary

docs/brand-dictionary.md
We answered the same questions multiple times about the brand dictionary. So here is a bit of doc we can link to.
=> docs: Add doc about brand dictionary

src/targets/services/onOperationOrBillCreate.js
If some steps succeed but another one fails, the `lastSeq` of the steps
that succeeded are saved, so we don't do the same work on the next
service run.
=> feat(service): Save settings after each step

src/ducks/commons/Nav.jsx
Add render hook to be able to add links in Nav.
=> feat: Render extra nav

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap, src/ducks/brandDictionary/brands.json
As title describe, it can be publish as soon as you want.
Test snapshots has been updated.
Thank's.
=> feat: Add Ekwateur brand to brandDictionnary

src/ducks/transactions/TransactionRow.jsx
We lost the pointer cursor on transaction row. This fixes it.
=> fix(TransactionRow): Show a pointer when hovering the row

package.json, src/ducks/notifications/Notification.js, src/ducks/notifications/helpers.js, src/ducks/notifications/helpers.spec.js, src/ducks/notifications/html/common-test.js, src/ducks/notifications/html/templates/balance-lower.hbs, src/ducks/notifications/html/testTemplates.js, src/ducks/notifications/url-polyfill.js, yarn.lock
Links in emails bring to native if possible now.
=> feat: Use AppLinker helper to generate universal link

src/utils/flag.js
We want the entire world to benefit from this awesome feature <3
=> feat: Enable reimbursement-tag flag by default

src/ducks/categories/Categories.jsx, src/ducks/transactions/TransactionHeader.jsx, src/ducks/transactions/TransactionRow.jsx
=> fix: Remove warnings

src/components/BottomButton.jsx, src/doctypes.js, src/ducks/transfers/TransferPage.jsx
- Temporary account creation containing password (encrypted)
- Permission is given to the konnector to read this account
=> feat: Transfer job creation

src/ducks/settings/Configuration.jsx, src/ducks/settings/ToggleRow.jsx, src/ducks/settings/ToggleRow.styl, src/locales/en.json, src/locales/fr.json
The UI was not correct. Now we respect the mockups.
=> Update health reimbursement notifications UI

package.json, src/components/Spacing/Padded.jsx, src/ducks/categories/AddAccountButton.jsx, src/ducks/transactions/TransactionActions.spec.jsx, src/ducks/transfers/TransferPage.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
Show explanation pages
- No recipients
- No bank accounts
- Validate amount (> 5, < 1000€)
=> feat: Error cases

src/ducks/notifications/HealthBillLinked.js, src/ducks/notifications/html/data/health-bill-linked.json, src/ducks/notifications/html/utils.spec.js, test/fixtures/demo.json
The vendors were not shown anymore in the health bill linked notification email.
Before:
After:
=> Fix health bill linked notification email content

manifest.webapp, package.json, src/ducks/transfers/TransferPage.jsx, src/locales/fr.json, yarn.lock
Important to create temporary account for transfers
=> feat: Add io.cozy.accounts permission

src/ducks/balance/Balance.jsx, src/ducks/balance/components/AccountRowLoading.jsx, src/ducks/balance/components/AccountRowLoading.styl, src/ducks/balance/components/AccountsImporting.jsx, src/ducks/balance/components/AccountsList.jsx, src/locales/en.json, src/locales/fr.json
Cette fonctionnalité permet de visualiser lorsqu'un compte est entrain d'être importé et qu'il y a une erreur sur ce compte. Il suffit alors de cliquer dessus pour être redirigé vers la `home`.
=> Accounts loading error

src/components/AccountIcon/index.jsx, src/components/AccountIcon/styles.styl, src/components/TextCard/index.jsx, src/components/TextCard/styles.styl, src/ducks/transfers/TransferPage.jsx, src/locales/en.json, src/locales/fr.json, src/targets/mobile/scripts/customizeConfigXML.js
- AccountIcon width/height were unconstrained due to CSS rule order. Added a container to constrain available space.
- Validation of amounts
- Wording
- Password slide improvements (icon + cannot click if value == '')
=> feat: Last touches to transfer page

config/webpack.config.base.js, src/ducks/pin/queries.js, src/ducks/transfers/TransferPage.jsx, src/ducks/transfers/TransferPage.spec.jsx, src/ducks/transfers/recipients.js, src/ducks/transfers/recipients.spec.js, src/ducks/transfers/transfers.js, src/locales/en.json, src/locales/fr.json
Show a specific message when the error is LOGIN_FAILED
=> feat: Handles wrongpass

docs/credentials.md, package.json
Ajout de documentation pour les fichiers chiffrés
=> feat(Credentials): Add doc & command to update credentials

manifest.webapp, src/ducks/notifications/DelayedDebit.js, src/ducks/notifications/DelayedDebit.spec.js, src/ducks/notifications/helpers.js, src/ducks/notifications/html/common-test.js, src/ducks/notifications/html/data/delayed-debit.json, src/ducks/notifications/html/delayed-debit-html.js, src/ducks/notifications/html/templates/delayed-debit.hbs, src/ducks/notifications/html/templates/index.js, src/ducks/notifications/index.js, src/ducks/notifications/services.js, src/locales/en.json, src/locales/fr.json
This implements the delayed debit notification. See screenshot below
=> Delayed debit notification

src/ducks/notifications/html/__snapshots__/emails.spec.js.snap
I missed it in my previous PR it seems.
=> test(notifications): Update emails snapshots

src/ducks/settings/Configuration.jsx
Because… it's useful ? For *things*.
=> feat(Configuration): Enable rendering extra items

src/ducks/account/AccountSwitch.jsx, src/ducks/balance/Balance.jsx, src/ducks/balance/components/GroupPanel.spec.jsx, src/ducks/categories/Categories.jsx, src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoriesPage.jsx, src/ducks/settings/AccountsSettings.jsx, src/ducks/settings/Configuration.jsx, src/ducks/transactions/TransactionHeader.jsx, src/ducks/transactions/TransactionsPage.jsx, src/lib/chartjsPieLabels.js, src/utils/flag.js
Apply flags that were set to true :tada:
Majority of the changes was done automatically via the flag codemod. Next eslint --fix (some manual fixes to) and then removal of the files that were not needed.
=> feat: Apply flags

.lintstagedrc, package.json
Both of both world hopefully :)
- Fast commit
- No failing tests too late (in CI)
=> chore: Only run tests on prepush

src/ducks/transactions/TransactionHeader.jsx
Wrong prop passed when removed the flags.
=> fix: BackButton uses theme and not color

auto-merge.yml
I want to add this for very small PRs : https://github.com/bobvanderlinden/probot-auto-merge
The idea being that for very small PRs, we can label when creating the issue with "merge" and
as soon as it is reviewed, it is automatically merged.
=> Configure auto merge

src/index.ejs
Add error handling for errors occuring before the React application is loaded.
=> feat: Add initial error handling

config/VersionPlugin.js, src/ducks/settings/Debug.jsx, src/styles/utilities.styl, webpack.config.js
Collects versions of packages and uses DefinePlugin to define a variable
containing those versions so we can use it in the code. The idea would be to have those versions in the Debug view.
=> feat: Attempt at VersionPlugin

package.json, yarn.lock
To the latest non-major version.
=> feat: Upgrade cozy-ui

README.md
=> docs: Split long sentence

.github/auto-merge.yml
=> fix: minApprovals instead of min-approvals

README.md
=> docs: Add "personal" word

.github/auto-merge.yml, src/index.ejs
- I queried the wrong app node, so the error would not show up
- Added the blockingChecks in auto-merge
=> fix: Query the right selector for app node

package.json, yarn.lock
We still had a problem on the back button. This cozy-authentication fixes it.
=> fix(deps): Update cozy-authentication to v1.15.1

package.json, yarn.lock
See https://github.com/cozy/cozy-libs/blob/master/packages/cozy-authentication/CHANGELOG.md#1152-2019-07-12
=> fix(deps): Update cozy-authentication to v1.15.2

src/targets/mobile/config.xml
- Added xmlns:android to xml schema to be able to use `<foo android: ` notation
- disable stuff
=> Feat/firebase: Rm useless stuff

src/components/App.jsx
It is easily accessible via the settings
=> feat: Do not show flag switcher as fixed

src/targets/services/stats.js
Remove sporadic categories and include retirement.
=> feat(stats): Update categories included in additional income

package.json, yarn.lock
Need a fix for the overrideFiles method
=> feat: Upgrade cozy-doctypes

test/fixtures/demo.json
In cozy-procedures, we want to add a JSON file containing banking data history for the last 3 months, including the accounts' IBAN. Adding fake IBANs to our fixtures enables us to test it easily
=> chore(fixtures): Add IBAN to bank accounts

scripts/visualizer/README.md, scripts/visualizer/index.js, scripts/visualizer/manifest.konnector, scripts/visualizer/package.json, scripts/visualizer/src/server/index.js, scripts/visualizer/webpack.config.js, scripts/visualizer/yarn.lock, src/ducks/billsMatching/Linker/Linker.js
The visualizer was not working after updates on the bills matching code. This repairs it and update the documentation.
=> Repair bills matching visualizer

src/ducks/settings/Debug.jsx
Add client URL in debug
Add oauth client id
=> feat: Debug info

package.json, src/components/Chart/LineChart.jsx, src/components/withSize.js, src/ducks/account/AccountSwitch.jsx, src/ducks/balance/Balance.jsx, src/ducks/balance/History.jsx, src/ducks/balance/HistoryChart.jsx, src/ducks/balance/components/BalanceHeader.spec.jsx, src/ducks/categories/CategoriesPage.jsx, src/ducks/client/utils.js, src/ducks/filters/index.js, src/ducks/transactions/TransactionHeader.jsx, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transactions/TransactionsPage.spec.jsx, test/jest.setup.js, yarn.lock
To improve page loading, we show data even if we are loading it. This works
well we data has already been loaded.
Next step would be not to fetch again if the data is fresh enough.
=> perf: Show data even if we are loading it

docs/bills-matching.md, src/ducks/billsMatching/Linker/Linker.js, src/ducks/billsMatching/Linker/Linker.spec.js
This documentation didn't exist at all. Since it was difficult to dive back in this algorithm after a long period without touching it, I thought it was necessary to take the time to write it.
=> Documentation about bills matching algorithm

src/ducks/settings/Debug.jsx, src/ducks/transfers/steps/Amount.jsx
=> Use UI components

.travis.yml, package.json, scripts/check-locales.sh, scripts/locale-check/check-locale-paths-usage.js, scripts/locale-check/find-unused-keys.sh, scripts/locale-check/list-t.js, src/ducks/transactions/TransactionRow.jsx, src/ducks/transactions/actions/KonnectorAction/index.jsx, src/ducks/transactions/header/TableHead.jsx, src/locales/en.json, src/locales/fr.json
I modified greg scripts to sort keys and use git to have colored diff.
Now travis will fail if we have differences betweeen keys in en.json or fr.json.
=> Check locales

package.json, src/components/Chart/LineChart.jsx, src/doctypes.js, src/ducks/balance/BalancePanels.jsx, src/ducks/balance/components/BalanceHeader.jsx, src/ducks/balance/components/GroupPanel.jsx, src/ducks/groups/helpers.js, src/ducks/groups/helpers.spec.js, src/lib/sentry.js, src/main.jsx, src/store/configureStore.js, src/styles/utilities.styl, yarn.lock
- Delay rendering of GroupPanels (biggest performance gain)
I could not see why GroupPanels where so long to render. I plan to put here more benchmarks. Stay tuned...
Visible on https://testbanksperf-banks.cozy.works/#/balances
=> Perf: Improvements of Balance perf at mount

src/components/Chart/LineChart.jsx
- Only hide tooltip when entering animation
- Refactored to better parametrize placement and dimensions
=> Fix tooltip

src/ducks/balance/HistoryChart.jsx, src/ducks/transactions/TransactionPageErrors.jsx, src/ducks/transactions/TransactionsPage.spec.jsx, src/ducks/transactions/TriggerErrorCard.jsx, src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusAction.spec.jsx, src/ducks/transactions/scroll/ScrollRestore.js
Otherwise, the error can be shrinked
=> feat: Apply u-flex-shrink-0 to transaction page errors

src/ducks/commons/Nav.jsx
By using a state, we do not wait for the route change to trickle down
into the `active` prop of the link. It makes the change of color after
click instant.
=> feat: Faster change of color of the Nav tab

docs/IconSpriteInjector.jsx, src/ducks/client/mobile/mobile.js, src/ducks/client/utils.js, src/ducks/client/utils.spec.js, src/ducks/commons/Nav.jsx, src/ducks/mobile/push.js, src/ducks/settings/Debug.jsx, src/lib/sentry.js, styleguide.config.js, test/fixtures/unit-tests.json
Small improvements/fixes detected during development.
=> Improvements

docs/styleguide/IconSpriteInjector.jsx, src/components/BackButton/style.styl, src/components/Chart/LineChart.jsx, src/components/SelectDates/SelectDates.styl, src/ducks/balance/components/AccountRow.styl, styleguide.config.js, test/fixtures/unit-tests.json
- Active styles help make the app feel more responsive
- Cursor pointer and bigger click area on curve
- 1 less warning in tests
- Icons work in styleguide
=> Little tweaks

package.json, yarn.lock
Bug on hydratation broke pages using groups
=> fix: Update cozy-client

package.json, src/ducks/client/index.js, src/ducks/client/web.js, src/ducks/transactions/TransactionsPage.spec.jsx, src/selectors/index.js, yarn.lock
We have to use the client's getQueryFromState to be able to hydrate.
=> feat: Correctly hydrate

src/selectors/index.js
Only hydrate when necessary, when the query results change.
- Logic for hydratation that is in cozy-client was copy/pasted. It could
be exported from cozy-client in the future
EDIT: 1.6.0.5 iOS was built from this branch
=> feat: Hydrate less

src/utils/triggers.js
4 new banking konnectors will be released soon. We add their slugs to the existing list.
=> feat: Add new banking konnectors slugs

src/components/App.jsx, src/ducks/account/helpers.js, src/ducks/balance/Balance.jsx, src/ducks/balance/BalancePanels.jsx, src/ducks/balance/History.jsx, src/ducks/balance/components/BalanceHeader.jsx, src/ducks/categories/Chart.jsx, src/ducks/reimbursements/HealthReimbursements.jsx, src/ducks/settings/Debug.jsx, src/ducks/transactions/TransactionPageErrors.jsx, src/ducks/transactions/TransactionPageErrors.spec.jsx, src/ducks/transactions/TransactionRow.jsx, src/ducks/transactions/actions/AppLinkAction.jsx, src/ducks/transactions/actions/AttachedDocsAction/index.js, src/ducks/transactions/actions/BillAction.jsx, src/ducks/transactions/actions/HealthExpenseStatusAction.jsx, src/ducks/transactions/actions/HealthLinkAction.jsx, src/ducks/transactions/actions/KonnectorAction/index.jsx, src/ducks/transactions/actions/ReimbursementStatusAction/match.js, src/ducks/transactions/actions/UrlLinkAction.jsx, src/ducks/transactions/helpers.js, src/ducks/transactions/helpers.spec.js, src/utils/flag.js
Add several flags to test UI changes.
=> UX tweaks 2

package.json, yarn.lock
Update to have the [richer mattermost message](https://github.com/cozy/cozy-libs/commit/98c0b53ba7cb6f6ab87252912f73c112e6891314) after publication.
=> feat: Update cozy-app-publish

package.json, src/components/Stepper/index.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.spec.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertSettingsPane.jsx, src/selectors/getClient.js, src/selectors/index.js, test/AppLike.jsx, test/client.js, yarn.lock
- Basic test
- Small tweaks
Commit messages are hopefully self explanatory.
I think the createClientWithData is particularly interesting and could be
very helpful.
=> UI tweaks on category alert edition modal

babel.config.js, package.json, src/ducks/budgetAlerts/CategoryBudgetNotificationView.js, src/ducks/budgetAlerts/cli.js, src/ducks/budgetAlerts/index.js, src/ducks/budgetAlerts/index.spec.js, src/ducks/budgetAlerts/template.hbs, src/ducks/notifications/index.js, src/ducks/settings/CategoryAlerts/CategoryAlertCard.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.spec.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertSettingsPane.jsx, src/ducks/settings/helpers.js, src/locales/en.json, src/locales/fr.json, src/targets/services/onOperationOrBillCreate.js, yarn.lock
- CLI to show current alerts and potentially force the sending of a notification
- Email template
- Saving of the current "amount" of the alert after sending notification not
to send a notification twice when nothing has changed
Template is a bit crude still, more work has to be done but this PR is already a good step.
=> feat: Category budget service

src/ducks/budgetAlerts/CategoryBudgetNotificationView.js, src/ducks/budgetAlerts/cli.js, src/ducks/budgetAlerts/index.js, src/ducks/budgetAlerts/index.spec.js, src/ducks/budgetAlerts/service.js, src/ducks/settings/CategoryAlerts/AccountGroupChoice.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertCard.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertSettingsPane.jsx, src/ducks/settings/Configuration.jsx, src/locales/en.json, src/locales/fr.json, src/targets/services/onOperationOrBillCreate.js
- Fix: Can create more than 1 alert 😅
- Translation tweaks for alert by category modal
- Order of text tweaks for alert by category card
- Placement tweak of the alert by category section in settings
=> Category budget service and UI tweaks and fixes

config/webpack.target.services.js, docs/services.md, manifest.webapp, src/ducks/budgetAlerts/CategoryBudgetNotificationView.js, src/ducks/budgetAlerts/index.js, src/ducks/budgetAlerts/index.spec.js, src/ducks/budgetAlerts/service.js, src/ducks/budgetAlerts/service.spec.js, src/ducks/settings/CategoryAlerts/CategoryAlertCard.jsx, src/ducks/settings/Debug.jsx, src/locales/en.json, src/locales/fr.json, src/targets/services/budgetAlerts.js, src/targets/services/service.js, test/client.js, test/fixtures/unit-tests.json
Added integration tests for the budget notification service
=> Tests for category budget notification service

src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx, src/locales/en.json, src/locales/fr.json
We previously show the vendor name only for refunds. Now we show it for every bill CTA
=> feat(BillChip): Show vendor name

src/ducks/settings/CategoryAlerts/AccountGroupChoice.jsx, src/ducks/settings/CategoryAlerts/AccountGroupChoice.spec.jsx
=> fix: Pass t function for helper to work correctly

src/ducks/balance/components/BalanceRow.jsx, src/ducks/budgetAlerts/CategoryBudgetNotificationView.js, src/ducks/budgetAlerts/service.js, src/ducks/budgetAlerts/service.spec.js, src/ducks/budgetAlerts/template.hbs, src/ducks/notifications/__snapshots__/emails.spec.js.snap, src/ducks/notifications/bank-layout.hbs, src/ducks/notifications/services.js, src/ducks/notifications/services.spec.js, src/targets/services/onOperationOrBillCreate.js
- Account and group labels are shown
- Push notification content
- Email footer is fixed
- Instead of launching function for category budgets, we launch a job for better monitoring in metabase/bender
=> feat: Budget notification improvements

docs/services.md, src/ducks/budgetAlerts/CategoryBudgetNotificationView.js, src/ducks/budgetAlerts/service.spec.js, src/locales/en.json, src/locales/fr.json
- Title of email/push is different depending on whether only 1 alert was
triggered or several
- Content of push also depends on whether only 1 alert was triggered or
several
=> feat: Improve notification title for category budgets

src/ducks/settings/CategoryAlerts/CategoryAlertCard.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertCard.styl
Mobile: 100%
Desktop: 300px
Also fixed typos in usage of `u-media` classes
=> feat: Size of category alerts setting cards

config/webpack.target.services.js, manifest.webapp, src/doctypes.js, src/ducks/account/helpers.js, src/ducks/account/helpers.spec.js, src/ducks/account/services.js, src/ducks/account/services.spec.js, src/ducks/groups/services.js, src/ducks/settings/__snapshots__/helpers.spec.js.snap, src/ducks/settings/constants.js, src/targets/services/linkMyselfToAccounts.js, src/utils/mergeSets.js, test/client.js
First step in the account/contact link : when a new account is created, we link it to the « myself » contact if it exists.
=> feat: When a new account is created, link myself to it

src/components/PopupSelect/index.jsx, src/components/PopupSelect/styles.styl
ModalContent is important for the scrolling
Using it instead ModalDescription is simpler and works
=> fix: Scroll not functioning in when selecting category of a transaction

.travis.yml
We do not know why Travis suddenly stopped building PR branches but
this seems the culprit
=> fix: We need to be able to build pushed branches

src/ducks/pin/PinAuth.jsx, src/ducks/pin/PinAuth.spec.jsx, src/ducks/pin/styles.styl
- Correctly pass t to Fingerprint paragraph (otherwise we had a crash)
- Also tweak the size of the fingerprint icon
=> fix: Fingerprint Pin

src/components/EditionModal/AccountOrGroupSection.jsx, src/components/EditionModal/CategorySection.jsx, src/components/EditionModal/EditionModal.jsx, src/components/EditionModal/ThresholdSection.jsx, src/components/EditionModal/index.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.jsx, src/ducks/settings/CategoryAlerts/helpers.js, src/ducks/settings/CategoryAlerts/helpers.spec.js
Since we will need to use the same kind of edition mechanism from
alerts to other notifications, it was necessary to make the edition
modal more generic.
- Extracted components to edit AccountGroup / Category / MaxThreshold
- Implement CategoryAlertEditModal through a generic EditionModal configured
through field specifications
=> Generic edition modal

src/utils/flag.js
We want these features to be enabled by default for the next release.
=> feat: Enable owners related flags by default

test/fixtures/demo.json
We thought we had this kind of loan account fixture, but we didn't.
=> chore(fixtures): Add loan account

src/ducks/settings/CategoryAlerts/CategoryAlertSettingsPane.jsx, src/ducks/settings/Configuration.jsx, src/ducks/settings/TogglableSettingCard.jsx, src/locales/en.json, src/locales/fr.json
Add create alert button that show an alert with "This feature will soon
be available".
Previously the TogglableCard contained the ToggleRowWrapper that was
adding a margin below it, I refactored it to extract a SettingSection
component
=> feat: Add demo create alert button

docs/dev.md, package.json, src/components/BackButton/index.jsx, src/components/BackButton/style.styl, src/ducks/notifications/BalanceLower/index.js, src/ducks/notifications/TransactionGreater/data.json, src/ducks/notifications/TransactionGreater/index.js, src/ducks/notifications/TransactionGreater/index.spec.js, src/ducks/notifications/services.js, src/ducks/settings/ruleUtils.js, src/ducks/transactions/helpers.js, src/locales/en.json, src/locales/fr.json, test/e2e/alerts-existing-cozy.js, test/e2e/alerts.js
- Support multi rules for TransactionGreater
- Add E2E semi automatic test for TransactionGreater
=> feat: Support multi rules for TransactionGreater

docs/dev.md, src/ducks/notifications/TransactionGreater/index.js, src/ducks/notifications/services.js, src/locales/en.json, src/locales/fr.json, test/e2e/alerts.js, test/e2e/fake-fcm-server.js
- See d710541d3 for push notification content examples
- Added semi automatic push notification E2E test
=> feat: Better content for transaction greater push notification

package.json, src/ducks/account/helpers.spec.js, src/ducks/settings/Rules.jsx, src/ducks/transactions/TriggerErrorCard.spec.jsx, src/ducks/transactions/__snapshots__/TriggerErrorCard.spec.jsx.snap, src/locales/fr.json, yarn.lock
- Smaller
- Detached from the rest with a margin
- "Ajouter une alerte" instead of "Créer une alerte" in French
=> feat: Better add alert button

package.json, src/ducks/settings/CategoryAlerts/CategoryAlertEditModal.spec.jsx, test/AppLike.jsx, yarn.lock
Will open the gate to use hooks to select data from the redux store.
I did not see any problems so far.
- [Release 7.0.1](https://github.com/reduxjs/react-redux/releases/tag/v7.0.1) - 19 Apr 2019
- [Release 6](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0) - 5 Dec 2018
=> feat: Update react redux

src/ducks/account/AccountSwitch.jsx, src/index.ejs, src/styles/main.styl
- Pin screen was truncated when starting the app
- Bar would disappear when entering the analyze screen
=> Mobile fixes

src/ducks/account/helpers.js, src/ducks/account/helpers.spec.js, src/ducks/balance/components/AccountRow.jsx, src/ducks/filters/index.js, src/ducks/reimbursements/HealthReimbursements.jsx, src/ducks/reimbursements/HealthReimbursements.spec.jsx, src/ducks/reimbursements/selectors.js, src/ducks/transactions/TransactionActions.spec.jsx, src/ducks/transactions/actions/ReimbursementStatusAction/match.js, src/locales/en.json, src/locales/fr.json, src/utils/flag.js
- Reimbursements are considered in the last 6 month period in account summary in the home (instead of current year)
- Current period is shown in the empty message
=> Health reimbursement period

src/ducks/pin/PinGuard.jsx, src/ducks/pin/PinKeyboard.jsx, src/ducks/pin/PinTimeout.debug.jsx, src/ducks/pin/WithFingerprint.jsx, src/ducks/pin/styles.styl
- Larger buttons
- Keyboard now takes 2/3 of the screen
=> Pin tweaks

src/ducks/transactions/TransactionActions.spec.jsx, src/ducks/transactions/TransactionRow.jsx, src/ducks/transactions/actions/AppLinkAction.jsx, src/ducks/transactions/actions/AttachedDocsAction/index.jsx, src/ducks/transactions/actions/BillAction.jsx, src/ducks/transactions/actions/HealthExpenseStatusAction.jsx, src/ducks/transactions/actions/HealthLinkAction.jsx, src/ducks/transactions/actions/KonnectorAction/index.jsx, src/ducks/transactions/actions/UrlLinkAction.jsx
- Applied reimbursement flag
- Updated tests to test new chips
=> Apply reimbursement flag

src/ducks/pin/PinAuth.jsx, src/ducks/pin/PinGuard.jsx, src/ducks/pin/WithFingerprint.jsx, src/ducks/pin/styles.styl
- Perf at startup
- Relaunch auth window after app blur
- Error text was shown underneath keyboard due to insufficient space
=> Improvements to Pin code

src/targets/mobile/config.xml
We did a mistake a some point and the version code was not good
according to our formula
(beta + patch *100 + minor * 10000 * major * 1000000). This fixes it so
we don't do a mistake next time we increase the version
=> chore: Fix android version code

src/components/App.jsx, src/ducks/pin/index.browser.jsx, src/ducks/pin/index.jsx, src/ducks/settings/Configuration.jsx
Pin is not present on browsers, only on mobile.
=> feat: Activate pin flag

README.md, docs/dev.md
- Added a bit on PR templates and README for feature requests to go to the forum.
- Moved skins part out of readme.
=> Improvements to README

src/locales/en.json, src/locales/fr.json
They are shorter than before so they are cut in less situations
=> feat(locales): Update reimbursements virtual accounts translations

test/fixtures/demo.json
- Add more health operations in demo fixtures
=> Add fixtures

src/components/Section/Section.jsx, src/components/Section/Section.styl, src/components/Section/index.js, src/ducks/categories/CategoriesHeader.jsx, src/ducks/reimbursements/Reimbursements.jsx, src/ducks/reimbursements/Reimbursements.spec.jsx, src/ducks/reimbursements/ReimbursementsPage.jsx, src/locales/en.json, src/locales/fr.json, src/targets/mobile/config.xml, src/utils/flag.js
<details>
```
```
```curl "https://apps-registry.cozycloud.cc/banks/registry/banks" | jq '.'```
</details>
<details>
```
```
</details>
<details> …
=> Release 1.14.0

package.json, src/components/BarBalance/index.jsx, src/components/Figure/Figure.jsx, src/components/Figure/Figure.styl, src/components/Figure/__snapshots__/Figure.spec.jsx.snap, src/components/Header/Header.styl, src/doctypes.js, src/ducks/balance/BalanceDetailsHeader.jsx, src/ducks/recurrence/DebugRecurrencePage.jsx, src/ducks/recurrence/RecurrencePage.jsx, src/ducks/recurrence/RecurrencesPage.jsx, src/ducks/recurrence/api.js, src/ducks/recurrence/queries.js, src/ducks/recurrence/rules.js, src/ducks/recurrence/utils.js, src/ducks/transactions/TransactionRecurrenceEditor.jsx, src/ducks/transactions/TransactionRecurrenceEditor.spec.jsx, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/__snapshots__/TransactionModal.spec.jsx.snap, src/locales/en.json, src/locales/fr.json, test/fixtures/demo.json, test/fixtures/unit-tests.json, yarn.lock
- Added a suppression button in the recurrence status menu
- Transactions are marked as non recurrent
- Recurrence object is deleted
=> feat: Ability to delete a recurrence

package.json, src/ducks/recurrence/DebugRecurrencePage.jsx, src/ducks/recurrence/RecurrencesPage.jsx, src/ducks/recurrence/rules.js, src/ducks/recurrence/rules.spec.js, src/ducks/recurrence/search.js, src/ducks/recurrence/search.spec.js, src/ducks/recurrence/utils.js, src/ducks/transactions/TransactionModal.jsx, src/ducks/transactions/__snapshots__/TransactionModal.spec.jsx.snap, src/locales/en.json, src/locales/fr.json, src/utils/flag.js, yarn.lock
Tweaks after our first user feedback (Fab)
Each commit should be self explanatory
=> Recurrence UI 9

package.json, src/components/ActionMenuHelper/index.jsx, src/components/ActionMenuHelper/styles.styl, src/components/Bar.jsx, src/components/useToggle.js, src/ducks/recurrence/RecurrencePage.jsx, src/ducks/transactions/TransactionRecurrenceEditor.jsx, src/locales/en.json, src/locales/fr.json, src/styles/main.styl, yarn.lock
Lots of small improvements. Most come from UI.
Each commit should be self explanatory.
=> Recurrence UI 10

.travis.yml, package.json, src/ducks/categorization/services.js, src/targets/services/categorization.js, src/targets/services/onOperationOrBillCreate.js, yarn.lock
The categorisation library tried to register the client
a second time. I fixed the categorisation lib not to use
registerClient. I also took this opportunity to remove
the old client where possible.
=> feat: Repair categorisation service

package.json, src/components/AppRoute.jsx, src/components/Title/PageTitle.jsx, src/components/__snapshots__/AppRoute.spec.jsx.snap, src/ducks/search/SearchPage.jsx, src/ducks/search/index.jsx, src/ducks/settings/Debug.jsx, src/ducks/transactions/TransactionModal.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
Behind a flag at the moment to test UI.
- Search page to search transactions in the store
- Link from transaction modal to search
=> Simple search page

package.json, yarn.lock
Updates cozy-scripts to latest version.
=> feat: Update cozy-scripts

src/components/Loading/Loading.styl, src/components/Table/styles.styl, src/ducks/account/AccountSwitch.styl, src/ducks/account/helpers.js, src/ducks/balance/components/AccountRow.styl, src/ducks/balance/components/GroupPanel.styl, src/ducks/categories/CategoriesHeader.styl, src/ducks/categories/categoriesMap.js, src/ducks/categories/colors.js, src/ducks/categories/styles.styl, src/ducks/settings/Sections.styl, src/ducks/transactions/TransactionModal.styl, src/ducks/transactions/Transactions.styl, src/utils/flag.js
Move colors config to one file so that it can be
easily overrided.
=> Make it easier to override category colors

src/components/Stepper/Stepper.jsx, src/components/Stepper/styles.styl, src/ducks/transfers/TransferPage.jsx
Other pages had been changed to have primaryColor top bar, not
this one.
=> feat: TransferPage has primaryColor top bar

jest.config.js, package.json, test/__mocks__/cozy-keys-lib/index.js, yarn.lock
Update cozy-harvest-lib to have the direct connection to
BI. Then update the dependencies of cozy-harvest-lib.
=> feat: Update libs

src/ducks/transfers/TransferPage.jsx, src/ducks/transfers/steps/TransferDoneImg.jsx, src/ducks/transfers/steps/TransferErrorImg.jsx, src/ducks/transfers/steps/TransferState.jsx, src/ducks/transfers/styles.styl
Refactor to be able to customize transfer success image.
=> feat: Ability to customize transfer state image

src/ducks/balance/AccountRow.styl
=> feat: Use semantic CSS vars for account row

package.json, yarn.lock
To get new maif bi api for client side bi account creation
=> chore: Upgrade cozy-harvest-lib

src/components/Bar.jsx, src/components/BarBalance/styles.styl, src/components/Title/PageTitle.jsx, src/components/Title/PageTitle.styl, src/components/Title/Title.styl, src/ducks/settings/GroupsSettings.styl, src/ducks/transfers/TransferPage.jsx
Small graphic tweaks.
The most important is a fix of ellipsis in the bar title.
Commits are self explanatory.
=> Various styling tweaks

manifest.webapp, package.json, scripts/release.sh, src/ducks/settings/NewAccountSettings.jsx, src/ducks/transactions/__snapshots__/TransactionModal.spec.jsx.snap, yarn.lock
Each commit is self explanatory.
=> Small things

package.json, yarn.lock
To make maif banks able to run its banking connectors
=> feat: Update Harvest to 1.41.3

package.json, yarn.lock
To allow maif banks to get proper bi api url in the end
=> feat: Upgrade harvest to 2.1.1

src/components/KonnectorUpdateInfo/index.jsx, src/ducks/balance/Balance.jsx, src/ducks/balance/History.jsx, src/ducks/brandDictionary/selectors.js, src/ducks/categories/CategoriesPage.jsx, src/ducks/chart/selectors.js, src/ducks/client/utils.js, src/ducks/loan/LoanListPage.jsx, src/ducks/pin/PinGuard.jsx, src/ducks/recurrence/RecurrencePage.jsx, src/ducks/recurrence/RecurrencesPage.jsx, src/ducks/reimbursements/Reimbursements.jsx, src/ducks/settings/AccountsSettings.jsx, src/ducks/settings/Configuration.jsx, src/ducks/settings/GroupsSettings.jsx, src/ducks/transactions/TransactionRecurrenceEditor.jsx, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transfers/TransferPage.jsx
Refactor to use cozy-client functions
fix https://github.com/cozy/cozy-banks/issues/1864
=> refactor: Use isQueryLoading and hasQueryBeenLoaded from cozy-client

CODEOWNERS
Easier to manage people in the team across different repository
Ability to do random code assignment
=> chore: Change codeowners to have a team

src/main.jsx
Otherwise the user has to login/logout for her flags to be synced
=> feat: Refresh flags on app resume / tab focus

config/webpack.config.plugins.js, package.json, src/ducks/settings/HarvestBankAccountSettings.jsx, src/ducks/tracking/browser.jsx, yarn.lock
Depends on https://github.com/cozy/cozy-libs/pull/1117
Through Harvest's new TrackingContext, we connect the tracker from
banks to events coming from Harvest.
This is ready to review, the CI is red because harvest has not been updated yet.
=> Handles tracking inside harvest

src/components/RouterContext.jsx, src/ducks/analysis/AnalysisTabs.jsx, src/ducks/recurrence/RecurrencePage.jsx, src/ducks/recurrence/RecurrencesPage.jsx, src/ducks/search/SearchPage.jsx, src/ducks/settings/AccountsSettings.jsx, src/ducks/settings/Settings.jsx, src/ducks/transactions/TransactionHeader.jsx, src/ducks/transactions/TransactionModal.jsx, src/ducks/transactions/TransactionsPage.spec.jsx
- Same hooks as react-router 4
- Reduce reliance on withRouter hook
- Promotes usage of functional component
=> refactor: Use hooks for router management

package.json, yarn.lock
To get BI webauth feature for banking connectors
=> feat: Upgrade Harvest to 2.18.1

src/components/AppRoute.jsx, src/components/__snapshots__/AppRoute.spec.jsx.snap, src/doctypes.js, src/ducks/transfers/TransferPage.jsx, src/ducks/transfers/recipients.js, src/ducks/transfers/recipients.spec.js, test/fixtures/demo.json
- Remove several entrypoints for transfer wizards
- Add track page when entering the transfer wizard
=> Transfer page improvements

package.json, src/ducks/konnectorAlerts/notification.js, src/ducks/recurrence/service.js, src/services/cli.js, src/targets/services/konnectorAlerts.js, src/targets/services/konnectorAlerts.spec.js, src/targets/services/recurrence.js, src/targets/services/service.js
- Improve tests
- Allow to run the service on a remote cozy
- Do not send konnector alerts on some cases
=> Fix konnector alerts

package.json, src/components/BarSearchInput/index.jsx, src/components/BarSearchInput/styles.styl, src/components/Carrousel.jsx, src/ducks/balance/BalanceDetailsHeader.jsx, src/ducks/balance/BalanceHeader.jsx, src/ducks/balance/BalanceHeader.styl, src/ducks/categories/CategoriesPage.jsx, src/ducks/search/SearchIconLink.jsx, src/ducks/search/SearchIconLink.styl, src/ducks/search/SearchPage.jsx, src/ducks/transactions/TransactionRow.jsx, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/Transactions.spec.jsx, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transactions/actions/HealthLinkAction.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
- Use fuse.js to search fuzzily
- Display the search icon in the bar on mobile when in account details
- Add a reset button in the search input
- Other small things for which hopefully the commits are self explanatory
=> Improve search

src/components/EditionModal/AccountOrGroupSection.jsx, src/components/EditionModal/SpecEditionModal.jsx, src/ducks/search/SearchPage.jsx, src/ducks/settings/Configuration.jsx, src/locales/fr.json
- Wording improvements
- Ability to deactivate the health section in the configuration for contexts
where there are no health connectors
- Other small things where commits are self explanatory
=> Small improvements

src/components/EditionModal/EditionModal.jsx, src/ducks/settings/Configuration.jsx, src/ducks/settings/Rules.jsx, src/ducks/tracking/tracker.js
Small fixes, I am merging as soon as this is green.
=> Tracking fixes

src/components/Carrousel.jsx, src/components/Carrousel.spec.jsx, src/ducks/transactions/TransactionPageErrors/errors.js
Due to untested recent refactors, the Carrousel did not work correctly
=> fix: Carrousel would crash

.travis.yml, docs/dev.md, src/components/App.jsx, src/components/useKeyboardState.jsx, src/ducks/konnectorAlerts/notification.spec.js, src/ducks/recurrence/queries.js, src/targets/mobile/config.xml
- Hide nav bar when keyboard is shown (use cordova-plugin-ionic-keyboard)
- Add sort by field to query otherwise recurrence page does not work
=> Small mobile fixes

src/ducks/account/AccountSwitch.jsx, src/ducks/account/AccountSwitch.styl, src/locales/en.json, src/locales/fr.json
AccountSwitch had been coded a long time ago and was still
implemented with an Overlay and a custom Modal.
Now that we have proper Dialog and List items, it becomes
trivial to code the AccountSwitch :)
Extra:
- Add account icons
- Removed a lot of custom stylus :tada:
=> feat: Use List and Dialog to implement AccountSwitch

package.json, src/ducks/transfers/TransferGate.jsx, src/ducks/transfers/TransferPage.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
A flag can be set on Bender to block transfers.
=> feat: Block transfer if flag is set on Bender

config/webpack.config.plugins.js, package.json, src/components/Header/Header.jsx, src/components/Header/__snapshots__/Header.spec.jsx.snap, src/ducks/balance/AccountsImporting.jsx, src/ducks/categories/CategoriesPage.jsx, src/ducks/tracking/browser.jsx, src/ducks/tracking/tracker.js, src/ducks/transactions/TransactionModal.jsx, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transactions/__snapshots__/TransactionModal.spec.jsx.snap, src/ducks/transfers/TransferPage.jsx, src/ducks/transfers/steps/Amount.jsx, yarn.lock
Add and modify tracking events
Other small improvements that are described in the commits
=> Tracking improvements

src/ducks/categories/CategoriesHeader.jsx, src/ducks/recurrence/RecurrencePage.jsx, src/ducks/recurrence/RecurrencesPage.jsx, src/ducks/settings/Settings.jsx
- Categories page
- Recurrence page
Merging as soon as this is green since it is small.
=> feat: Add LegalMention to analysis pages

package.json, src/ducks/balance/AccountRow.jsx, src/ducks/balance/AccountRow.styl, src/ducks/balance/AccountRowCaption.jsx, src/ducks/balance/AccountRowLoading.jsx, src/ducks/balance/AccountsList.jsx, src/ducks/balance/AccountsList.styl, src/ducks/balance/GroupPanel.jsx, src/ducks/settings/Sections.jsx, src/ducks/settings/Sections.styl, src/ducks/settings/ToggleRow.jsx, src/ducks/settings/ToggleRow.styl, yarn.lock
This way, we rely on the List components from MUI and we can
remove a lot of custom CSS.
=> Feat: Use List / ListItem for Balance panel

src/ducks/settings/Debug.jsx
Added this part to test event going to the native part
=> feat: Native comm part in debug

src/ducks/future/PlannedTransactionsPage.jsx, src/ducks/personal-info/PersonalInfoDialog.jsx, src/locales/en.json, src/locales/fr.json
One typo fixed
Added two events for tracking
=> Smallish improvements

src/ducks/account/AccountSwitch.jsx, src/ducks/account/AccountSwitch.spec.jsx
=> fix: Fix group label

src/ducks/categories/CategoriesHeader.jsx, src/ducks/future/PlannedTransactionsPage.jsx, src/ducks/recurrence/RecurrencesPage.jsx
-  Empty Component has cozy as default value
=> fix: We can pass any icon name for Empty component

babel.config.js, package.json, src/ducks/personal-info/PersonalInfoDialog.jsx, src/ducks/personal-info/PersonalInfoDialog.spec.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
- fix: set correctly nationality to initialize page
- feat: adding birthcountry field and adding of test about it
- fix: adding of test about mandatory fields and translation missing
- chore: Adding of optional chaining in babel plugins
=> fix: Fix edit personal info

src/ducks/personal-info/PersonalInfoDialog.jsx, src/ducks/personal-info/PersonalInfoDialog.spec.jsx, src/ducks/personal-info/utils.js, src/ducks/transfers/TransferPage.spec.jsx, src/locales/en.json, src/locales/fr.json
- Change birth city and birth country placeholder + fix tests
- Addition of birth country field as a required field to accesses to transfer page + fix tests
- Display the validation message in red
=> fix: Some fix ui for Edit Personal Info

src/ducks/transfers/TransferPage.jsx, src/ducks/transfers/TransferPage.spec.jsx
- Correctly display loading when click on transfer confirmation
- Add property to allows hide as we wish reimbursements notification in configuration page
=> fix: several fixes ui

package.json, src/components/EditionModal/EditionModal.jsx, src/ducks/categories/CategoriesHeader.jsx, src/main.jsx, yarn.lock
Each commit is self explanatory.
=> Fix small bugs

package.json, src/main.jsx, src/styles/mobile.styl, yarn.lock
I re-add fastclick since otherwise clicks are too slow on iOS.
=> Clicks on mobile

src/components/Loading/Loading.jsx, src/ducks/balance/NoAccount.jsx, src/ducks/balance/NoAccount.styl, src/ducks/categories/CategoriesHeader.jsx
- fix: Regression on home page when no account
- feat: add color to props of the Loading component
- fix: Add legal mention when no account
- feat: Enriched No Account UI
=> S9 empty state maif

src/ducks/balance/HistoryChart.jsx, src/utils/flag.js
- fix: Amount blur was broken
- fix: Graph show most recent months
=> Some fixes abount amount blur and Graph

package.json, src/ducks/transactions/TransactionRow.jsx, src/ducks/transactions/Transactions.jsx, yarn.lock
- fix: Change dateAndGroup to id (from array) key for Transactions component
Allows to have unique key. Because, it can happen to have the same date And Group
- fix: Disable onClick for RowMobile Component if not _id
- Disable onClick if transaction._id is undefined
- Active css when transaction._id exist
- chore: Update cozy-harvest-lib from 3.2.0 to 3.7.1
=> Fix on unauthorized click

src/logger.js
Add minilog logger.
Can be enabled in the console via minilog.enable()
=> feat: Add logger

src/store/persistedState.js
=> fix: Set default reducer for mobile object

src/components/Table/index.jsx, src/ducks/settings/GroupsSettings.jsx, src/ducks/settings/GroupsSettings.spec.jsx
The group settings page would crash because getGroupLabel need to be called with t.
- Added a test for GroupsSettings
=> Fix group settings

src/ducks/budgetAlerts/CategoryBudgetNotificationView.js, src/ducks/konnectorAlerts/notification.js, src/ducks/notifications/BalanceLower/index.js, src/ducks/notifications/BaseNotificationView.js, src/ducks/notifications/DelayedDebit/index.js, src/ducks/notifications/HealthBillLinked/index.js, src/ducks/notifications/TransactionGreater/index.js, src/ducks/notifications/TransactionGreater/index.spec.js, src/targets/services/service.js
Add source "Cozy" in the payload of all push notifications. This helps
distinguish push notifications coming from cozy from other push
notifications.
=> feat: Add generic extra attributes to all push notifications

package.json, src/ducks/transactions/FileOpener.jsx, yarn.lock
On souhaite avoir une visualisation des fichiers comme celle que l'on a dans Drive
=> File viewer behavior as the one in Drive

package.json, src/ducks/transactions/FileOpener.jsx, yarn.lock
=> feat: Use dark iframe for FileOpener

package.json, src/components/ErrorBoundary/Error.jsx, src/components/ErrorBoundary/Error.spec.jsx, src/components/ErrorBoundary/Error.styl, src/ducks/search/SearchPage.spec.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
=> feat: Change Error page

src/ducks/transactions/TransactionRow.jsx
Allows to have the possibility to enable/disable it
=> feat: Feature flag for Transaction Actions

package.json, src/ducks/transactions/TransactionCategoryEditor.jsx, src/ducks/transactions/TransactionRow.jsx, yarn.lock
Back button was not shown correctly.
=> NestedSelectModal fixes

package.json, src/ducks/settings/HarvestBankAccountSettings.jsx, yarn.lock
- Add reconnect props
- Update Harvest Lib to pass reconnect props
=> fix: add mapping route for reconnect

manifest.webapp, src/ducks/context/BanksContext.jsx, src/ducks/context/BanksContext.spec.jsx, src/ducks/context/JobsContext.spec.jsx, src/targets/mobile/config.xml, src/utils/triggers.js
Before we displayed all konnectors in progress, except that it is not necessary.
Now we display only the banking konnector in progress.
=> Fix show banks konnector

src/ducks/transactions/actions/AppLinkAction.jsx, src/ducks/transactions/actions/HealthLinkAction.jsx, src/ducks/transactions/actions/ReimbursementStatusAction/ReimbursementStatusAction.jsx
=> fix: Click on transaction actions does not open the transaction dialog

package.json, src/ducks/balance/AccountRowLoading.jsx, src/ducks/settings/AccountListItem.jsx, src/ducks/settings/AccountsListSettings.jsx, src/ducks/settings/AccountsSettings.spec.jsx, src/ducks/settings/helpers/jobs.js, src/hooks/useAppsInMaintenance.js, src/locales/en.json, src/locales/fr.json, yarn.lock
Error and maintenance indicator in settings / accounts
=> Maintenance konn settings

package.json, yarn.lock
Upgrading harvest to 5.10.1
Add the banque de savoie banks (in banque populaire)
=> chore: Upgrade harvest for new bank

docs/services.md
Add a warning with a link to the PR for stateful notifications.
=> Docs for PR draft on stateful notifications

src/ducks/appSuggestions/services.js, src/ducks/appSuggestions/services.spec.js, src/ducks/notifications/LateHealthReimbursement/index.js, src/ducks/notifications/LateHealthReimbursement/index.spec.js, src/ducks/notifications/TransactionGreater/index.js, src/ducks/notifications/services.js
Those commits were made while doing other service related tasks and
extracted.
The app suggestion service had been broken by an upstream update, I
added a test so that it cannot happen anymore.
Same for the onSuccess of LateHealthReimbursements.
=> Improvements to services

src/components/App.jsx, src/components/BackButton/index.jsx, src/components/Title/PageTitle.jsx, src/ducks/analysis/AnalysisPage.jsx, src/ducks/analysis/AnalysisTabs.jsx, src/ducks/analysis/index.jsx, src/ducks/balance/AccountSwitchBalanceDetails.jsx, src/ducks/balance/BalanceDetailsHeader.jsx, src/ducks/balance/BalanceHeader.jsx, src/ducks/balance/HeaderTitle.jsx, src/ducks/balance/PageTitleBalanceHeader.jsx, src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoryAccountSwitch.jsx, src/ducks/categories/DateSelectorHeader/index.jsx, src/ducks/categories/IncomeToggle.jsx, src/ducks/commons/Nav.jsx, src/ducks/commons/helpers.jsx, src/ducks/recurrence/Bundles.jsx, src/ducks/recurrence/RecurrencesPage.jsx, src/ducks/settings/Settings.jsx, src/ducks/settings/TabsHeader/index.jsx
This PR does not add any direct functionality but allows the possibility of overriding some components as desired in our case.
- Some grouping of components in one, to make the code more readable and easily override
- Several default props overrided
=> Customization

src/ducks/balance/AccountRow.jsx, src/ducks/balance/AccountRowCaption.jsx, src/ducks/balance/AccountsList.jsx, src/ducks/balance/AccountsList.spec.jsx, src/ducks/balance/GroupPanel.spec.jsx, src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoriesPage.jsx, src/ducks/categories/categoriesMap.spec.js, src/ducks/settings/AccountListItem.jsx, src/ducks/settings/AccountsListSettings.jsx, src/ducks/settings/AccountsSettings.jsx, src/ducks/settings/AccountsSettings.spec.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertCard.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertSettingsPane.jsx, src/ducks/settings/CategoryAlerts/CategoryAlertSettingsPane.spec.jsx, src/ducks/settings/Configuration.jsx, src/ducks/settings/DelayedDebitAlertRules.jsx, src/ducks/settings/EditableSettingCard.jsx, src/ducks/settings/HarvestBankAccountSettings.jsx, src/ducks/settings/useList.js, yarn.lock
Again, with the help of why-did-you-render, try to limit the number
of unnecessary renders. Principal strategies used:
* useCallback
* useMemo
* bound methods in class constructor
* put data observers in smaller components to have less "big" renders
=> Render perfs

src/components/KonnectorUpdateInfo/index.jsx, src/components/KonnectorUpdateInfo/index.spec.jsx, src/ducks/balance/AccountsImporting.spec.jsx, src/ducks/transactions/TriggerErrorCard.spec.jsx
fix: Blank screen on store (incorrect url)
useRedirectionURL returns a tuple value
not just an url.
The url used was therefore not usable as such
=> fix: Blank screen on store (incorrect url)

src/ducks/account/AccountSwitch.jsx, src/ducks/balance/GroupPanel.jsx, src/ducks/categories/CategoriesHeader.jsx, src/ducks/categories/CategoryAccountSwitch.jsx
- Delete multiple error logs
- Add inisidebar props (useful for an override)
=> Small fixes and add prop

src/ducks/demo/AugmentedModal.jsx, src/ducks/demo/AugmentedModal.styl, src/ducks/demo/VentePrivee.jsx, src/ducks/demo/helpers.js
Migration of the last modals in Dialog
=> Migration modal

CODEOWNERS
=> chore: Remove codeowners

src/ducks/balance/AccountRow.jsx, src/ducks/balance/GroupPanel.jsx, src/ducks/balance/History.styl, src/ducks/groups/helpers.js, src/ducks/settings/GroupSettings.jsx, src/ducks/settings/GroupSettings.spec.jsx, src/ducks/settings/GroupsSettings.styl, src/utils/multiKeyBy.js, src/utils/multiKeyBy.spec.jsx
fix: Ellipsis on number column
feat: Add other groups column
feat: Always hide HistoryChart scrollbar
feat: Deactivate transition on home page accordions
=> Ux improvements

docs/dev.md, src/targets/mobile/config.xml
Update the docs to reflect the workflow we have now to publish
Android and iOS apps.
=> Better mobile docs

package.json, src/ducks/transactions/Transactions.spec.jsx, yarn.lock
Update cozy-ui to 51.0.2
will be merged when CI green
=> feat: Update cozy-ui to 51.0.2

manifest.webapp, src/targets/mobile/config.xml
=> chore: Bump version to 1.32.0

src/ducks/transactions/TransactionRow/TransactionRowMobile.jsx, src/ducks/transactions/Transactions.jsx
=> refactor: Reword hasSeparator in hasDivider for transactions

src/ducks/selection/SelectionBar.jsx
see commit message
cf https://github.com/cozy/cozy-banks/pull/2144#pullrequestreview-698900328
=> refactor: Add propTypes and memo on SelectionBar

src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx, src/ducks/transactions/TransactionRow/TransactionRowDesktop.spec.jsx, src/ducks/transactions/Transactions.spec.jsx
The label should not have an on click handler as the row is already 
handling it. Besides, it had the wrong handler.
=> fix: Click on transaction label opens category modal

src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx, src/ducks/transactions/Transactions.styl
Gives feedback to the user that something different from
the normal row click is going to happen
=> feat: Small hover effect on category icon

src/ducks/settings/AccountListItem.jsx
If there is no action attached to the content.
If you want to display an icon aligned to the right
let's just use the icon directly
=> fix: Don't use ListSecondaryAction

CHANGELOG.md, package.json, yarn.lock
Hide owner field in account configuration when Contacts app is not installed
=> feat: Update cozy-harvest-lib to 6.4.0

CHANGELOG.md
=> docs: Add push notif server mention in CHANGELOG

src/ducks/client/links.js
Add warmup queries to populate the most important indexes.
It improves for example the loading time of the analysis page in the following scenario:
- Pouch has finished its replication for the transaction doctype
- When going to the analysis page, a query for the current account(s) transactions is fired
- Pouch has not yet indexes for the given query and it takes a long time to build them
- So while the index is being built, the user sees a spinner
With warmed up queries, the cozy pouch link does not consider itself ready while the warm up queries have not returned. So it will pass the query down to the next link = stack link here. It means that while the index is being built, the stack is responding to the query. After the warm up query succeed, it means the index has been built, and now …
=> feat: Warmup queries to have indexes on account / date / date & account [apk]

package.json, yarn.lock
=> chore: ach package removed (not used anymore)

CHANGELOG.md, src/ducks/categories/CategoriesPage.jsx, src/ducks/categories/CategoriesPage/CategoryTransactions.jsx, src/ducks/categories/CategoriesPage/enhanceCategoriesPage.jsx, src/ducks/client/links.js, src/ducks/transactions/TransactionModal/TransactionModalInfoContent.jsx, src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx, src/ducks/transactions/constants.js, src/ducks/transactions/helpers.js, src/ducks/transactions/helpers.spec.js, src/ducks/transactions/queries.js, src/ducks/transactions/queries.spec.js
according to the selected period
=> fix: Reassigned transactions are displayed in the correct period

CHANGELOG.md, src/ducks/transactions/queries.js, src/ducks/transactions/queries.spec.js
to have first the attribute on which we have an equality predicate
fix https://github.com/cozy/cozy-banks/issues/2209
=> Change indexes order for transactions queries

CHANGELOG.md, src/ducks/transactions/TransactionRow/TransactionOpener.jsx, src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx, src/ducks/transactions/Transactions.styl
already reviewed https://github.com/cozy/cozy-banks/pull/2213
will be merged as soon as CI green
=> fix: Transactions are no longer selectable in future page

CHANGELOG.md, src/ducks/future/HeaderInfoCard.jsx, src/ducks/future/PlannedTransactionsPage.jsx, src/ducks/future/PlannedTransactionsPageHeader.jsx, src/ducks/future/styles.styl
already reviewed https://github.com/cozy/cozy-banks/pull/2214
will be merged as soon as CI green
=> fix: Planned transactions page shows transactions correctly on tablet

CHANGELOG.md, docs/notifications.md, docs/services.md, src/ducks/budgetAlerts/service.spec.js, src/ducks/notifications/BalanceLower/index.js, src/ducks/notifications/BalanceLower/index.spec.js, src/ducks/notifications/CategoryBudget/index.js, src/ducks/notifications/TransactionGreater/index.js, src/ducks/notifications/TransactionGreater/index.spec.js
Dans les notifications push sur mobile, on souhaite séparer le contenu par un retour à la ligne et non plus une virgule.
⚠️ A cherrypicker sur master après merge
=> feat: Separates content in notification

CHANGELOG.md, docs/notifications.md, docs/services.md, src/ducks/budgetAlerts/service.spec.js, src/ducks/notifications/BalanceLower/index.js, src/ducks/notifications/BalanceLower/index.spec.js, src/ducks/notifications/CategoryBudget/index.js, src/ducks/notifications/TransactionGreater/index.js, src/ducks/notifications/TransactionGreater/index.spec.js
already reviewed https://github.com/cozy/cozy-banks/pull/2218
will be merged as soon as CI green
=> feat: Separates content with a return to line in notifications

package.json, yarn.lock
To get the right icons and avoid warnings for query
=> fix: Upgrade cozy-bar

CHANGELOG.md, src/ducks/recurrence/__snapshots__/search.spec.js.snap, src/ducks/recurrence/search.js, src/ducks/recurrence/search.spec.js, src/ducks/recurrence/service.js, src/ducks/recurrence/utils.js
S'il y a déjà des récurrences, on souhaite d'abord mettre à jour les récurrences existantes avant d'essayer de créer de nouvelles récurrences. Alors qu'avant, dans ce cas là, on ne faisait que mettre à jour les récurrences existantes.
=> Recurrence can be updated and created in the same batch

src/ducks/recurrence/utils.js
Old code never used was merged by mistake from this [PR #2162](https://github.com/cozy/cozy-banks/pull/2162)
=> refactor: Remove old code

CHANGELOG.md, src/ducks/balance/BalanceDetailsHeader.jsx, src/ducks/context/SelectionContext.jsx, src/ducks/search/SearchHeader.jsx, src/ducks/selection/SelectionBar.jsx, src/ducks/selection/SelectionIconLink.jsx, src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx, src/ducks/transactions/Transactions.jsx, src/ducks/transactions/header/TableHead.jsx
Pour désactiver le fait que la feature soit derrière un flag, et donc pour la rendre accessible à tout le monde.
=> feat: Enabled selection mode for everyone

CHANGELOG.md, src/ducks/recurrence/__snapshots__/search-with-existing-recurrence.spec.js.snap, src/ducks/recurrence/search-with-existing-recurrence.spec.js, src/ducks/recurrence/search.js, src/ducks/recurrence/service.js, src/ducks/recurrence/utils.js, src/locales/en.json, src/locales/fr.json
and migration modal wording.
already merged in 1.35.0 as patch : https://github.com/cozy/cozy-banks/pull/2236 and https://github.com/cozy/cozy-banks/pull/2235
will be merded as soon as CI green
=> Remove 100 days back condition for creating/updating recurrence

package.json
permet de lancer webpack-analyzer
=> chore: Add analyzer command in package.json

CHANGELOG.md, src/actions/accounts.js, src/actions/accounts.spec.js
=> refactor: Use CozyClient links in removeAccountFromGroups

CHANGELOG.md, src/ducks/future/selectors.js, src/ducks/recurrence/api.js, src/ducks/recurrence/api.spec.js, src/ducks/recurrence/utils.js, src/ducks/recurrence/utils.spec.js
On a rajouté un latestAmount dans io.cozy.bank.recurrence voir https://github.com/cozy/cozy-doctypes/pull/185
=> Futur balances shows latest transaction amount

CHANGELOG.md, package.json, src/components/SelectDates/SelectDates.jsx, yarn.lock
mergé après CI verte pour débloquer la beta Maif
=> Fix Accordion border color and SelectDates text color

CHANGELOG.md, src/ducks/devtools/Notifications.jsx, src/ducks/konnectorAlerts/notification.js
Les notifications d'alertes de connecteurs KO renvoie à la page settings/accounts en cliquant dessus.
=> Alert notifications link for KO connectors

package.json, yarn.lock
See https://github.com/konnectors/libs/pull/816
=> fix: Local categorization

CHANGELOG.md, package.json, yarn.lock
To get the correct contact mail in error messages, according to the
context configuration
https://github.com/cozy/cozy-libs/pull/1392
=> feat: Upgrade Harvest -> mail contact

src/targets/services/konnectorAlerts/createTriggerAt.js
see commit messages
(commit qui trainait sur une ancienne branche qui n'a pas abouti à une PR)
=> Add doc and change log message for konnectorAlerts service

CHANGELOG.md, src/doctypes.js
C'est dans le field qu'on trouve les infos des remboursements
=> fix: Add reimbursements field in makeBalanceTransactionsConn

CHANGELOG.md
on a récupéré une feature de master pour la mettre sur la release 1.40.0 https://github.com/cozy/cozy-banks/commit/84e231e808784e85d6e48e69210ed5a917a10e4a, on déplace donc l'entrée dans le changelog
=> docs: Changelog

src/selectors/index.spec.jsx
After the investigation https://github.com/cozy/cozy-banks/pull/2322 , here are the tests
=> test(selectors): document expected recomputations by providing use cases

test/jest.setup.js
Will be handled in a better way once all dependencies are
up to date
=> fix: Mock webviewIntentProvider to fix tests

package.json, src/AppContainer.jsx, yarn.lock
Also require cozy-intent latest version
=> fix: Inject cozy-bar callback into cozy-intent

package.json, yarn.lock
Required for better UI in App Amirale
=> feat: Upgrade cozy-bar to latest

package.json, src/components/App.jsx, test/jest.setup.js, yarn.lock
https://trello.com/c/KWxWhWBK/274-%F0%9F%8E%81-e162-gestion-des-navbar-et-statusbar-dans-lensemble-de-laa-4-jh
For statusbar and navbar to be handled in app amirale, cozy-intent and more importantly cozy-ui have to be updated on every cozy app
=> feat: Upgrade cozy dependencies for App Amirale navigation

src/ducks/brandDictionary/__snapshots__/index.spec.js.snap, src/ducks/brandDictionary/brands.json
Adding a new brand in dictionnary
=> feat: Add new brand GEG

CHANGELOG.md, package.json, src/components/BackButton/index.jsx, src/components/BarSearchInput/index.jsx, src/ducks/recurrence/RecurrencePage/BundleInfo.jsx, src/ducks/search/EarliestTransactionDate.jsx, src/ducks/search/SearchIconLink.jsx, src/ducks/selection/SelectionIconLink.jsx, src/ducks/settings/EditableSettingCard.jsx, src/ducks/transactions/TransactionModal/TransactionModalInfoContent.jsx, src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx, yarn.lock
on branche release/1.43.0
same as https://github.com/cozy/cozy-banks/pull/2364
will be merged as soon as the other is too
=> Upgrade cozy-ui to 67.0.2 to get bugfix on Matomo tracking

src/ducks/recurrence/RecurrencesPage.jsx
no changelog, this is not a fix according to 1.42.0 version
=> fix: RecurencesPage error on mount

CHANGELOG.md, src/locales/fr.json
idem que https://github.com/cozy/cozy-banks/pull/2368 mais pour la branche `/release/1.43.0`
=> fix: Deprecated bundles help french translation

CHANGELOG.md, package.json, yarn.lock
already merged here https://github.com/cozy/cozy-banks/pull/2373
=> feat: Upgrade cozy-harvest-lib to 9.4.0

src/ducks/settings/HarvestSwitch.jsx
already merged on master https://github.com/cozy/cozy-banks/pull/2374
no need to review, will be merged as soon as CI is green
=> fix: Add replaceHistory method for Harvest

CHANGELOG.md, package.json, yarn.lock
same as https://github.com/cozy/cozy-banks/pull/2377
=> feat: Upgrade cozy-client to 29.0.1

package.json, yarn.lock
same as https://github.com/cozy/cozy-banks/pull/2378
=> feat: Upgrade cozy-pouch-link to have same version as cozy-client

CHANGELOG.md, package.json, src/ducks/account/AccountSwitch.jsx, src/ducks/account/AccountSwitch.styl, yarn.lock
pas d'override côté maif à gérer
=> Use DropdownText comp instead of custom in AccountSwitch

CHANGELOG.md, package.json, yarn.lock
idem que https://github.com/cozy/cozy-banks/pull/2387 mais sur master
=> feat: Update harvest to 9.11.0

CHANGELOG.md, package.json, yarn.lock
To not show Popup when intentsApi parameter is given
=> feat: Upgrade Harvest to 9.12

CHANGELOG.md, package.json, yarn.lock
To get harvest fixes:
- do not double encode oauth url
=> feat: Update harvest to 9.12.3

src/ducks/settings/HarvestBankAccountSettings.jsx
lié à https://github.com/cozy/cozy-banks/pull/2396
=> Use absolute import instead of relative

CHANGELOG.md, src/locales/en.json, src/locales/fr.json
when importing data from a bank is completed
lié à https://github.com/cozy/cozy-banks/pull/2401
=> feat: Change wording for toast message

CHANGELOG.md, src/ducks/transactions/TransactionPageErrors/ReconnectTriggerButton.jsx
lié à https://github.com/cozy/cozy-banks/pull/2409
=> Remove icon on ReconnectTriggerButton

src/ducks/settings/HarvestBankAccountSettings.jsx
already merged on release/1.44
=> refactor: Fix lint errors

CHANGELOG.md, src/ducks/balance/AccountsImporting.jsx, src/ducks/balance/AccountsImporting.styl
lié à https://github.com/cozy/cozy-banks/pull/2420
=> fix: Colors when importing account

jsconfig.json
It’s one small step for man, one giant leap for "cozy-banks" developers! 🎁
=> chore: Add jsconfig file for assist navigation in editor

CHANGELOG.md, package.json, yarn.lock
=> feat: Upgrade cozy-ui to 70.2.4

src/components/Tag/TagAddNewTagModal.jsx
pas de changelog, on est dans l'entrée `Add tags on transactions`
=> feat: Add autofocus on TagAddNewTagModal input

src/components/useDocuments.js, src/doctypes.js, src/ducks/transactions/TransactionModal/DeleteTransactionRow.jsx, src/ducks/transactions/TransactionModal/TransactionModal.spec.jsx, src/ducks/transactions/Transactions.spec.jsx, src/ducks/transactions/helpers.js
Remove "transaction" relationships on all tags before destroy the transaction.
=> Delete transaction with tags

src/ducks/tags/TagDialog.jsx, src/ducks/tags/TagDialogTitle.jsx, src/locales/en.json
This also prepares for the override
=> fix: make the back button from `TagDialog` custom

src/components/Tag/TagAddModalContentList.jsx, src/components/Tag/TagAddModalOrBottomSheet.jsx, src/components/Tag/TagBottomSheet.jsx
Les Tags pouvant être nombreux, cette PR tente une approche via un auto-sroll du contenu si il dépasse une certaine hauteur.
=> Fix/Tags bottomSheet

CHANGELOG.md, package.json, yarn.lock
For fix BottomSheet with dynamic content
=> Update cozy-ui to 70.6.1

src/components/Tag/TagAddNewTagModal.jsx, src/components/Tag/TagAddNewTagModal.spec.jsx
Ajout des tests suite aux retours https://github.com/cozy/cozy-banks/pull/2467
=> test: Add tests for TagAddNewTagModal component

CHANGELOG.md, package.json, yarn.lock
To have a better handling of duplicate accounts : locale + realtime in bank accounts
=> fix: Upgrade harvest to 9.26.6

CHANGELOG.md, package.json, yarn.lock
=> feat: Upgrade cozy-ui to 74.0.0

package.json, yarn.lock
to fix ListItem button focus bug
=> Upgrade cozy-ui from 74.6.0 to 74.6.1 on `/release/1.44.0` branch

package.json, yarn.lock
Principalement pour récupérer le fix sur les ListItem button
```
* Upgrade cozy-ui from 74.3.0 to 74.6.1
```
=> feat: Upgrade cozy-ui from 74.3.0 to 74.6.1

src/ducks/recurrence/RecurrencesPage.jsx, src/locales/en.json, src/locales/fr.json
These are fixes for #2505.
(changelog omitted since the fixes concern changes that are not yet in beta)
=> Fix view more button and deprecated notice alignment issues

src/components/AppRoute.jsx, src/components/__snapshots__/AppRoute.spec.jsx.snap, src/doctypes.js, src/ducks/categories/CategoriesHeader/DesktopFragment.jsx, src/ducks/categories/CategoriesHeader/MobileFragment.jsx, src/ducks/settings/TabsHeader/index.jsx, src/ducks/tags/TagDialog.jsx, src/ducks/transactions/TransactionModal/DeleteTransactionRow.jsx, src/ducks/transactions/TransactionModal/TransactionModalInfoContent.jsx, src/ducks/transactions/TransactionRow/TransactionRowDesktop.jsx, src/ducks/transactions/TransactionRow/TransactionRowMobile.jsx, src/ducks/transactions/header/TableHead.jsx
```
* Remove flag for Tags feature
```
=> Remove banks.tags.enabled flag

src/targets/services/service.js
Backports #2540
```
* Fix notifications issues on the b2c app
```
=> Backport "RunService will always wait for flag to be initialized"

package.json, yarn.lock
```
* Upgrade cozy-bar from 8.9.3 to 8.9.4
```
=> fix: Safari settings dropdown margin

package.json, yarn.lock
```
* Only update cozy-client store when refreshing contracts 
```
=> feat: Upgrade cozy-harvest-lib to 9.32.2

package.json, yarn.lock
Add new links in settings dropdown
```
* Upgrade cozy-bar from 8.9.3 to 8.10.0
```
=> feat: Upgrade cozy-bar from 8.9.3 to 8.10.0

package.json, yarn.lock
to get https://github.com/cozy/cozy-libs/pull/1904
```
* Update harvest 9.32.2 to 9.32.3
```
=> Branch 1.47.1 - Update harvest 9.32.2 to 9.32.3

src/ducks/konnectorAlerts/notification.js, src/targets/services/konnectorAlerts/sendTriggerNotifications.js
when sending notification, and to disable notification sending
backport de https://github.com/cozy/cozy-banks/pull/2568
=> chore: Add some log for konnectorAlert service

src/ducks/groups/helpers.js, src/ducks/settings/CategoryAlerts/AccountOrGroupLabel.jsx
```
* Localize account and group labels in notification settings
```
=> Localize account and group labels in notification settings by using the dedicated helpers

src/ducks/categories/CategoriesHeader/AdvancedFilter.jsx
```
* Right arrow on advanced filter in category page was not clickable
```
=> fix(AdvancedFilter): Right arrow was not clickable

src/ducks/analysis/AnalysisTabs.jsx, src/ducks/settings/TabsHeader/index.jsx
```
* Use absolute links for analysis tabs
```
=> Use absolute links for analysis tabs

package.json, yarn.lock
Fix missing Claudy icon.
```
* Upgrade cozy-bar from 8.11.2 to 8.12.1
```
=> feat: Upgrade cozy-bar from 8.11.2 to 8.12.1

src/targets/services/onOperationOrBillCreateHelpers.js
for doTransactionsMatching and doBillsMatching
```
* More specific log for doTransactionsMatching and doBillsMatching in onOperationOrBillCreate
```
=> refactor: Be more specific for some logs in onOperationOrBillCreate

package.json, yarn.lock
```
* Update cozy-bar from 8.12.1 to 8.13.0
```
=> feat: Update cozy-bar from 8.12.1 to 8.13.0

src/ducks/recurrence/service.js
We can skip transactions with a recurrence or marked as not recurrent
via a partial filter instead of requesting all the transactions first
and then loop over them to remove those that we don't want to modify.
```
* Improved performance of transactions filtering in the recurrence service
```
=> perf: Improve recurrence service filtering

src/ducks/settings/Configuration.jsx, src/locales/en.json, src/locales/fr.json
This sub -section allows the export and import of banking data
```
* Add sub section in configuration settings for manage data (import/export)
```
=> feat: Add sub section in configuration settings for manage data

src/ducks/devtools/Notifications.jsx, src/ducks/konnectorAlerts/notification.js, src/ducks/notifications/BalanceGreater/index.js, src/ducks/notifications/BalanceLower/index.js, src/ducks/notifications/BaseNotificationView.js, src/ducks/notifications/CategoryBudget/index.js, src/ducks/notifications/DelayedDebit/index.js, src/ducks/notifications/HealthBillLinked/index.js, src/ducks/notifications/TransactionGreater/index.js
```
* Notifications are compatible with the new Cozy app
```
=> feat: Add redirectLink to every notifications

package.json, yarn.lock
```
* Update cozy-bar to get fixed cloud icon position
```
=> feat: Update cozy-bar to get fixed cloud icon position

src/ducks/transactions/actions/AttachedDocsAction/BillChip.jsx, src/ducks/transactions/actions/AttachedDocsAction/BillChip.spec.jsx, src/ducks/transactions/actions/KonnectorAction/index.jsx
KonnectorChip is the action on transaction row used to add a relative konnector
BillChip is also an action on transaction row (to retrieve health bill)
```
* Hide KonnectorChip by flag for health category
* Hide BillChip by flag for health category
```
=> feat: Hide KonnectorChip by flag for health category

manifest.webapp
```
* Remove native link and icon from manifest
```
=> feat: Remove native link and icon from manifest

src/ducks/transactions/TransactionRow/TransactionOpener.jsx
this https://github.com/cozy/cozy-banks/pull/2666 on 1.56.0 branch. Will be merged as soon as CI's green
=> 1.56.0 fix: Transaction modale closed by itself on some mobile devices

src/AppContainer.jsx, src/components/RawContentDialog.jsx, src/ducks/context/DisableEnforceFocusModalContext.jsx, src/ducks/transactions/TransactionModal/TransactionModal.jsx, src/ducks/transactions/actions/KonnectorAction/index.jsx, test/AppLike.jsx
```
* Fields in Intent modals must be clickable
```
=> Fix: Focus of fields when installing a konnector

src/AppContainer.jsx, src/doctypes.js, src/ducks/appSuggestions/services.js, src/ducks/appSuggestions/services.spec.js, src/ducks/billsMatching/Linker/billsToOperation/operationsFilters.spec.js, src/ducks/brandDictionary/__snapshots__/index.spec.js.snap, src/ducks/brandDictionary/brandsReducer.js, src/ducks/brandDictionary/brandsReducer.spec.js, src/ducks/brandDictionary/index.js, src/ducks/brandDictionary/index.spec.js, src/ducks/recurrence/rules.js, src/ducks/recurrence/rules.spec.js, src/ducks/recurrence/search-with-existing-recurrence.spec.js, src/ducks/recurrence/search-without-existing-recurrence.spec.js, src/ducks/reimbursements/Reimbursements.spec.jsx, src/ducks/transactions/actions/AttachedDocsAction/BillChip.spec.jsx, src/store/configureStore.js, src/targets/services/onOperationOrBillCreate.js, src/targets/services/onOperationOrBillCreateHelpers.js
```
* Use redux store instead localStorage for save all brands
* Use optimize query for get triggers without jobs
```
=> Feat: Optimize brands management

src/doctypes.js, src/ducks/balance/AccountsList.jsx, src/ducks/balance/EmptyAccount.jsx, src/ducks/brandDictionary/brandsReducer.js, src/ducks/client/checks.js, src/ducks/personal-info/utils.js, src/ducks/settings/AccountsListSettings.jsx, src/ducks/settings/AccountsSettings.spec.jsx, src/ducks/settings/HarvestBankAccountSettings.jsx, src/ducks/transactions/TransactionPageErrors/TransactionPageErrors.jsx, src/ducks/transactions/TransactionsPage.jsx, src/ducks/transactions/actions/KonnectorAction/index.jsx
```
* In order to display correctly the KonnectorChip and don't propose the installation of a clisk if it's already connected
```
=> fix: Request konnector and client worker

src/ducks/brandDictionary/index.js, src/ducks/recurrence/rules.js, src/ducks/recurrence/search.js, src/ducks/recurrence/service.js
```
* Recurrence service was trying to use `client` via `window` object.
```
=> fix: Use right client on recurrence service

.bundlemonrc, .travis.yml
=> chore: Fix travis build

package.json, src/ducks/transactions/actions/KonnectorAction/BrowserConfigurationModal.jsx, yarn.lock
```
* Open the details page when proposing to install a konnector
```
=> [VO-161] feat: Open the details page when proposing to install a konnector

src/ducks/transactions/TransactionPageErrors/HarvestRoutes.jsx, src/ducks/transactions/TransactionPageErrors/TransactionPageErrors.jsx, src/lib/queries.js
Small correction following integration of the Harvest banner
=> [VO-452 & VO-450] fix(HarvestBanner): Problem with queries

config/webpack.target.services.js
Second attempt to fix the issue because the publish wasn't good in the first : https://github.com/cozy/cozy-banks/pull/2711
```
* Build configuration to be able to send notifications into a service
```
=> fix: Build configuration to use cozy-notifications in production

src/ducks/settings/HarvestBankAccountSettings.jsx, src/ducks/settings/HarvestModal.jsx
```
* Make closable the HarvestModal in banks settings
```
=> [VO-598] fix: Make closable the HarvestModal in banks settings
